SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[F_ROUND](@VLERA AS FLOAT,@VLUP AS FLOAT) RETURNS FLOAT
BEGIN
  DECLARE   @REZULTATI FLOAT
  SET @REZULTATI= CASE WHEN @VLERA>=@VLUP THEN floor((@VLERA + @VLUP) / @VLUP) * @VLUP ELSE @VLERA END;
  RETURN @REZULTATI
END

GO
