SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[CHKBC](@KOD AS VARCHAR(100))
RETURNS INT
AS
BEGIN
DECLARE @RET AS INT
SET @RET = 0

IF (SELECT COUNT(1) FROM ARTIKUJ WHERE BC = @KOD AND KOD<>BC)>=1
	SET @RET=1

RETURN @RET
END
GO
