SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dbo].[DATE_1601] 
(	
	@Date DATETIME 
)
RETURNS VARCHAR(50)
AS
BEGIN
	DECLARE @DateStr VARCHAR(50);
	SET @DateStr = CONVERT(VARCHAR(50), @Date, 127);
	IF(LEN(@DateStr)>20)
	SET @DateStr = STUFF(@DateStr, 20, 4, '')
	RETURN @DateStr + RIGHT(SYSDATETIMEOFFSET(),6)
END
GO
