SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO



CREATE  VIEW [dbo].[AP_VIEWFT]       -- Vetem AP

AS


      SELECT KODKL=A.KOD,A.KODFKL,A.NIPT,A.NRDOK,A.DATEDOK,A.NRDSHOQ,A.DTDSHOQ,KTH=ISNULL(A.KTH,0),
             A.SHENIM1,A.SHENIM2,A.SHENIM3,A.SHENIM4,A.KMAG,A.KMON,
             B.*
        FROM FJT A LEFT JOIN FJTSCR B ON A.NRRENDOR = B.NRD
       WHERE B.TIPKLL='K';

 

GO
