SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO






CREATE     VIEW [dbo].[FDFHLIDHJE04] AS 
 SELECT TOP 100 PERCENT 
            KMAGLNKD    = KMAGLNK1,
            NRDOKLNKD   = NRDOKLNK1,
            NRFRAKSLNKD = NRFRAKSLNK1,
            DATEDOKLNKD = DATEDOKLNK1,KARTLLG,
            NRCOUNT     = COUNT(*), 
            SASI        = SUM(CASE WHEN TIP='H' THEN SASI ELSE 0-SASI END)
       FROM FDFHLIDHJE02 
   GROUP BY KMAGLNK1,NRDOKLNK1,NRFRAKSLNK1,DATEDOKLNK1,KARTLLG
     HAVING (NOT ((COUNT(*)=2) AND SUM(CASE WHEN TIP='H' THEN SASI ELSE 0-SASI END)=0))

  UNION ALL

 SELECT TOP 100 PERCENT 
            KMAGLNKD    = KMAGLNK2,
            NRDOKLNKD   = NRDOKLNK2,
            NRFRAKSLNKD = NRFRAKSLNK2,
            DATEDOKLNKD = DATEDOKLNK2,
            KARTLLG,
            NRCOUNT     = COUNT(*), 
            SASI        = SUM(CASE WHEN TIP='H' THEN SASI ELSE 0-SASI END)
       FROM FDFHLIDHJE02 
   GROUP BY KMAGLNK2,NRDOKLNK2,NRFRAKSLNK2,DATEDOKLNK2,KARTLLG
     HAVING (NOT ((COUNT(*)=2) AND SUM(CASE WHEN TIP='H' THEN SASI ELSE 0-SASI END)=0))

   ORDER BY KMAGLNKD,NRDOKLNKD,NRFRAKSLNKD,DATEDOKLNKD








GO
