SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO



CREATE VIEW [dbo].[LEVIZJEHDSM1] AS

-- kjo view duhet te behet LevizjeHDSm (duke e zendesuar ate) pas diskutimeve

      SELECT TOP 100 PERCENT     TIP='H', 
             A.NRRENDOR, A.KMAG, A.NRMAG, A.NRDOK, A.NRFRAKS, A.DATEDOK, A.DOK_JB, A.DST, A.KTH, A.SHENIM1, A.SHENIM2, A.SHENIM3, A.SHENIM4, 
             B.KOD, B.KODAF, B.KARTLLG, BC=ISNULL(B.BC,''), B.PERSHKRIM, B.CMIMM, SASIH=B.SASI, VLERAH=B.VLERAM, SASID=0, VLERAD=0, B.NJESI, 

             MASE   = ISNULL((SELECT MAX(ISNULL(MASE,''))    FROM ARTIKUJBCSCR R WHERE R.BC=B.BC AND ISNULL(B.BC,'')<>''),''),
             NGJYRE = ISNULL((SELECT MAX(ISNULL(NGJYRE,''))  FROM ARTIKUJBCSCR R WHERE R.BC=B.BC AND ISNULL(B.BC,'')<>''),''),
             CMSHBC = ISNULL((SELECT MAX(ISNULL(R.CMSH,''))  FROM ARTIKUJBCSCR R WHERE R.BC=B.BC AND ISNULL(B.BC,'')<>''),     -- R.CMSHBC
                             (SELECT MAX(ISNULL(R.CMSH,''))  FROM ARTIKUJ      R WHERE R.KOD=B.KARTLLG)),
             B.DTSKADENCE, B.SERI, B.NRD, NRRENDORSCR=B.NRRENDOR, GJENROWAUT=ISNULL(B.GJENROWAUT,0)

       FROM FH A LEFT JOIN FHSCR B ON A.NRRENDOR=B.NRD
                

  UNION ALL
  

     SELECT TOP 100 PERCENT      TIP='D',
            A.NRRENDOR, A.KMAG, A.NRMAG, A.NRDOK, A.NRFRAKS, A.DATEDOK, A.DOK_JB, A.DST, A.KTH, A.SHENIM1, A.SHENIM2, A.SHENIM3, A.SHENIM4, 
            B.KOD, B.KODAF, B.KARTLLG, BC=ISNULL(B.BC,''), B.PERSHKRIM, B.CMIMM, SASIH=0, VLERAH=0, SASID=B.SASI, VLERAD=B.VLERAM, B.NJESI, 

            MASE    = ISNULL((SELECT MAX(ISNULL(MASE,''))    FROM ARTIKUJBCSCR R WHERE R.BC=B.BC AND ISNULL(B.BC,'')<>''),''),
            NGJYRE  = ISNULL((SELECT MAX(ISNULL(NGJYRE,''))  FROM ARTIKUJBCSCR R WHERE R.BC=B.BC AND ISNULL(B.BC,'')<>''),''),
            CMSHBC  = ISNULL((SELECT MAX(ISNULL(R.CMSH,''))  FROM ARTIKUJBCSCR R WHERE R.BC=B.BC ),                            -- R.CMSHBC  
                             (SELECT MAX(ISNULL(R.CMSH,''))  FROM ARTIKUJ      R WHERE R.KOD=B.KARTLLG)),
            B.DTSKADENCE, B.SERI, B.NRD, NRRENDORSCR=B.NRRENDOR, GJENROWAUT=ISNULL(B.GJENROWAUT,0)
                                         
       FROM FD A LEFT JOIN FDSCR B ON A.NRRENDOR=B.NRD
                

  UNION ALL
  

      SELECT TOP 100 PERCENT     TIP='D',
             A.NRRENDOR, A.KMAG, NRMAG=A.NRDOK, A.NRDOK, NRFRAKS=0, A.DATEDOK, DOK_JB=1, DST='', KTH=0, A.SHENIM1, A.SHENIM2, A.SHENIM3, A.SHENIM4, 
             B.KOD, B.KODAF, B.KARTLLG, BC=ISNULL(B.BC,''), B.PERSHKRIM, B.CMIMM, SASIH=0, VLERAH=0, SASID=B.SASI, VLERAD=B.VLERAM, B.NJESI, 

             MASE    =        (SELECT MAX(ISNULL(MASE,''))   FROM ARTIKUJBCSCR R WHERE R.BC=B.BC),
             NGJYRE  =        (SELECT MAX(ISNULL(NGJYRE,'')) FROM ARTIKUJBCSCR R WHERE R.BC=B.BC),
             CMSHBC  = ISNULL((SELECT MAX(ISNULL(R.CMSH,'')) FROM ARTIKUJBCSCR R WHERE R.BC=B.BC ),                            -- R.CMSHBC
                              (SELECT MAX(ISNULL(R.CMSH,'')) FROM ARTIKUJ      R WHERE R.KOD=B.KARTLLG)),
             DTSKADENCE=NULL, SERI=0, B.NRD, NRRENDORSCR=B.NRRENDOR, GJENROWAUT=0

        FROM SM A LEFT JOIN SMSCR B ON A.NRRENDOR=B.NRD
GO
