SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO





CREATE            VIEW [dbo].[FU_POROSIORF] AS 

SELECT ORF.NRRENDOR,DATEDOK=MAX(DATEDOK),NRDOK=MAX(NRDOK),KODFKL=MAX(KODFKL),
       SHENIM1=MAX(SHENIM1),NRDSHOQ=MAX(NRDSHOQ),DTLEVRIM=MAX(DTDSHOQ),
       KMON=MAX(KMON),KURS1=MAX(KURS1),KURS2=MAX(KURS2),
       KARTLLG,PERSHKRIM=MAX(ORFSCR.PERSHKRIM),NJESI=MAX(ORFSCR.NJESI),SASI=SUM(ORFSCR.SASI),
       CMIMBS=CASE WHEN SUM(ORFSCR.SASI)<>0 THEN SUM(ORFSCR.VLPATVSH)/SUM(ORFSCR.SASI) ELSE 1 END,
       VLPATVSH=SUM(ORFSCR.VLPATVSH),VLTVSH=SUM(ORFSCR.VLTVSH),VLERABS=SUM(ORFSCR.VLERABS),ORFSCR.TIPKLL,NRDFTEXTRA=ISNULL(MAX(ORF.NRDFTEXTRA),0)
FROM ORF INNER JOIN ORFSCR ON ORF.NRRENDOR=ORFSCR.NRD
WHERE ISNULL(ORF.STATUS,0)<>0
GROUP BY ORF.NRRENDOR,ORFSCR.KARTLLG,ORFSCR.TIPKLL





GO
