SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[FJSCRZGJ]
 AS 
SELECT FJSCR.NRRENDOR,FJSCR.NRD,KODFJSCR=FJSCR.KARTLLG,FJSCR.TIPKLL,
       KARTLLG  =ISNULL(ARTIKUJSCR.KOD,      FJSCR.KARTLLG),
       NJESI    =ISNULL(ARTIKUJSCR.NJESI,    FJSCR.NJESI),
       PERSHKRIM=ISNULL(ARTIKUJSCR.PERSHKRIM,FJSCR.PERSHKRIM),
       SASI     =ISNULL(ARTIKUJSCR.KOEFICIENT,1)*FJSCR.SASI,
       VLPATVSH =CASE WHEN ARTIKUJSCR.KOD IS NOT NULL
                      THEN A.CMSH*ISNULL(ARTIKUJSCR.KOEFICIENT,1)*FJSCR.SASI
                      ELSE FJSCR.VLPATVSH END
FROM FJSCR LEFT  JOIN ARTIKUJ    ON FJSCR.KARTLLG   =ARTIKUJ.KOD
           LEFT  JOIN ARTIKUJSCR ON ARTIKUJ.NRRENDOR=ARTIKUJSCR.NRD
           LEFT  JOIN ARTIKUJ A  ON ARTIKUJSCR.KOD  =A.KOD
WHERE TIPKLL='K'

GO
