SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE     VIEW [dbo].[ARTIKUJT] AS SELECT        BARKODI=MAX(ARTIKUJ.BC),       SASIA=ISNULL(SUM(SASIH-SASID),0),       PERSHKRIMI=MAX(ARTIKUJ.PERSHKRIM),       CMIMI=MAX(ARTIKUJ.CMSH),CMimiMes=MAX(ARTIKUJ.KOSTMES),       ARTIKUJ.KOD,       KMAG=LEVIZJEHD.KMAG FROM ARTIKUJ LEFT JOIN LEVIZJEHD ON LEVIZJEHD.KARTLLG=ARTIKUJ.KOD GROUP BY KMAG,ARTIKUJ.KOD
GO
