SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE           VIEW [dbo].[RP_SPECIAL] AS 


SELECT TOP 100 PERCENT 
       KODRP =A.KOD,
       TITULL=A.PERSHKRIM,B.NRRENDOR,KOD=B.PART,PERSHKRIM1=ISNULL(B.TEXT1,''),PERSHKRIM2=ISNULL(B.TEXT2,''),PERSHKRIM3=ISNULL(B.TEXT3,''),
       KLS1PROMPT=ISNULL(B.KLS1PROMPT,''),KLS2PROMPT=ISNULL(B.KLS2PROMPT,''),KLS3PROMPT=ISNULL(B.KLS3PROMPT,''),
       KLS1,KLS2,KLS3,
       GJ    =ISNULL((SELECT SUM(D.DBKRMV) FROM FKSCR D INNER JOIN FK E ON E.NRRENDOR=D.NRD WHERE D.KOD>=C.KUFIP AND D.KOD<=C.KUFIS AND (1=1)),0),
       GJVP  =ISNULL((SELECT SUM(D.DBKRMV) FROM FKSCR D INNER JOIN FK E ON E.NRRENDOR=D.NRD WHERE D.KOD>=C.KUFIP AND D.KOD<=C.KUFIS AND (3=3)),0)
       ,REPL=2

  FROM DBRP..RP_LISTE00 A INNER JOIN DBRP..RP_LISTE01 B ON A.NRRENDOR=B.NRD
                          LEFT  JOIN DBRP..RP_LISTE02 C ON B.NRRENDOR=C.NRD
WHERE (2=2)
ORDER BY B.PART,B.NRRENDOR

GO
