SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO





CREATE    VIEW [dbo].[FDFHLIDHJE03] AS 
 SELECT TOP 100 PERCENT 
            DOKTEST     = 'FD',
            KMAGLNKD    = KMAGLNK1,
            NRDOKLNKD   = NRDOKLNK1,
            NRFRAKSLNKD = NRFRAKSLNK1,
            DATEDOKLNKD = DATEDOKLNK1,
            NRCOUNT     = COUNT(*)
       FROM FDFHLIDHJE01 
   GROUP BY KMAGLNK1,NRDOKLNK1,NRFRAKSLNK1,DATEDOKLNK1
     HAVING SUM(1)<>2

  UNION ALL

 SELECT TOP 100 PERCENT 
            DOKTEST     = 'FH',
            KMAGLNKD    = KMAGLNK2,
            NRDOKLNKD   = NRDOKLNK2,
            NRFRAKSLNKD = NRFRAKSLNK2,
            DATEDOKLNKD = DATEDOKLNK2,
            NRCOUNT     = COUNT(*)
       FROM FDFHLIDHJE01 
   GROUP BY KMAGLNK2,NRDOKLNK2,NRFRAKSLNK2,DATEDOKLNK2
     HAVING SUM(1)<>2

   ORDER BY DOKTEST,KMAGLNKD,NRDOKLNKD,NRFRAKSLNKD,DATEDOKLNKD







GO
