SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO



CREATE  VIEW [dbo].[QDitarNRDFKMD] AS 
  SELECT TOP 100 PERCENT M.NRDFK AS NRDFKMASTER, D.NRDFK AS NRDFKDETAIL
    FROM FH AS D INNER JOIN FF AS M ON  D.NRRENDOR=M.NRRENDDMG
   WHERE (D.DOK_JB=1) AND (D.NRDFK<>0) AND  (M.NRDFK<>0)
   UNION ALL 
  SELECT TOP 100 PERCENT M.NRDFK AS NRDFKMASTER, D.NRDFK AS NRDFKDETAIL
    FROM FD AS D INNER JOIN FJ AS M ON  D.NRRENDOR=M.NRRENDDMG
   WHERE (D.DOK_JB=1) AND (D.NRDFK<>0) AND (M.NRDFK<>0)
ORDER BY NRDFKDETAIL, NRDFKMASTER



GO
