SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO



CREATE                             VIEW [dbo].[VOUCHERAR] AS 

SELECT TOP 100 PERCENT 
       KOD      =CASE WHEN ARTIKUJ.KOD IS NULL THEN FFSCR.LLOGARIPK
                      ELSE CASE WHEN LEFT(SKEMELM.LLOGB,1)<>'8' THEN SKEMELM.LLOGB ELSE SKEMELM.LLOGINV END
                      END,
       PERSHKRIM=CASE WHEN ARTIKUJ.KOD IS NULL THEN FFSCR.PERSHKRIM
                      ELSE SKEMELM.PERSHKRIM
                      END, 
       FFSCR.KOMENT,VLDB=FFSCR.VLPATVSH,VLKR=0,RENDITJE=ARKASCR.NRRENDOR,RENDITJE1='0',ARKA.NRRENDOR,
       ARKA.NUMDOK,ARKA.DATEDOK,MONEDHA.SIMBOL
FROM ARKASCR INNER JOIN ARKA     ON ARKASCR.NRD       =ARKA.NRRENDOR
             INNER JOIN FF       ON ARKASCR.DATEDOKREF=FF.DTDSHOQ AND ARKASCR.NRDOKREF=FF.NRDSHOQ AND ARKASCR.LLOGARIPK=FF.KODFKL
             INNER JOIN FFSCR    ON FFSCR.NRD         =FF.NRRENDOR
             LEFT  JOIN ARTIKUJ  ON FFSCR.KARTLLG     =ARTIKUJ.KOD
             LEFT  JOIN SKEMELM  ON ARTIKUJ.KODLM     =SKEMELM.KOD
             LEFT  JOIN MONEDHA  ON FF.KMON           =MONEDHA.KOD   


UNION ALL
SELECT TOP 100 PERCENT
       KOD      =FF.LLOGTVSH,
       PERSHKRIM=LLOGARI.PERSHKRIM, 
       FFSCR.KOMENT,
       FFSCR.VLTVSH,VLKR=0,ARKASCR.NRRENDOR,'1',ARKA.NRRENDOR,
       ARKA.NUMDOK,ARKA.DATEDOK,MONEDHA.SIMBOL
FROM ARKASCR INNER JOIN ARKA     ON ARKASCR.NRD       =ARKA.NRRENDOR
             INNER JOIN FF       ON ARKASCR.DATEDOKREF=FF.DTDSHOQ AND ARKASCR.NRDOKREF=FF.NRDSHOQ AND ARKASCR.LLOGARIPK=FF.KODFKL
             INNER JOIN FFSCR    ON FFSCR.NRD         =FF.NRRENDOR
             LEFT  JOIN LLOGARI  ON FF.LLOGTVSH       =LLOGARI.KOD
             LEFT  JOIN MONEDHA  ON FF.KMON           =MONEDHA.KOD
        WHERE FFSCR.VLTVSH<>0

UNION ALL
SELECT TOP 100 PERCENT
       KOD      =LLOGARI.KOD,
       PERSHKRIM=LLOGARI.PERSHKRIM, 
       FF.SHENIM1,
       VLDB=0,FF.VLERTOT,ARKASCR.NRRENDOR,'2',ARKA.NRRENDOR,
       ARKA.NUMDOK,ARKA.DATEDOK,MONEDHA.SIMBOL
FROM ARKASCR INNER JOIN ARKA     ON ARKASCR.NRD       =ARKA.NRRENDOR
             INNER JOIN FF       ON ARKASCR.DATEDOKREF=FF.DTDSHOQ AND ARKASCR.NRDOKREF=FF.NRDSHOQ AND ARKASCR.LLOGARIPK=FF.KODFKL
             INNER JOIN FURNITOR ON FURNITOR.KOD      =FF.KODFKL
             LEFT  JOIN LLOGARI  ON FURNITOR.LLOGARI  =LLOGARI.KOD
             LEFT  JOIN MONEDHA  ON FF.KMON           =MONEDHA.KOD

UNION ALL
SELECT TOP 100 PERCENT
       FURNITOR.LLOGARI,ARKASCR.PERSHKRIM,ARKASCR.KOMENT,
       ARKASCR.DB-ARKASCR.KR,0,ARKASCR.NRRENDOR,'3',ARKA.NRRENDOR,
       ARKA.NUMDOK,ARKA.DATEDOK,MONEDHA.SIMBOL
FROM ARKASCR INNER JOIN ARKA     ON ARKASCR.NRD=ARKA.NRRENDOR
             INNER JOIN FF       ON ARKASCR.DATEDOKREF=FF.DTDSHOQ AND ARKASCR.NRDOKREF=FF.NRDSHOQ AND ARKASCR.LLOGARIPK=FF.KODFKL
             INNER JOIN FURNITOR ON ARKASCR.LLOGARIPK=FURNITOR.KOD
             LEFT  JOIN MONEDHA  ON ARKASCR.KMON      =MONEDHA.KOD

UNION ALL
SELECT TOP 100 PERCENT
       ARKA.LLOGARI,LLOGARI.PERSHKRIM,ARKASCR.KOMENT,
       0,ARKASCR.DB-ARKASCR.KR,ARKASCR.NRRENDOR,'4',ARKA.NRRENDOR,
       ARKA.NUMDOK,ARKA.DATEDOK,MONEDHA.SIMBOL
FROM ARKASCR INNER JOIN ARKA    ON ARKASCR.NRD       =ARKA.NRRENDOR
             INNER JOIN FF      ON ARKASCR.DATEDOKREF=FF.DTDSHOQ AND ARKASCR.NRDOKREF=FF.NRDSHOQ AND ARKASCR.LLOGARIPK=FF.KODFKL
             INNER JOIN LLOGARI ON LLOGARI.KOD       =ARKA.LLOGARI  
             LEFT  JOIN MONEDHA ON ARKASCR.KMON      =MONEDHA.KOD

UNION ALL
SELECT TOP 100 PERCENT
       ARKASCR.LLOGARIPK,ARKASCR.PERSHKRIM,ARKASCR.KOMENT,
       CASE WHEN (ARKASCR.DB-ARKASCR.KR)<0 THEN 0 ELSE ARKASCR.DB-ARKASCR.KR END,
       CASE WHEN (ARKASCR.DB-ARKASCR.KR)<0 THEN -(ARKASCR.DB-ARKASCR.KR) ELSE 0 END,
       ARKASCR.NRRENDOR,'5',ARKA.NRRENDOR,
       ARKA.NUMDOK,ARKA.DATEDOK,MONEDHA.SIMBOL
FROM ARKASCR INNER JOIN ARKA    ON ARKASCR.NRD       =ARKA.NRRENDOR
             INNER JOIN LLOGARI ON LLOGARI.KOD       =ARKA.LLOGARI
             LEFT  JOIN MONEDHA ON ARKASCR.KMON      =MONEDHA.KOD   
WHERE ARKASCR.TIPKLL='T' AND ARKASCR.RRAB<>'K'

UNION ALL
SELECT TOP 100 PERCENT
       ARKA.LLOGARI,LLOGARI.PERSHKRIM,ARKASCR.KOMENT,

       CASE WHEN (ARKASCR.KR-ARKASCR.DB)<0 THEN 0 ELSE ARKASCR.KR-ARKASCR.DB END,
       CASE WHEN (ARKASCR.KR-ARKASCR.DB)<0 THEN -(ARKASCR.KR-ARKASCR.DB) ELSE 0 END,


       ARKASCR.NRRENDOR,'6',ARKA.NRRENDOR,
       ARKA.NUMDOK,ARKA.DATEDOK,MONEDHA.SIMBOL
FROM ARKASCR INNER JOIN ARKA    ON ARKASCR.NRD       =ARKA.NRRENDOR
             INNER JOIN LLOGARI ON LLOGARI.KOD       =ARKA.LLOGARI
             LEFT  JOIN MONEDHA ON ARKASCR.KMON      =MONEDHA.KOD  
WHERE ARKASCR.TIPKLL='T' AND ARKASCR.RRAB<>'K'









GO
