SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO




CREATE         VIEW [dbo].[S_LIBSHHC] AS 

SELECT FJ.NIPT, FJ.KODFISKAL,
       SHENIM1=CASE WHEN (KLIENT.EMERTIMLB IS NULL) OR (KLIENT.EMERTIMLB='')
                    THEN FJ.SHENIM1
                    ELSE KLIENT.EMERTIMLB END,
       FJ.NRSERIAL, FJ.RRETHI,FJ.DATEDOK,MUAJ=MONTH(DATEDOK),VIT=YEAR(DATEDOK),
       PERIUDHE=CAST(MONTH(DATEDOK) AS VARCHAR)+CAST(YEAR(DATEDOK) AS VARCHAR),
       FJ.NRRENDOR,TIPDOK.PERSHKRIM,FJ.KLASIFIKIM,
       H_TOTPATVSHVAL=CASE WHEN (VLTVSH=0) AND (ISDG=0) THEN VLERTOT ELSE 0 END,
       I_VLTOTEXPVAL =CASE WHEN ISDG =1   THEN VLERTOT  ELSE 0 END,
       J_FATMETVSHVAL=CASE WHEN VLTVSH<>0 THEN VLPATVSH-VLERZBR ELSE 0 END,
       K_VLTVSHVAL   =CASE WHEN VLTVSH<>0 THEN VLTVSH   ELSE 0 END,
       H_TOTPATVSH   =ROUND(((CASE WHEN (VLTVSH=0) AND (ISDG=0) THEN VLERTOT ELSE 0 END)*KURS2)/KURS1,2),
       I_VLTOTEXP    =ROUND(((CASE WHEN ISDG =1   THEN VLERTOT  ELSE 0 END)*KURS2)/KURS1,2),
       J_FATMETVSH   =ROUND(((CASE WHEN VLTVSH<>0 THEN VLPATVSH-VLERZBR ELSE 0 END)*KURS2)/KURS1,2),
       K_VLTVSH      =ROUND(((CASE WHEN VLTVSH<>0 THEN VLTVSH   ELSE 0 END)*KURS2)/KURS1,2),
       G_TOTAL       =ROUND(((CASE WHEN (VLTVSH=0) AND (ISDG=0) THEN VLERTOT ELSE 0 END)*KURS2)/KURS1,2)+
                      ROUND(((CASE WHEN ISDG=1    THEN VLERTOT  ELSE 0 END)*KURS2)/KURS1,2)+
                      ROUND(((CASE WHEN VLTVSH<>0 THEN VLPATVSH-VLERZBR ELSE 0 END)*KURS2)/KURS1,2)+
		      ROUND(((CASE WHEN VLTVSH<>0 THEN VLTVSH   ELSE 0 END)*KURS2)/KURS1,2),
       LIBERNR       =CASE ISDG WHEN 1 THEN NRDOKDG ELSE NRDSHOQ END,
       LIBERDT       =CASE ISDG WHEN 1 THEN DTDOKDG ELSE DTDSHOQ END,
       NIPTND        =(SELECT MAX(NIPT) FROM CONFND),
       PERSHKRIMND   =(SELECT MAX(PERSHKRIM) FROM CONFND),
       TIPDOK        =TIPDOK.TIPDOK,
       ISDOKSHOQ     =FJ.ISDOKSHOQ
    FROM FJ LEFT JOIN KLIENT ON FJ.KODFKL=KLIENT.KOD
            LEFT JOIN TIPDOK ON CAST(MONTH(FJ.DATEDOK) AS VARCHAR)=TIPDOK.KOD
UNION ALL
SELECT NIPT=KLIENT.NIPT,KODFISKAL='',
       SHENIM1=QHCOM.PERSHKRIM,
       NRSERIAL='0'+NRFAT,RRETHI=VENDNDODHJE.PERSHKRIM,QHCOM.DATEDOK,MUAJ=MONTH(QHCOM.DATEDOK),VIT=YEAR(QHCOM.DATEDOK),
       PERIUDHE=CAST(MONTH(QHCOM.DATEDOK) AS VARCHAR)+CAST(YEAR(QHCOM.DATEDOK) AS VARCHAR),
       NRRENDOR=0,PERSHKRIM='',KLASIFIKIM='',
       
       H_TOTPATVSHVAL=0,
       I_VLTOTEXPVAL =0,
       J_FATMETVSHVAL=0,
       K_VLTVSHVAL   =0,
       H_TOTPATVSH   =0,
       I_VLTOTEXP    =0,
       J_FATMETVSH   =ROUND(QHCOM.VLEFTAMV/1.2,2),
       K_VLTVSH      =ROUND(QHCOM.VLEFTAMV-ROUND(QHCOM.VLEFTAMV/1.2,2),2),
       G_TOTAL       =QHCOM.VLEFTAMV,

       LIBERNR       =''+RIGHT(QHCOM.KOD,5)+RIGHT('00'+CAST(MONTH(DATEDOK) AS VARCHAR),2),
       LIBERDT       =QHCOM.DATEDOK,
       NIPTND        =(SELECT MAX(NIPT) FROM CONFND),
       PERSHKRIMND   =(SELECT MAX(PERSHKRIM) FROM CONFND),
       TIPDOK        ='Z',
       ISDOKSHOQ     =0       
FROM QHCOM INNER JOIN KLIENT      ON QHCOM.KOD      =KLIENT.KOD
           LEFT  JOIN VENDNDODHJE ON VENDNDODHJE.KOD=KLIENT.VENDNDODHJE
WHERE OPERLLOJ='DF'







GO
