SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO







CREATE      VIEW [dbo].[FJSHTESE01T] AS 
SELECT TOP 100 PERCENT DATEDOK, NRDOK,   DTORIGJ=DATEDOK, NRORIGJ=NRDOK,1 AS NRTIMEFJ,LLOJDOK,KMON,VLERTOT,KODFKL,SHENIM1,KMAG
FROM FJ 
WHERE (LLOJDOK='F')

UNION ALL 
SELECT TOP 100 PERCENT DTFATST, NRFATST, DATEDOK, NRDOK,  -1,LLOJDOK,KMON,VLERTOT,KODFKL,SHENIM1,KMAG
FROM FJ 
WHERE (LLOJDOK='H')

UNION ALL 
SELECT TOP 100 PERCENT DATEDOK, NRDOK,   DATEDOK, NRDOK,   1 AS NRTIMEFJ,LLOJDOK,KMON,VLERTOT,KODFKL,SHENIM1,KMAG
FROM FJ 
WHERE (LLOJDOK='G')

UNION ALL 
SELECT TOP 100 PERCENT DTFATST, NRFATST, DATEDOK, NRDOK,  -1,LLOJDOK,KMON,VLERTOT,KODFKL,SHENIM1,KMAG
FROM FJ 
WHERE (LLOJDOK='I')

UNION ALL 
SELECT TOP 100 PERCENT DTFATST, NRFATST, DATEDOK, NRDOK,  -1,LLOJDOK,KMON,VLERTOT,KODFKL,SHENIM1,KMAG
FROM FJ 
WHERE (LLOJDOK='K')

ORDER BY DATEDOK, NRDOK






GO
