SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO















CREATE     VIEW [dbo].[S_LIBBLAN] AS 

SELECT NIPT=MAX(FF.NIPT),KODFISKAL=MAX(FF.KODFISKAL),SHENIM1=MAX(FF.SHENIM1),KODFKL=MAX(FF.KODFKL),KMON=MAX(FF.KMON),
       NRSERIAL=MAX(FF.NRSERIAL),RRETHI=MAX(FF.RRETHI),KMAG=MAX(FF.KMAG),DATEDOK=MAX(FF.DATEDOK),
       FF.NRRENDOR,KLASIFIKIM=MAX(KLASIFIKIM),ISDG=MAX(CASE WHEN FF.ISDG=1 THEN 1 ELSE 0 END),KURS1=MAX(KURS1),KURS2=MAX(KURS2),
       NRDOKDG=MAX(FF.NRDOKDG),DTDOKDG=MAX(FF.DTDOKDG),DTDSHOQ=MAX(FF.DTDSHOQ),NRDSHOQ=MAX(FF.NRDSHOQ),KODDG=MAX(KODDG),
       VLPATVSH=SUM(FFSCR.VLPATVSH)-MAX(VLERZBR),VLTVSH=MAX(FF.VLTVSH),VLERZBR=0,
       VLERTOT =SUM(FFSCR.VLPATVSH)-MAX(VLERZBR)+MAX(FF.VLTVSH)
FROM FF INNER JOIN FFSCR ON FF.NRRENDOR=FFSCR.NRD
WHERE FFSCR.VLTVSH<>''
GROUP BY FF.NRRENDOR
UNION ALL
SELECT NIPT=MAX(FF.NIPT),KODFISKAL=MAX(FF.KODFISKAL),SHENIM1=MAX(FF.SHENIM1),KODFKL=MAX(FF.KODFKL),KMON=MAX(FF.KMON),
       NRSERIAL=MAX(FF.NRSERIAL),RRETHI=MAX(FF.RRETHI),KMAG=MAX(FF.KMAG),DATEDOK=MAX(FF.DATEDOK),
       FF.NRRENDOR,KLASIFIKIM=MAX(KLASIFIKIM),ISDG=MAX(CASE WHEN FF.ISDG=1 THEN 1 ELSE 0 END),KURS1=MAX(KURS1),KURS2=MAX(KURS2),
       NRDOKDG=MAX(FF.NRDOKDG),DTDOKDG=MAX(FF.DTDOKDG),DTDSHOQ=MAX(FF.DTDSHOQ),NRDSHOQ=MAX(FF.NRDSHOQ),KODDG=MAX(KODDG),
       VLPATVSH=SUM(FFSCR.VLPATVSH),VLTVSH=SUM(FFSCR.VLTVSH),VLERZBR=0,
       VLERTOT=SUM(FFSCR.VLERABS)
FROM FF INNER JOIN FFSCR ON FF.NRRENDOR=FFSCR.NRD
WHERE FFSCR.VLTVSH=0
GROUP BY FF.NRRENDOR








GO
