SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE       VIEW [dbo].[FU_AfatFature] AS
   SELECT DATEDOK,
          NRDOK,
          A.KOD,
          KODFKL,
          SHENIM1,
          A.KMON,
          A.NIPT,
          NRSERIAL,
          NRFATURE   = NRDSHOQ,
          DATEFATURE = ISNULL(DTDSHOQ,DATEDOK),
          AFATPAGESE = ISNULL(DTAF,ISNULL(B.AFAT,0)),
          DITEPAGESE = DATEADD(DAY,ISNULL(DTAF,ISNULL(B.AFAT,0)),ISNULL(DTDSHOQ,DATEDOK)),
          DITEKALUAR = DATEDIFF(DAY,DATEADD(DAY,ISNULL(DTAF,ISNULL(B.AFAT,0)),ISNULL(DTDSHOQ,DATEDOK)),GETDATE()),
          VLERTOT,
          VLERTOTMB = VLERTOT*(CASE WHEN KURS2*KURS1>0 THEN KURS2/KURS1 ELSE 1 END),
          TIPDOK    = 'FF',
          A.NRRENDOR
     FROM FF A INNER JOIN FURNITOR B ON A.KODFKL=B.KOD
UNION ALL
   SELECT VS.DATEDOK,
          VS.NRDOK,
          VSSCR.KOD,
          VSSCR.LLOGARIPK,
          VSSCR.PERSHKRIM,
          VSSCR.KMON,
          NIPT = '',
          '0',
          NRFATURE   = ISNULL(NRDOKREF,0),
          DATEFATURE = ISNULL(DATEDOKREF,VS.DATEDOK),
          AFATPAGESE = ISNULL(OPERNR,0),
          DITEPAGESE = ISNULL(DATEDOKREF,VS.DATEDOK)+ISNULL(OPERNR,0),
          DITEKALUAR = DATEDIFF(DAY,ISNULL(DATEDOKREF,VS.DATEDOK)+ISNULL(OPERNR,0),GETDATE()),
          VLERTOT    = DB-KR,
          VLERTOTMB  = DBKRMV,
          TIPDOK     = 'VS',
          VS.NRRENDOR
     FROM VSSCR INNER JOIN VS ON VSSCR.NRD=VS.NRRENDOR
    WHERE VSSCR.TIPKLL='F'
 --ORDER BY DITEPAGESE,DATEFATURE,NRFATURE
GO
