SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[LLOGNRTIMEKR]
AS
SELECT TOP 100 PERCENT FKSCR.KOD, FK.DATEDOK, FKSCR.NRD, FKSCR.NRRENDOR, (SELECT SUM(1) 
FROM FK AS FK1 LEFT JOIN FKSCR AS FKSCR1 ON FK1.NRRENDOR=FKSCR1.NRD 
WHERE   (FKSCR1.TREGDK='K') AND (FKSCR1.KOD=FKSCR.KOD) AND 
               ((FK1.DATEDOK<FK.DATEDOK) OR 
               ((FK1.DATEDOK=FK.DATEDOK) AND (FKSCR1.NRD<FKSCR.NRD)) OR
               ((FK1.DATEDOK=FK.DATEDOK) AND (FKSCR1.NRD=FKSCR.NRD) AND (FKSCR1.NRRENDOR<FKSCR.NRRENDOR)))) AS NRTKR, 
               NRTIMEKR=CASE
                 WHEN (SELECT SUM(1) 
                       FROM FK AS FK1 LEFT JOIN FKSCR AS FKSCR1 ON FK1.NRRENDOR=FKSCR1.NRD 
                       WHERE   (FKSCR1.TREGDK='K') AND (FKSCR1.KOD=FKSCR.KOD) AND 
                               ((FK1.DATEDOK<FK.DATEDOK) OR 
                               ((FK1.DATEDOK=FK.DATEDOK) AND (FKSCR1.NRD<FKSCR.NRD)) OR
                               ((FK1.DATEDOK=FK.DATEDOK) AND (FKSCR1.NRD=FKSCR.NRD) AND (FKSCR1.NRRENDOR<FKSCR.NRRENDOR)))) IS NULL THEN 0
                 ELSE (SELECT SUM(1) 
                       FROM FK AS FK1 LEFT JOIN FKSCR AS FKSCR1 ON FK1.NRRENDOR=FKSCR1.NRD 
                       WHERE   (FKSCR1.TREGDK='K') AND (FKSCR1.KOD=FKSCR.KOD) AND 
                               ((FK1.DATEDOK<FK.DATEDOK) OR 
                               ((FK1.DATEDOK=FK.DATEDOK) AND (FKSCR1.NRD<FKSCR.NRD)) OR
                               ((FK1.DATEDOK=FK.DATEDOK) AND (FKSCR1.NRD=FKSCR.NRD) AND (FKSCR1.NRRENDOR<FKSCR.NRRENDOR))))
               END+CASE
                   WHEN TREGDK='K' THEN 1
                   ELSE 0
               END
FROM FK LEFT JOIN FKSCR ON FK.NRRENDOR = FKSCR.NRD
WHERE TREGDK='K'
ORDER BY FKSCR.KOD, FK.DATEDOK, FKSCR.NRD, FKSCR.NRRENDOR



GO
