SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO














CREATE View [dbo].[DRHReference] As
--SELECT * FROM DRHUSER
--SELECT * FROM DRHUSERKUFI WHERE MODUL='S'
--
-- Dokumenta
--   Select A.*,
--          KufiP=Cast(Convert(VarChar(10),GetDate()-5,101) As DateTime),
--          KufiS=Cast(Convert(Varchar(10),GetDate(),101) As DateTime)
--    From FJ A Inner Join DRHReference  B On A.KODFKL=B.KOD
--   Where B.Modul='S' AND B.KodUs='USERONE'
--Order By B.KodUs,B.Modul,B.TipDok

-- Referenca
--   Select A.*,
--    From KLIENT A Inner Join DRHReference  B On A.KOD=B.KOD
--   Where B.Modul='S' AND B.KodUs='USERONE'
--Order By B.KodUs,B.Modul,B.TipDok


             -- Klient
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='KLIENT'  
        FROM DRH..USERS A, KLIENT B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2)
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='KLIENT' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 --CASE WHEN ISNULL(D.NONOTACTIVKLI,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END
              
              
   UNION ALL -- Furnitor
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='FURNITOR'  
        FROM DRH..USERS A, FURNITOR B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2)
             -- AND 
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='FURNITOR' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVFUR,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END
             
              
   UNION ALL -- Artikuj
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='ARTIKUJ' 
        FROM DRH..USERS A, ARTIKUJ B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='ARTIKUJ' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVART,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END
              
   UNION ALL -- Llogari
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='LLOGARI' 
        FROM DRH..USERS A, LLOGARI B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='LLOGARI' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))

   UNION ALL -- Arka
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='ARKAT' 
        FROM DRH..USERS A, ARKAT B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='ARKAT' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVARK,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END
              
              
   UNION ALL -- Banka
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='BANKAT' 
        FROM DRH..USERS A, BANKAT B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2)
             -- AND
               (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='BANKAT' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVBAN,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END
              
   UNION ALL -- Magazina
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='MAGAZINA' 
        FROM DRH..USERS A, MAGAZINA B, CONFND D
       WHERE (ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2)
              AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='MAGAZINA' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVMAG,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END

   UNION ALL -- Departament
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='DEPARTAMENT' 
        FROM DRH..USERS A, DEPARTAMENT B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='DEPARTAMENT' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVDEP,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END

   UNION ALL -- Liste
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='LISTE' 
        FROM DRH..USERS A, LISTE B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
               (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='LISTE' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVLIS,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END

   UNION ALL -- Tatim
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='TATIM' 
        FROM DRH..USERS A, TATIM B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='TATIM' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVTAT,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END
              
   UNION ALL -- KlasaTatim
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='KLASATATIM' 
        FROM DRH..USERS A, KLASATATIM B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='KLASATATIM' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVKLT,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END

   UNION ALL -- Zbritje
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='ZBRITJE' 
        FROM DRH..USERS A, ZBRITJE B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='ZBRITJE' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVZBR,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END

   UNION ALL -- Sherbim
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='SHERBIM' 
        FROM DRH..USERS A, SHERBIM B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='SHERBIM' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVSHR,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END

   UNION ALL -- Monedha
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='MONEDHA'  
        FROM DRH..USERS A, MONEDHA B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='MONEDHA' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVMON,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END             

   UNION ALL -- Njesi
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='NJESI' 
        FROM DRH..USERS A, NJESI B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='NJESI' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVNJS,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END             

   UNION ALL -- Agjent Shitje
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='AGJENTSHITJE' 
        FROM DRH..USERS A, AGJENTSHITJE B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='AGJENTSHITJE' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVAGJ,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END

   UNION ALL -- Agjent Blerje
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='AGJENTBLERJE' 
        FROM DRH..USERS A, AGJENTBLERJE B--, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='AGJENTBLERJE' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVAGJ,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END

   UNION ALL -- Vend Ndodhje
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='VENDNDODHJE' 
        FROM DRH..USERS A, VENDNDODHJE B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='VENDNDODHJE' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVNVD,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END

   UNION ALL -- Rajon
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='RAJON' 
        FROM DRH..USERS A, RAJON B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='RAJON' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVRAJ,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END

   UNION ALL -- Kategori
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='KATEGORI' 
        FROM DRH..USERS A, KATEGORI B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='KATEGORI' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVKTG,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END

   UNION ALL -- Transport
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='TRANSPORT' 
        FROM DRH..USERS A, TRANSPORT B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='TRANSPORT' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVTRA,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END

   UNION ALL -- Kase
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='KASE' 
        FROM DRH..USERS A, KASE B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='KASE' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVKAS,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END

   UNION ALL -- Personel
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='PERSONEL' 
        FROM DRH..USERS A, PERSONEL B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='PERSONEL' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVPER,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END

   UNION ALL -- Promoc
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='PROMOC' 
        FROM DRH..USERS A, PROMOC B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='PROMOC' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVPRC,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END


   UNION ALL -- SkemeLM
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='SKEMELM'  
        FROM DRH..USERS A, SKEMELM B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='SKEMELM'    AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVSLM,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END

   UNION ALL -- TipNjesi
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='TIPNJESI' 
        FROM DRH..USERS A, TIPNJESI B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='TIPNJESI'   AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVKLT,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END

   UNION ALL -- AQKartela
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='AQKARTELA'  
        FROM DRH..USERS A, AQKARTELA B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='AQKARTELA'  AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVAQA,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END
           
   UNION ALL -- AQKategori
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='AQKATEGORI'  
        FROM DRH..USERS A, AQKATEGORI B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='AQKATEGORI' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVAQK,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END
                                         
   UNION ALL -- AQGrup
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='AQGRUP'  
        FROM DRH..USERS A, AQGRUP B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='AQGRUP'     AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVAQG,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END
           
   UNION ALL -- AQSkemeLM
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='AQSKEMELM'  
        FROM DRH..USERS A, AQSKEMELM B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='AQSKEMELM'  AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVAQG,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END
           
   UNION ALL -- ArtikujKtg
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='ARTIKUJKTG'  
        FROM DRH..USERS A, ARTIKUJKTG B, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='ARTIKUJKTG'  AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVAQG,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END
           
   UNION ALL -- FisTcr
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='FISTCR' 
        FROM DRH..USERS A, FISTCR B--, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='FISTCR' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVTAT,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END

   UNION ALL -- FisProces
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='FISPROCES' 
        FROM DRH..USERS A, FISPROCES B--, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='FISPROCES' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVTAT,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END
              
   UNION ALL -- FisTipdokFt
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='FISTIPDOKFT' 
        FROM DRH..USERS A, FISTIPDOKFT B--, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='FISTIPDOKFT' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVTAT,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END
              
   UNION ALL -- FisOperator
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='FISOPERATOR' 
        FROM DRH..USERS A, FISOPERATOR B--, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='FISOPERATOR' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVTAT,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END

   UNION ALL -- FisMenPagese
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='FISMENPAGESE' 
        FROM DRH..USERS A, FISMENPAGESE B--, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='FISMENPAGESE' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVTAT,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END


   UNION ALL -- Countries
      SELECT KODUS=A.USERN, B.KOD, REFERENCE='COUNTRIES' 
        FROM DRH..USERS A, COUNTRIES B--, CONFND D
       WHERE --(ISNULL(B.NOTACTIV,0)<>1 OR D.ListRefNotActiv<>2) 
             -- AND
             (NOT EXISTS (SELECT 1 
                            FROM DRHUSERKUFI C
                           WHERE C.KODUS=A.USERN AND REFERENCE='COUNTRIES' AND (B.KOD>=C.KUFIP AND B.KOD<=C.KUFIS )))
           -- AND ISNULL(B.NOTACTIV,0) = 0 -- CASE WHEN ISNULL(D.NONOTACTIVTAT,0)=0 THEN ISNULL(B.NOTACTIV,0) ELSE 0 END

/*
*/












GO
