SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO




CREATE VIEW [dbo].[QFKZGJBL] 

AS 

      SELECT TOP 100 PERCENT 
             NRDFK, 
             NRDSHOQ,               
             DTDSHOQ,   
             KLASIFIKIM = CAST(ISNULL(KLASIFIKIM,'') AS VARCHAR(25)) 
        FROM FF
       WHERE ISNULL(NRDFK,0)<>0

   UNION ALL

      SELECT TOP 100 PERCENT 
             NRDFK, 
             NRDSHOQ    = MAX(NRDOKREF), 
             DTDSHOQ    = MAX(DATEDOKREF),
             KLASIFIKIM = MAX(CAST(ISNULL(OPERNR,'') AS VARCHAR(25)))
        FROM ARKA INNER JOIN ARKASCR ON ARKA.NRRENDOR=ARKASCR.NRD
       WHERE ISNULL(NRDFK,0)<>0 AND TIPREF='FF'
    GROUP BY NRDFK

   UNION ALL

      SELECT TOP 100 PERCENT 
             NRDFK,
             NRDSHOQ    = MAX(NRDOKREF),
             DTDSHOQ    = MAX(DATEDOKREF),
             KLASIFIKIM = MAX(CAST(ISNULL(OPERNR,'') AS VARCHAR(25)))
        FROM BANKA INNER JOIN BANKASCR ON BANKA.NRRENDOR=BANKASCR.NRD
       WHERE ISNULL(NRDFK,0)<>0 AND TIPREF='FF' 
    GROUP BY NRDFK

   UNION ALL

      SELECT TOP 100 PERCENT 
             NRDFK,
             NRDSHOQ    = MAX(NRDOKREF),
             DTDSHOQ    = MAX(DATEDOKREF),
             KLASIFIKIM = MAX(CAST(ISNULL(OPERNR,'') AS VARCHAR(25)))
        FROM VS INNER JOIN VSSCR ON VS.NRRENDOR=VSSCR.NRD
       WHERE ISNULL(NRDFK,0)<>0 AND TIPREF='FF' 
    GROUP BY NRDFK

GO
