SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO



CREATE    VIEW [dbo].[QFKSCRDEPLIST] AS 

SELECT FKSCR.NRRENDOR,
       DEP =ISNULL(LEFT(RIGHT(FKSCR.KOD,LEN(FKSCR.KOD)-CHARINDEX('.',FKSCR.KOD)),CHARINDEX('.',RIGHT(FKSCR.KOD,LEN(FKSCR.KOD)-CHARINDEX('.',FKSCR.KOD)))-1),''),
       LIST=ISNULL(LEFT(RIGHT(RIGHT(LTRIM(RTRIM(FKSCR.KOD)),LEN(LTRIM(RTRIM(FKSCR.KOD)))-CHARINDEX('.',LTRIM(RTRIM(FKSCR.KOD)))),LEN(RIGHT(LTRIM(RTRIM(FKSCR.KOD)),LEN(LTRIM(RTRIM(FKSCR.KOD)))-CHARINDEX('.',LTRIM(RTRIM(FKSCR.KOD)))))-CHARINDEX('.',RIGHT(LTRIM(RTRIM(FKSCR.KOD)),LEN(LTRIM(RTRIM(FKSCR.KOD)))-CHARINDEX('.',LTRIM(RTRIM(FKSCR.KOD)))))),CHARINDEX('.',RIGHT(RIGHT(LTRIM(RTRIM(FKSCR.KOD)),LEN(LTRIM(RTRIM(FKSCR.KOD)))-CHARINDEX('.',LTRIM(RTRIM(FKSCR.KOD)))),LEN(RIGHT(LTRIM(RTRIM(FKSCR.KOD)),LEN(LTRIM(RTRIM(FKSCR.KOD)))-CHARINDEX('.',LTRIM(RTRIM(FKSCR.KOD)))))-CHARINDEX('.',RIGHT(LTRIM(RTRIM(FKSCR.KOD)),LEN(LTRIM(RTRIM(FKSCR.KOD)))-CHARINDEX('.',LTRIM(RTRIM(FKSCR.KOD)))))))-1),'')
FROM FKSCR


GO
