SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE      VIEW [dbo].[S_FJ_UNIKE]   AS  SELECT NRDSHOQ,DTDSHOQ,        KLASIFIKIM =ISNULL(MIN(KLASIFIKIM),''),        KLASIFIKIM1=ISNULL(MIN(KLASIFIKIM1),''),        KMAG       =ISNULL(MAX(KMAG),'')  FROM FJ  GROUP BY NRDSHOQ,DTDSHOQ 
GO
