SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[T_DOKDIT_BA] AS 
SELECT TOP 100 PERCENT NRRENDOR,NRDITAR,'B' AS TIPD
  FROM BANKA
 UNION ALL 
SELECT TOP 100 PERCENT VSSCR.NRRENDOR,NRDITAR,'E' AS TIPD
  FROM VS INNER JOIN VSSCR ON VS.NRRENDOR=VSSCR.NRD
 WHERE TIPKLL='B'
ORDER BY NRDITAR


GO
