SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO









CREATE                            VIEW [dbo].[VOUCHERBA] AS 

SELECT TOP 100 PERCENT 
       KOD      =CASE WHEN ARTIKUJ.KOD IS NULL THEN FFSCR.LLOGARIPK
                      ELSE CASE WHEN LEFT(SKEMELM.LLOGB,1)<>'8' THEN SKEMELM.LLOGB ELSE SKEMELM.LLOGINV END
                      END,
       PERSHKRIM=CASE WHEN ARTIKUJ.KOD IS NULL THEN FFSCR.PERSHKRIM
                      ELSE SKEMELM.PERSHKRIM
                      END, 
       FFSCR.KOMENT,VLDB=FFSCR.VLPATVSH,VLKR=0,RENDITJE=BANKASCR.NRRENDOR,RENDITJE1='0',BANKA.NRRENDOR,
       BANKA.NUMDOK,BANKA.DATEDOK,MONEDHA.SIMBOL
FROM BANKASCR INNER JOIN BANKA    ON BANKASCR.NRD       =BANKA.NRRENDOR
              INNER JOIN FF       ON BANKASCR.DATEDOKREF=FF.DTDSHOQ AND BANKASCR.NRDOKREF=FF.NRDSHOQ AND BANKASCR.LLOGARIPK=FF.KODFKL
              INNER JOIN FFSCR    ON FFSCR.NRD          =FF.NRRENDOR
              LEFT  JOIN ARTIKUJ  ON FFSCR.KARTLLG      =ARTIKUJ.KOD
              LEFT  JOIN SKEMELM  ON ARTIKUJ.KODLM      =SKEMELM.KOD  
              LEFT  JOIN MONEDHA  ON FF.KMON            =MONEDHA.KOD

UNION ALL
SELECT TOP 100 PERCENT
       KOD      =FF.LLOGTVSH,
       PERSHKRIM=LLOGARI.PERSHKRIM, 
       FFSCR.KOMENT,
       FFSCR.VLTVSH,VLKR=0,BANKASCR.NRRENDOR,'1',BANKA.NRRENDOR,
       BANKA.NUMDOK,BANKA.DATEDOK,MONEDHA.SIMBOL
FROM BANKASCR INNER JOIN BANKA    ON BANKASCR.NRD       =BANKA.NRRENDOR
              INNER JOIN FF       ON BANKASCR.DATEDOKREF=FF.DTDSHOQ AND BANKASCR.NRDOKREF=FF.NRDSHOQ AND BANKASCR.LLOGARIPK=FF.KODFKL
              INNER JOIN FFSCR    ON FFSCR.NRD          =FF.NRRENDOR
              LEFT  JOIN LLOGARI  ON FF.LLOGTVSH        =LLOGARI.KOD
              LEFT  JOIN MONEDHA  ON FF.KMON            =MONEDHA.KOD
       WHERE FFSCR.VLTVSH<>0
       
UNION ALL
SELECT TOP 100 PERCENT
       KOD      =LLOGARI.KOD,
       PERSHKRIM=LLOGARI.PERSHKRIM, 
       FF.SHENIM1,
       VLDB=0,FF.VLERTOT,BANKASCR.NRRENDOR,'2',BANKA.NRRENDOR,
       BANKA.NUMDOK,BANKA.DATEDOK,MONEDHA.SIMBOL
FROM BANKASCR INNER JOIN BANKA    ON BANKASCR.NRD       =BANKA.NRRENDOR
              INNER JOIN FF       ON BANKASCR.DATEDOKREF=FF.DTDSHOQ AND BANKASCR.NRDOKREF=FF.NRDSHOQ AND BANKASCR.LLOGARIPK=FF.KODFKL
              INNER JOIN FURNITOR ON FURNITOR.KOD       =FF.KODFKL
              LEFT  JOIN LLOGARI  ON FURNITOR.LLOGARI   =LLOGARI.KOD
              LEFT  JOIN MONEDHA  ON FF.KMON            =MONEDHA.KOD
UNION ALL
SELECT TOP 100 PERCENT
       FURNITOR.LLOGARI,BANKASCR.PERSHKRIM,BANKASCR.KOMENT,
       BANKASCR.DB-BANKASCR.KR,0,BANKASCR.NRRENDOR,'3',BANKA.NRRENDOR,
       BANKA.NUMDOK,BANKA.DATEDOK,MONEDHA.SIMBOL
FROM BANKASCR INNER JOIN BANKA    ON BANKASCR.NRD       =BANKA.NRRENDOR
              INNER JOIN FF       ON BANKASCR.DATEDOKREF=FF.DTDSHOQ AND BANKASCR.NRDOKREF=FF.NRDSHOQ AND BANKASCR.LLOGARIPK=FF.KODFKL
              --INNER JOIN FFSCR    ON FFSCR.NRD          =FF.NRRENDOR
              INNER JOIN FURNITOR ON BANKASCR.LLOGARIPK =FURNITOR.KOD
              LEFT  JOIN MONEDHA  ON BANKASCR.KMON      =MONEDHA.KOD

UNION ALL
SELECT TOP 100 PERCENT
       BANKA.LLOGARI,LLOGARI.PERSHKRIM,BANKASCR.KOMENT,
       0,BANKASCR.DB-BANKASCR.KR,BANKASCR.NRRENDOR,'4',BANKA.NRRENDOR,
       BANKA.NUMDOK,BANKA.DATEDOK,MONEDHA.SIMBOL
FROM BANKASCR INNER JOIN BANKA    ON BANKASCR.NRD       =BANKA.NRRENDOR
              INNER JOIN FF       ON BANKASCR.DATEDOKREF=FF.DTDSHOQ AND BANKASCR.NRDOKREF=FF.NRDSHOQ AND BANKASCR.LLOGARIPK=FF.KODFKL
              --INNER JOIN FFSCR    ON FFSCR.NRD          =FF.NRRENDOR
              INNER JOIN LLOGARI  ON LLOGARI.KOD        =BANKA.LLOGARI  
              LEFT  JOIN MONEDHA  ON BANKASCR.KMON      =MONEDHA.KOD

UNION ALL
SELECT TOP 100 PERCENT
       BANKASCR.LLOGARIPK,BANKASCR.PERSHKRIM,BANKASCR.KOMENT,
       CASE WHEN (BANKASCR.DB-BANKASCR.KR)<0 THEN 0 ELSE BANKASCR.DB-BANKASCR.KR END,
       CASE WHEN (BANKASCR.DB-BANKASCR.KR)<0 THEN -(BANKASCR.DB-BANKASCR.KR) ELSE 0 END,
       BANKASCR.NRRENDOR,'5',BANKA.NRRENDOR,
       BANKA.NUMDOK,BANKA.DATEDOK,MONEDHA.SIMBOL
FROM BANKASCR INNER JOIN BANKA    ON BANKASCR.NRD       =BANKA.NRRENDOR
              INNER JOIN LLOGARI  ON LLOGARI.KOD        =BANKA.LLOGARI  
              LEFT  JOIN MONEDHA  ON BANKASCR.KMON      =MONEDHA.KOD
WHERE BANKASCR.TIPKLL='T' AND BANKASCR.RRAB<>'K'

UNION ALL
SELECT TOP 100 PERCENT
       BANKA.LLOGARI,LLOGARI.PERSHKRIM,BANKASCR.KOMENT,
       CASE WHEN (BANKASCR.KR-BANKASCR.DB)<0 THEN 0 ELSE BANKASCR.KR-BANKASCR.DB END,
       CASE WHEN (BANKASCR.KR-BANKASCR.DB)<0 THEN -(BANKASCR.KR-BANKASCR.DB) ELSE 0 END,
       BANKASCR.NRRENDOR,'6',BANKA.NRRENDOR,
       BANKA.NUMDOK,BANKA.DATEDOK,MONEDHA.SIMBOL
FROM BANKASCR INNER JOIN BANKA    ON BANKASCR.NRD      =BANKA.NRRENDOR
              INNER JOIN LLOGARI  ON LLOGARI.KOD       =BANKA.LLOGARI
              LEFT  JOIN MONEDHA  ON BANKASCR.KMON      =MONEDHA.KOD
WHERE BANKASCR.TIPKLL='T' AND BANKASCR.RRAB<>'K'








GO
