SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE                      VIEW [dbo].[QHCOM] AS 

SELECT TOP 100 PERCENT
       KOD=VSSCR.KODAF,PERSHKRIM=KLIENT.PERSHKRIM,TEL1=KLIENT.TELEFON1,TEL2=KLIENT.TELEFON2,KOMENT=VSSCR.KOMENT,KMON=VSSCR.KMON,KURS1=VSSCR.KURS1,KURS2=VSSCR.KURS2,
       TIPDOK=ISNULL(VSSCR.TIPREF,''),NRDOK=VS.NRDOK,FRAKSDOK=0,DATEDOK=VS.DATEDOK,VLEFTA=(VSSCR.DB+VSSCR.KR),
       VLEFTAMV=ABS(VSSCR.DBKRMV),TREGDK=VSSCR.TREGDK,TIPFAT=ISNULL(VSSCR.TIPREF,''),NRFAT=VSSCR.OPERNRFAT,DTFAT=VSSCR.OPERDT,
       KODMASTER=VSSCR.KODAF,OPERLLOJ=ISNULL(OPERLLOJ,''),OPERAPL,OPERORD,A.NRORD,NRRENDOR=VSSCR.NRDITAR,
       GRUPREF=KLIENT.KOD+LTRIM(RTRIM(CAST(ISNULL(CONVERT(char(12), OPERDT, 3),'') AS VARCHAR(10))))+ISNULL(OPERNRFAT,''),
       OPERDET=CASE WHEN OPERLLOJ IN('DF','PF') THEN 'DF'
                    WHEN OPERLLOJ IN('TA','PA') THEN 'TA'   
                    WHEN OPERLLOJ IN('KA','PK') THEN 'KA'
                    WHEN OPERLLOJ IN('AB','PB') THEN 'AB'
                    ELSE 'TJ' END                     
FROM  VSSCR INNER JOIN KLIENT ON VSSCR.KODAF=KLIENT.KOD
            INNER JOIN VS     ON VSSCR.NRD=VS.NRRENDOR
            LEFT  JOIN CONFIG..TIPDOK A ON ISNULL(OPERLLOJ,'')=A.KOD  
WHERE VSSCR.TIPKLL='S' AND A.TIPDOK='C'

UNION ALL
SELECT TOP 100 PERCENT
       KOD      =ARKASCR.KODAF,PERSHKRIM=KLIENT.PERSHKRIM,TEL1=KLIENT.TELEFON1,TEL2=KLIENT.TELEFON2,KOMENT=ARKASCR.KOMENT,KMON=ARKASCR.KMON,KURS1=ARKASCR.KURS1,KURS2=ARKASCR.KURS2,
       TIPDOK   =ISNULL(ARKASCR.TIPREF,''),NRDOK=ARKA.NUMDOK,FRAKSDOK=0,DATEDOK=ARKA.DATEDOK,VLEFTA=(ARKASCR.DB+ARKASCR.KR),
       VLEFTAMV =ABS(ARKASCR.DBKRMV),TREGDK=ARKASCR.TREGDK,TIPFAT=ISNULL(ARKASCR.TIPREF,''),NRFAT=ARKASCR.OPERNRFAT,DTFAT=ARKASCR.OPERDT,
       KODMASTER=ARKASCR.KODAF,OPERLLOJ=ISNULL(OPERLLOJ,''),OPERAPL,OPERORD,A.NRORD,ARKASCR.NRDITAR,
       GRUPREF=KLIENT.KOD+LTRIM(RTRIM(CAST(ISNULL(CONVERT(char(12), OPERDT, 3),'') AS VARCHAR(10))))+ISNULL(OPERNRFAT,''),
       OPERDET=CASE WHEN OPERLLOJ IN('DF','PF') THEN 'DF'
                    WHEN OPERLLOJ IN('TA','PA') THEN 'TA'   
                    WHEN OPERLLOJ IN('KA','PK') THEN 'KA'
                    WHEN OPERLLOJ IN('AB','PB') THEN 'AB'
                    ELSE 'TJ' END                     

FROM  ARKASCR INNER JOIN KLIENT   ON ARKASCR.KODAF=KLIENT.KOD
              INNER JOIN ARKA     ON ARKASCR.NRD=ARKA.NRRENDOR
              LEFT  JOIN CONFIG..TIPDOK A ON ISNULL(OPERLLOJ,'')=A.KOD  

WHERE ARKASCR.TIPKLL='S' AND A.TIPDOK='C'

UNION ALL
SELECT TOP 100 PERCENT
       KOD      =BANKASCR.KODAF,PERSHKRIM=KLIENT.PERSHKRIM,TEL1=KLIENT.TELEFON1,TEL2=KLIENT.TELEFON2,KOMENT=BANKASCR.KOMENT,KMON=BANKASCR.KMON,KURS1=BANKASCR.KURS1,KURS2=BANKASCR.KURS2,
       TIPDOK   =ISNULL(BANKASCR.TIPREF,''),NRDOK=BANKA.NUMDOK,FRAKSDOK=0,DATEDOK=BANKA.DATEDOK,VLEFTA=(BANKASCR.DB+BANKASCR.KR),
       VLEFTAMV =ABS(BANKASCR.DBKRMV),TREGDK=BANKASCR.TREGDK,TIPFAT=ISNULL(BANKASCR.TIPREF,''),NRFAT=BANKASCR.OPERNRFAT,DTFAT=BANKASCR.OPERDT,
       KODMASTER=BANKASCR.KODAF,OPERLLOJ=ISNULL(OPERLLOJ,''),OPERAPL,OPERORD,A.NRORD,BANKASCR.NRDITAR,
       GRUPREF=KLIENT.KOD+LTRIM(RTRIM(CAST(ISNULL(CONVERT(char(12), OPERDT, 3),'') AS VARCHAR(10))))+ISNULL(OPERNRFAT,''),
       OPERDET  =CASE WHEN OPERLLOJ IN('DF','PF') THEN 'DF'
                    WHEN OPERLLOJ IN('TA','PA') THEN 'TA'   
                    WHEN OPERLLOJ IN('KA','PK') THEN 'KA'
                    WHEN OPERLLOJ IN('AB','PB') THEN 'AB'
                    ELSE 'TJ' END                     

FROM  BANKASCR INNER JOIN KLIENT   ON BANKASCR.KODAF=KLIENT.KOD
               INNER JOIN BANKA    ON BANKASCR.NRD=BANKA.NRRENDOR
               LEFT  JOIN CONFIG..TIPDOK A ON ISNULL(OPERLLOJ,'')=A.KOD  

WHERE BANKASCR.TIPKLL='S' AND A.TIPDOK='C'













GO
