SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO



CREATE                      VIEW [dbo].[QFKSCRYOUNG] AS 
SELECT TOP 100 PERCENT FK.DATEDOK,FKSCR.KOD,
FKSCR.LLOGARIPK,
UNIT      ='MK104',
OPUNIT    =ISNULL(LEFT(RIGHT(FKSCR.KOD,LEN(FKSCR.KOD)-CHARINDEX('.',FKSCR.KOD)),CHARINDEX('.',RIGHT(FKSCR.KOD,LEN(FKSCR.KOD)-CHARINDEX('.',FKSCR.KOD)))-1),''),
MGMUNIT   =CASE WHEN LEFT(LLOGARIPK,1)>='6' AND LEFT(LLOGARIPK,1)<'8' THEN '00836' ELSE '99999' END, 
SUBMGMUNIT=ISNULL(LEFT(RIGHT(RIGHT(FKSCR.KOD,LEN(FKSCR.KOD)-CHARINDEX('.',FKSCR.KOD)),LEN(RIGHT(FKSCR.KOD,LEN(FKSCR.KOD)-CHARINDEX('.',FKSCR.KOD)))-CHARINDEX('.',RIGHT(FKSCR.KOD,LEN(FKSCR.KOD)-CHARINDEX('.',FKSCR.KOD)))),CHARINDEX('.',RIGHT(RIGHT(FKSCR.KOD,LEN(FKSCR.KOD)-CHARINDEX('.',FKSCR.KOD)),LEN(RIGHT(FKSCR.KOD,LEN(FKSCR.KOD)-CHARINDEX('.',FKSCR.KOD)))-CHARINDEX('.',RIGHT(FKSCR.KOD,LEN(FKSCR.KOD)-CHARINDEX('.',FKSCR.KOD)))))-1),''),
ACCGFIS   =ISNULL(LLOGARI.PERSHKRIM1,''),
ENGAGEID  =CASE WHEN (FF.KLASIFIKIM IS NULL) OR (LEFT(LLOGARIPK,1)<>'6') THEN '' ELSE FF.KLASIFIKIM END,
VENDORID  =CASE WHEN (FF.KLASIFIKIM IS NULL) OR (LEFT(LLOGARIPK,1)<>'6') THEN '' ELSE 'ZZ00000014'  END,
ACTID     =CASE WHEN (FF.KLASIFIKIM IS NULL) OR (LEFT(LLOGARIPK,1)<>'6') THEN '' ELSE '0000'        END,
WRKLOCK1  =CASE WHEN (FF.KLASIFIKIM IS NULL) OR (LEFT(LLOGARIPK,1)<>'6') THEN '' ELSE 'ALB'         END,
WRKLOCK2  =CASE WHEN (FF.KLASIFIKIM IS NULL) OR (LEFT(LLOGARIPK,1)<>'6') THEN '' ELSE 'OTHER'       END,
KOMENT    =ISNULL(FKSCR.KOMENT,''),
VLDB      =CASE WHEN TREGDK='D' THEN    DBKRMV ELSE 0 END,
VLKR      =CASE WHEN TREGDK='K' THEN -1*DBKRMV ELSE 0 END
FROM FK INNER JOIN FKSCR   ON FK.NRRENDOR=FKSCR.NRD
        INNER JOIN LLOGARI ON FKSCR.LLOGARIPK=LLOGARI.KOD
        LEFT  JOIN FF      ON  FK.NRRENDOR=FF.NRDFK
ORDER BY FK.DATEDOK,FKSCR.NRD,FKSCR.NRRENDOR


GO
