SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO


CREATE       VIEW [dbo].[S_LIBSHAN] AS 

SELECT NIPT=MAX(FJ.NIPT),KODFISKAL=MAX(FJ.KODFISKAL),SHENIM1=MAX(FJ.SHENIM1),KODFKL=MAX(FJ.KODFKL),KMON=MAX(FJ.KMON),
       NRSERIAL=MAX(FJ.NRSERIAL),RRETHI=MAX(FJ.RRETHI),KMAG=MAX(FJ.KMAG),DATEDOK=MAX(FJ.DATEDOK),
       FJ.NRRENDOR,KLASIFIKIM=MAX(KLASIFIKIM),ISDG=MAX(CASE WHEN FJ.ISDG=1 THEN 1 ELSE 0 END),KURS1=MAX(KURS1),KURS2=MAX(KURS2),
       NRDOKDG=MAX(FJ.NRDOKDG),DTDOKDG=MAX(FJ.DTDOKDG),DTDSHOQ=MAX(FJ.DTDSHOQ),NRDSHOQ=MAX(FJ.NRDSHOQ),ISDOKSHOQ=MAX(CASE WHEN FJ.ISDOKSHOQ=1 THEN 1 ELSE 0 END),
       VLPATVSH=SUM(FJSCR.VLPATVSH)-MAX(VLERZBR),VLTVSH=MAX(FJ.VLTVSH),VLERZBR=0,
       VLERTOT =SUM(FJSCR.VLPATVSH)-MAX(VLERZBR)+MAX(FJ.VLTVSH)
FROM FJ INNER JOIN FJSCR ON FJ.NRRENDOR=FJSCR.NRD
WHERE FJSCR.VLTVSH<>''
GROUP BY FJ.NRRENDOR
UNION ALL
SELECT NIPT=MAX(FJ.NIPT),KODFISKAL=MAX(FJ.KODFISKAL),SHENIM1=MAX(FJ.SHENIM1),KODFKL=MAX(FJ.KODFKL),KMON=MAX(FJ.KMON),
       NRSERIAL=MAX(FJ.NRSERIAL),RRETHI=MAX(FJ.RRETHI),KMAG=MAX(FJ.KMAG),DATEDOK=MAX(FJ.DATEDOK),
       FJ.NRRENDOR,KLASIFIKIM=MAX(KLASIFIKIM),ISDG=MAX(CASE WHEN FJ.ISDG=1 THEN 1 ELSE 0 END),KURS1=MAX(KURS1),KURS2=MAX(KURS2),
       NRDOKDG=MAX(FJ.NRDOKDG),DTDOKDG=MAX(FJ.DTDOKDG),DTDSHOQ=MAX(FJ.DTDSHOQ),NRDSHOQ=MAX(FJ.NRDSHOQ),ISDOKSHOQ=MAX(CASE WHEN FJ.ISDOKSHOQ=1 THEN 1 ELSE 0 END),
       VLPATVSH=SUM(FJSCR.VLPATVSH),VLTVSH=SUM(FJSCR.VLTVSH),VLERZBR=0,
       VLERTOT=SUM(FJSCR.VLERABS)
FROM FJ INNER JOIN FJSCR ON FJ.NRRENDOR=FJSCR.NRD
WHERE FJSCR.VLTVSH=0
GROUP BY FJ.NRRENDOR






GO
