SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO



CREATE    VIEW [dbo].[S_DKLPAG] AS
      SELECT TOP 100 PERCENT 
             KOD         = MIN(A.KOD),
             KODFKL      = LEFT(A.KOD, CASE WHEN CHARINDEX ('.',A.KOD )>0 THEN CHARINDEX ('.',A.KOD)-1 ELSE LEN(A.KOD) END), 
             KMON        = MAX(A.KMON),
             VLEFTAPAG   = SUM(CASE WHEN A.TREGDK='K' THEN A.VLEFTA   ELSE 0-A.VLEFTA   END),
             VLEFTAMVPAG = SUM(CASE WHEN A.TREGDK='K' THEN A.VLEFTAMV ELSE 0-A.VLEFTAMV END) 
        FROM DKL A
       WHERE (A.TREGDK='K') OR (A.TREGDK='D' AND A.VLEFTA<0)      
    GROUP BY LEFT(A.KOD, CASE WHEN CHARINDEX ('.',A.KOD )>0 THEN CHARINDEX ('.',A.KOD)-1 ELSE LEN(A.KOD) END) 
--ORDER BY KODFKL


GO
