SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[ARKATDRH] 

AS
  
      SELECT A.*,KODUS=C.KODUS
        FROM ARKAT A INNER JOIN DRHReference C ON A.KOD=C.KOD
       WHERE REFERENCE='ARKAT'
--  ORDER BY A.KOD
GO
