SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO



CREATE       VIEW [dbo].[LEVIZJEHDSM] 

AS 

      SELECT TOP 100 PERCENT 
             TIP='H', A.NRRENDOR, A.KMAG, A.NRMAG, A.NRDOK, A.NRFRAKS, A.DATEDOK, A.DOK_JB, A.DST, A.KTH, A.SHENIM1, A.SHENIM2, A.SHENIM3, A.SHENIM4, 
             B.KOD, B.KODAF, B.KARTLLG, B.PERSHKRIM, B.NJESI, B.DTSKADENCE, B.SERI, 

             B.CMIMM, SASIH=B.SASI, VLERAH=B.VLERAM, SASID=0, VLERAD=0,

             B.NRD, NRRENDORSCR=B.NRRENDOR, GJENROWAUT=ISNULL(B.GJENROWAUT,0)

        FROM FH A LEFT JOIN FHSCR B ON A.NRRENDOR=B.NRD


   UNION ALL


      SELECT TOP 100 PERCENT 
             TIP='D', A.NRRENDOR, A.KMAG, A.NRMAG, A.NRDOK, A.NRFRAKS, A.DATEDOK, A.DOK_JB, A.DST, A.KTH, A.SHENIM1, A.SHENIM2, A.SHENIM3, A.SHENIM4,
             B.KOD, B.KODAF, B.KARTLLG, B.PERSHKRIM, B.NJESI, B.DTSKADENCE, B.SERI, 

             B.CMIMM, SASIH=0, VLERAH=0, SASID=B.SASI, VLERAD=B.VLERAM,

             B.NRD, NRRENDORSCR=B.NRRENDOR, GJENROWAUT=ISNULL(B.GJENROWAUT,0)

        FROM FD A LEFT JOIN FDSCR B ON A.NRRENDOR=B.NRD


   UNION ALL


      SELECT TOP 100 PERCENT 
             TIP='D', A.NRRENDOR, A.KMAG, A.NRMAG, A.NRDOK, NRFRAKS=0, A.DATEDOK, DOK_JB=1, DST='', KTH=0, A.SHENIM1, A.SHENIM2, A.SHENIM3, A.SHENIM4,       
             B.KOD, B.KODAF, B.KARTLLG, B.PERSHKRIM, B.NJESI, DTSKADENCE=NULL, SERI=0, 
             
             B.CMIMM, SASIH=0, VLERAH=0, SASID=B.SASI, VLERAD=B.VLERAM,
             
             B.NRD, NRRENDORSCR=B.NRRENDOR, GJENROWAUT=0
             
        FROM SM A LEFT JOIN SMSCR B ON A.NRRENDOR=B.NRD


    ORDER BY KMAG,DATEDOK,NRDOK  -- Nuk ka nevoje per renditje




GO
