SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[T_DOKDIT_KL] AS 
SELECT TOP 100 PERCENT NRRENDOR,NRDITAR,'S' AS TIPD
  FROM FJ
 UNION ALL 
SELECT TOP 100 PERCENT NRRENDOR,NRDITARSHL,'S' AS TIPD
  FROM FJ
 WHERE PARAPG<>0
 UNION ALL 
SELECT TOP 100 PERCENT VSSCR.NRRENDOR,VSSCR.NRDITAR,'E' AS TIPD
  FROM VS INNER JOIN VSSCR ON VS.NRRENDOR=VSSCR.NRD
 WHERE TIPKLL='S'
 UNION ALL
SELECT TOP 100 PERCENT ARKASCR.NRRENDOR,ARKASCR.NRDITAR,'A' AS TIPD
  FROM ARKA INNER JOIN ARKASCR ON ARKA.NRRENDOR=ARKASCR.NRD
 WHERE TIPKLL='S'
 UNION ALL 
SELECT TOP 100 PERCENT BANKASCR.NRRENDOR,NRDITAR=BANKASCR.NRDITAR,'B' AS TIPD
  FROM BANKA INNER JOIN BANKASCR ON BANKA.NRRENDOR=BANKASCR.NRD
 WHERE TIPKLL='S'
ORDER BY NRDITAR


GO
