SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO





CREATE                     VIEW [dbo].[LEVIZJEHDKopje] AS 
SELECT TOP 100 PERCENT 
       FH.NRRENDOR,KMAG, NRMAG,NRDOK, NRFRAKS, DATEDOK, DOK_JB,DST,KTH,TIPDOK='FH',
       SHENIM1,SHENIM2,SHENIM3,SHENIM4,KODLM=ISNULL(KODLM,''),NRRENDORFAT, 
       KMAGLNK, NRDOKLNK, NRFRAKSLNK, DATEDOKLNK,
       KOD, KODAF, KARTLLG, PERSHKRIM,TIP='H',
       CMIMM,
       SASIH=SASI,VLERAH=VLERAM,VLERASHH=VLERASH,SASID=0,VLERAD=0,VLERASHD=0,
       NJESI,
       SASIHKOEF=ISNULL(KOEFICIENT,0),SASIDKOEF=0,
       FHSCR.DTSKADENCE,FHSCR.SERI,NRD,
       NRRENDORSCR=FHSCR.NRRENDOR,GJENROWAUT=ISNULL(GJENROWAUT,0),TIPFR,SASIFR,TIPKTH,KONVERTART
FROM FH LEFT JOIN FHSCR ON FH.NRRENDOR = FHSCR.NRD

UNION ALL
SELECT TOP 100 PERCENT 
       FD.NRRENDOR,KMAG, NRMAG,NRDOK, NRFRAKS, DATEDOK, DOK_JB,DST,KTH,TIPDOK='FD',
       SHENIM1,SHENIM2,SHENIM3,SHENIM4,KODLM=ISNULL(KODLM,''),NRRENDORFAT,
       KMAGLNK, NRDOKLNK, NRFRAKSLNK, DATEDOKLNK,       
       KOD, KODAF, KARTLLG, PERSHKRIM,TIP='D',
       FDSCR.CMIMM,SASIH=0,VLERAH=0,VLERASHH=0,SASID=SASI,VLERAD=VLERAM,VLERASHD=VLERASH,NJESI,
       SASIHKOEF=0,SASIDKOEF=ISNULL(KOEFICIENT,0),
       FDSCR.DTSKADENCE,FDSCR.SERI,NRD,
       NRRENDORSCR=FDSCR.NRRENDOR,GJENROWAUT=ISNULL(GJENROWAUT,0),TIPFR,SASIFR,TIPKTH,KONVERTART

FROM FD LEFT JOIN FDSCR ON FD.NRRENDOR = FDSCR.NRD
ORDER BY KMAG,DATEDOK,NRDOK





















GO
