SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[T_DOKDIT_AR] AS 
SELECT TOP 100 PERCENT NRRENDOR,NRDITAR,'A' AS TIPD
  FROM ARKA 
 UNION ALL 
SELECT TOP 100 PERCENT VSSCR.NRRENDOR,NRDITAR,'E' AS TIPD
  FROM VS INNER JOIN VSSCR ON VS.NRRENDOR=VSSCR.NRD
 WHERE TIPKLL='A'
ORDER BY NRDITAR

GO
