SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO





CREATE                 VIEW [dbo].[PRODUKTKOSTOPERBERES] AS 
SELECT ARTIKUJ.KOD,KOSTOPROD=SUM(ARTIKUJSCR.KOEFICIENT*A.KOSTMES)
FROM ARTIKUJ INNER JOIN ARTIKUJSCR ON ARTIKUJ.NRRENDOR=ARTIKUJSCR.NRD
             INNER JOIN ARTIKUJ A ON A.KOD=ARTIKUJSCR.KOD
GROUP BY ARTIKUJ.KOD


GO
