SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO


CREATE     VIEW [dbo].[DFUAN] AS 

SELECT TOP 100 PERCENT 
       SG1=MAX(FF.KODFKL),KOD=FF.KODFKL+'.'+RIGHT(FFSCR.KODAF+'.',LEN(FFSCR.KODAF+'.')-CHARINDEX('.',FFSCR.KODAF+'.')),
       PERSHKRIM=MAX(FF.SHENIM1),KOMENT=MAX(ISNULL(FF.SHENIM2,'')),KMON=MAX(FF.KMON),KURS1=MAX(FF.KURS1),KURS2=MAX(FF.KURS2),
       TIPDOK='FF',NRDOK=MAX(FF.NRDOK),FRAKSDOK=0,DATEDOK=MAX(FF.DATEDOK),
       VLEFTA=SUM(FFSCR.VLERABS),VLEFTAMV=SUM(FFSCR.VLERABS*KURS2/KURS1),TREGDK='K',
       NRFAT=MAX(NRDSHOQ),DTFAT=MAX(DTDSHOQ),KODMASTER=MAX(FF.KODFKL),TROW=0,TAGNR=0,NRRENDOR=MIN(FF.NRRENDOR)
FROM FF INNER JOIN FFSCR ON FF.NRRENDOR=FFSCR.NRD
GROUP BY FF.NRRENDOR,FF.KODFKL+'.'+RIGHT(FFSCR.KODAF+'.',LEN(FFSCR.KODAF+'.')-CHARINDEX('.',FFSCR.KODAF+'.'))
UNION ALL

SELECT TOP 100 PERCENT 
       SG1=ARKASCR.LLOGARIPK,KOD=ARKASCR.KODAF+'.',
       PERSHKRIM=ARKASCR.PERSHKRIM,KOMENT=ISNULL(ARKASCR.KOMENT,''),KMON=ARKASCR.KMON,KURS1=ARKASCR.KURS1,KURS2=ARKASCR.KURS2,
       TIPDOK=ARKA.TIPDOK,NRDOK=ARKA.NUMDOK,FRAKSDOK=0,DATEDOK=ARKA.DATEDOK,
       VLEFTA=ARKASCR.DB+ARKASCR.KR,VLEFTAMV=(ARKASCR.DB+ARKASCR.KR)*ARKASCR.KURS2/ARKASCR.KURS1,ARKASCR.TREGDK,
       NRFAT=NRDOKREF,DTFAT=DATEDOKREF,KODMASTER=ARKA.KODAB,TROW=0,TAGNR=0,NRRENDOR=ARKA.NRRENDOR
FROM ARKA INNER JOIN ARKASCR ON ARKA.NRRENDOR=ARKASCR.NRD
WHERE TIPKLL='F'

UNION ALL
SELECT TOP 100 PERCENT 
       SG1=BANKASCR.LLOGARIPK,KOD=BANKASCR.KODAF+'.',
       PERSHKRIM=BANKASCR.PERSHKRIM,KOMENT=ISNULL(BANKASCR.KOMENT,''),KMON=BANKASCR.KMON,KURS1=BANKASCR.KURS1,KURS2=BANKASCR.KURS2,
       TIPDOK=BANKA.TIPDOK,NRDOK=BANKA.NUMDOK,FRAKSDOK=0,DATEDOK=BANKA.DATEDOK,
       VLEFTA=BANKASCR.DB+BANKASCR.KR,VLEFTAMV=(BANKASCR.DB+BANKASCR.KR)*BANKASCR.KURS2/BANKASCR.KURS1,BANKASCR.TREGDK,
       NRFAT=NRDOKREF,DTFAT=DATEDOKREF,KODMASTER=BANKA.KODAB,TROW=0,TAGNR=0,NRRENDOR=BANKA.NRRENDOR
FROM BANKA INNER JOIN BANKASCR ON BANKA.NRRENDOR=BANKASCR.NRD
WHERE TIPKLL='F'

UNION ALL
SELECT TOP 100 PERCENT 
       SG1=VSSCR.LLOGARIPK,KOD=VSSCR.KODAF+'.',
       PERSHKRIM=VSSCR.PERSHKRIM,KOMENT=ISNULL(VSSCR.KOMENT,''),KMON=VSSCR.KMON,KURS1=VSSCR.KURS1,KURS2=VSSCR.KURS2,
       TIPDOK='VS',NRDOK=VS.NRDOK,FRAKSDOK=0,DATEDOK=VS.DATEDOK,
       VLEFTA=VSSCR.DB+VSSCR.KR,VLEFTAMV=(VSSCR.DB+VSSCR.KR)*VSSCR.KURS2/VSSCR.KURS1,VSSCR.TREGDK,
       NRFAT=NRDOKREF,DTFAT=DATEDOKREF,KODMASTER=VSSCR.LLOGARIPK,TROW=0,TAGNR=0,NRRENDOR=VS.NRRENDOR
FROM VS INNER JOIN VSSCR ON VS.NRRENDOR=VSSCR.NRD
WHERE TIPKLL='F'







GO
