SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[LLOGNRTIMEDB]
AS
SELECT TOP 100 PERCENT FKSCR.KOD, FKSCR.NRD, FKSCR.NRRENDOR, FK.DATEDOK, 
(SELECT SUM(1) 
FROM FK AS FK1 LEFT JOIN FKSCR AS FKSCR1 ON FK1.NRRENDOR=FKSCR1.NRD 
WHERE   (FKSCR1.TREGDK='D') AND (FKSCR1.KOD=FKSCR.KOD) AND (FK1.DATEDOK<=FK.DATEDOK) AND
              ((FKSCR1.NRD<>FKSCR.NRD) OR (FKSCR.NRRENDOR<>FKSCR.NRRENDOR))) NRTDB, 

              NRTIMEDB=(CASE
                WHEN (SELECT SUM(1) 
                      FROM FK AS FK1 LEFT JOIN FKSCR AS FKSCR1 ON FK1.NRRENDOR=FKSCR1.NRD 
                      WHERE   (FKSCR1.TREGDK='D') AND (FKSCR1.KOD=FKSCR.KOD) AND (FK1.DATEDOK<=FK.DATEDOK) AND
                      ((FKSCR1.NRD<>FKSCR.NRD) OR (FKSCR.NRRENDOR<>FKSCR.NRRENDOR))) IS NULL  THEN 0
                ELSE 1
              END)+1
FROM FK LEFT JOIN FKSCR ON FK.NRRENDOR = FKSCR.NRD
ORDER BY FKSCR.KOD, FK.DATEDOK




GO
