SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO












CREATE           VIEW [dbo].[FU_POROSIFF] AS 

SELECT NRRENDOR=MAX(FF.NRRENDOR),DATEDOK=MAX(DATEDOK),NRDOK=MAX(NRDOK),KODFKL=MAX(KODFKL),
       SHENIM1=MAX(SHENIM1),NRDSHOQ=MAX(NRDSHOQ),DTDSHOQ=MAX(DTDSHOQ),
       KMON=MAX(KMON),KURS1=MAX(KURS1),KURS2=MAX(KURS2),FF.NRRENDOROR,
       FFSCR.KARTLLG,PERSHKRIM=MAX(FFSCR.PERSHKRIM),NJESI=MAX(FFSCR.NJESI),SASI=SUM(FFSCR.SASI),
       CMIMBS=CASE WHEN SUM(FFSCR.SASI)<>0 THEN SUM(FFSCR.VLPATVSH)/SUM(FFSCR.SASI) ELSE 1 END,
       VLPATVSH=SUM(FFSCR.VLPATVSH),VLTVSH=SUM(FFSCR.VLTVSH),VLERABS=SUM(FFSCR.VLERABS),FFSCR.TIPKLL
FROM FF INNER JOIN FFSCR ON FF.NRRENDOR=FFSCR.NRD
WHERE ISNULL(FF.NRRENDOROR,0)<>0
GROUP BY FF.NRRENDOROR,FFSCR.KARTLLG,FFSCR.TIPKLL




GO
