SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[P_ARTIKUJ_BC_PRINT_ARTTMP] AS
/*
 KJO TABELE MJAFTON TE KETE VETEM DY KOLNA [KOD,BARKOD] 
 DHE TE TJERAT MERREN NGA TABELAT 
 ARTIKUJ,ARTIKUJCMAD dhe ARTIKUJ_BC_PRINT
*/
if object_id('ARTTMP') is not null
begin
  drop table dbo.ARTTMP
end

SELECT 
        ABP.KOD ,
        A.PERSHKRIM ,
        ABP.BC ,
        A.CMSH ,
        A.KLASIF ,
        A.KLASIF2 ,
        A.KLASIF3 ,
        A.KLASIF4 ,
        A.KLASIF5 ,
        A.KLASIF6 ,
        ABP.SHENIME ,
        ABP.SASIAPRINT ,
        ABP.GARANCI ,
        ABP.VMD ,
        ABP.TAG,
        ABP.NGJYRE,
        ABP.MASE
INTO ARTTMP
FROM  ARTIKUJ_BC_PRINT ABP
INNER JOIN ARTIKUJ A ON A.KOD=ABP.KOD
WHERE ABP.NRRENDOR=-1

GO
