SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE procedure [dbo].[getNrdokFj](@user as int)
as
DECLARE @VNRDOKMIN AS INTEGER
DECLARE @VNRDOKMAX AS INTEGER
DECLARE @VNRDOK AS INTEGER
DECLARE @PKODUSER AS VARCHAR;

SET @PKODUSER = (SELECT TOP 1 USERN FROM DRH..USERS WHERE NRRENDOR=@USER)

SET @VNRDOKMIN=ISNULL((SELECT NRKUFIP FROM DRHUSER WHERE MODUL='S' AND KODUS=@PKODUSER),1)
SET @VNRDOKMAX=ISNULL((SELECT NRKUFIS FROM DRHUSER WHERE MODUL='S' AND KODUS=@PKODUSER),999999999)

SET @VNRDOK   =ISNULL((SELECT MAX(NRDOK) AS NRMAX FROM FJ 
                WHERE (YEAR(DATEDOK)=YEAR(GETDATE())) AND (NRDOK BETWEEN @VNRDOKMIN AND @VNRDOKMAX))+1,@VNRDOKMIN)

select @VNRDOK
GO
