SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[P_CSH_REKORD_UNIK] @ID INT AS
DECLARE
@TIP_SHITJE VARCHAR(10),
@DATE_FILLIMI DATETIME,
@KOD VARCHAR(25),
@KMON VARCHAR(10),
@KOD_SHITJE VARCHAR(25) --MUND TE PERDORET DHE MONEDHA SI CELES

SELECT 
   @DATE_FILLIMI=DATE_FILLIMI,
   @TIP_SHITJE=TIP_SHITJE,
   @KOD=KOD,
   @KOD_SHITJE= KOD_SHITJE FROM CSH_LISTA
WHERE ID=@ID

SELECT HERE=COUNT(*) FROM dbo.CSH_LISTA   
WHERE  
   TIP_SHITJE=@TIP_SHITJE 
   AND    KOD=@KOD 
   AND    DATE_FILLIMI=@DATE_FILLIMI
   AND ISNULL(KOD_SHITJE,'') = ISNULL(@KOD_SHITJE, '')
   

GO
