SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO






-- Exec ZeroDok @PKodMagKp= '',        
--              @PKodMagKs= 'zz',
--              @PDeriDtKp= '01/02/2010', 
--              @PDeriDtKs= '31/12/2010'

CREATE   procedure [dbo].[ZeroDok]
 (
  @PKodMagKp As Varchar(20),
  @PKodMagKs As Varchar(20),
  @PDeriDtKp As Varchar(20),
  @PDeriDtKs As Varchar(20)
  )
AS

Set @PKodMagKp=QuoteName(@PKodMagKp,'''')
Set @PKodMagKs=QuoteName(@PKodMagKs,'''')
Set @PDeriDtKp=QuoteName(@PDeriDtKp,'''')
Set @PDeriDtKs=QuoteName(@PDeriDtKs,'''')

DELETE FROM ARKA
DELETE FROM ARKASCR
DELETE FROM ARKAT
DELETE FROM FK
DELETE FROM FKSCR
DELETE FROM FKST
DELETE FROM FKSTSCR
DELETE FROM VS
DELETE FROM VSSCR
DELETE FROM VSST
DELETE FROM VSSTSCR

DELETE FROM BANKA
DELETE FROM BANKASCR
DELETE FROM BANKAT
DELETE FROM BORDERO

DELETE FROM LAQ
DELETE FROM LAR
DELETE FROM LBA


Exec(' DELETE
         FROM FH
        WHERE (DATEDOK>=DBO.DATEVALUE('+@PDeriDtKp+') AND DATEDOK<=DBO.DATEVALUE('+@PDeriDtKs+'))')

Exec(' DELETE
         FROM FD
        WHERE (DATEDOK>=DBO.DATEVALUE('+@PDeriDtKp+') AND DATEDOK<=DBO.DATEVALUE('+@PDeriDtKs+'))')
Exec(' DELETE
         FROM FF
        WHERE (DATEDOK>=DBO.DATEVALUE('+@PDeriDtKp+') AND DATEDOK<=DBO.DATEVALUE('+@PDeriDtKs+'))')
Exec(' DELETE
         FROM FJ
        WHERE (DATEDOK>=DBO.DATEVALUE('+@PDeriDtKp+') AND DATEDOK<=DBO.DATEVALUE('+@PDeriDtKs+'))')

Exec(' DELETE
         FROM DKL
        WHERE (DATEDOK>=DBO.DATEVALUE('+@PDeriDtKp+') AND DATEDOK<=DBO.DATEVALUE('+@PDeriDtKs+'))')
Exec(' DELETE
         FROM DFU
        WHERE (DATEDOK>=DBO.DATEVALUE('+@PDeriDtKp+') AND DATEDOK<=DBO.DATEVALUE('+@PDeriDtKs+'))')



--DELETE FROM ARTIKUJ
--DELETE FROM ARTIKUJ_PATH
--DELETE FROM ARTIKUJ_RBOT
--
--DELETE FROM ARTIKUJ_RCD
--DELETE FROM ARTIKUJ_RMAK
--DELETE FROM ARTIKUJCM
--DELETE FROM ARTIKUJFIR
--DELETE FROM ARTIKUJKLS1
--DELETE FROM ARTIKUJKLS2
--DELETE FROM ARTIKUJKLS3
--DELETE FROM ARTIKUJSCR
--DELETE FROM ARTIKUJSIST


-- DELETE FROM CONFIGLM
-- DELETE FROM CONFIGMG
-- DELETE FROM CONFND

--DELETE FROM DAR
--DELETE FROM DBA
--DELETE FROM DEPARTAMENT
--DELETE FROM DFU
--DELETE FROM DG
--DELETE FROM DGSCR
--DELETE FROM DKL

--DELETE FROM FF
--DELETE FROM FFSCR
--
--DELETE FROM FH
--DELETE FROM FHSCR
--
--DELETE FROM FJ
--DELETE FROM FJSCR
--DELETE FROM FJPG
--DELETE FROM FJSHOQERUES
--DELETE FROM FJT
--DELETE FROM FJTSCR

--DELETE FROM AGJENTSHITJE
--DELETE FROM FURNITOR
--DELETE FROM GRUPIMFT
--
--DELETE FROM KALENDAR
--DELETE FROM KASE

--DELETE FROM KATEGORI
--DELETE FROM KLIENT
--DELETE FROM KURSE

--
--DELETE FROM LFU
--DELETE FROM LKL
--DELETE FROM LM
--DELETE FROM LMG

--DELETE FROM MAGAZINA
--DELETE FROM NENDITAR
--DELETE FROM NJESI
--
--DELETE FROM OFK
--DELETE FROM OFKSCR
--
--DELETE FROM ORF
--DELETE FROM ORFSCR
--
--DELETE FROM ORK
--DELETE FROM ORKSCR
--
--DELETE FROM PERIUDHE
--DELETE FROM PROFITCENTER
--
--DELETE FROM RAJON
--DELETE FROM SHERBIM
--
--DELETE FROM SM
--DELETE FROM SMSCR
--
--DELETE FROM TATIM
--DELETE FROM TRANSPORT
--DELETE FROM VENDNDODHJE
--
--DELETE FROM ZBRITJE
--




GO
