SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROC [dbo].[VW_0SHITJE_KRAHASUESE_FURNITOR]
(@DNGA AS DATETIME,@DDERI AS DATETIME,
 @FURN1 AS VARCHAR(50),@FURN2 AS VARCHAR(50)
)
AS

begin try
	drop table #t
end try
begin catch
end catch

CREATE TABLE #T(
	KOD varchar(50) NULL,
	CMB float NULL,
	CMSH float NULL,
	KODFURN VARCHAR(50) NULL)
CREATE NONCLUSTERED INDEX IX_T ON #T 
(
	KOD ASC
)


INSERT INTO #T(KOD,CMB,CMSH,KODFURN) 
SELECT KOD, (SELECT TOP 1 CMIMB= AVG(CASE WHEN SASI=0 THEN CMIMM ELSE VLERABS/SASI END) FROM FFSCR 
INNER JOIN FF ON FF.NRRENDOR= FFSCR.NRD
WHERE FF.DATEDOK<=@DDERI AND FFSCR.KARTLLG = ARTIKUJ.Kod
--ORDER BY FF.DATEDOK DESC
)
AS CMB, (SELECT TOP 1 CMIMSH= AVG(CASE WHEN SASI=0 THEN CMIMM ELSE VLERABS/SASI END) FROM FJSCR 
INNER JOIN FJ ON FJ.NRRENDOR= FJSCR.NRD
WHERE FJ.DATEDOK<=@DDERI AND FJSCR.KARTLLG = ARTIKUJ.Kod
--ORDER BY FJ.DATEDOK DESC
)
AS CMSH, 
(SELECT TOP 1 KODFKL FROM FFSCR 
INNER JOIN FF ON FF.NRRENDOR= FFSCR.NRD
WHERE FF.DATEDOK<=@DDERI AND FFSCR.KARTLLG = ARTIKUJ.Kod
--ORDER BY FF.DATEDOK DESC
) AS KODFURN
FROM ARTIKUJ


SELECT	F.KOD,
		PERSHKRIM = MIN(F.PERSHKRIM),
		SASI = SUM(SASI),
		VLERE = SUM(SC.VLPATVSH),
		@DNGA AS DATANGA, 
		@DDERI AS DATADERI,
		@FURN1 AS FURN1,
		@FURN2 AS FURN2,
		(select count(1) from ff where datedok >= @dnga and datedok <=@dderi and kodfkl = f.kod) as BLERJE,
		(select AVG(((CMSH-CMB)/CMSH)*100) FROM #T WHERE KODFURN = F.KOD AND CMB <>0) AS MARZH,
		(select AVG(((CMSH-CMB)/CMB)*100) FROM #T WHERE KODFURN = F.KOD AND CMB <>0) AS MarkUp,
		(select SUM(FJSCR.VLPATVSH-FDSCR.VLERABS) FROM FJ
			INNER JOIN FD ON FD.NRRENDORFAT = FJ.NRRENDOR
			INNER JOIN FJSCR ON FJSCR.NRD = FJ.NRRENDOR
			INNER JOIN FDSCR ON FDSCR.NRD = FD.NRRENDOR AND FJSCR.KARTLLG = FDSCR.KARTLLG
			WHERE FJSCR.KARTLLG IN (SELECT KOD FROM ARTIKUJ WHERE FURNKOD = F.KOD)) AS FITIMBRUTO
FROM	FJ S
INNER JOIN FJSCR SC ON SC.NRD = S.NRRENDOR
INNER JOIN ARTIKUJ A ON A.KOD = SC.KARTLLG
INNER JOIN FURNITOR F ON F.KOD = A.FURNKOD--A.KLASIF--<--
--KUJDES ME LART DUHET FUSHA KU ESHTE MBUSHUR KODI I FURNITORIT
WHERE S.DATEDOK>=@DNGA AND S.DATEDOK<=@DDERI
AND (F.KOD = @FURN1 OR F.KOD = @FURN2) 
GROUP BY F.KOD

GO
