SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[Isd_GatiFiskalSM]           -- U MOR NGA ISD_GATIFISCAL dhe U BE VETEM REPLACE STRING 'FJ' me STRINGUN 'SM'.
(
 @pNrRendor Integer
)
AS
BEGIN
SET NOCOUNT ON;
	DECLARE @TEMPOUTPUT VARCHAR(MAX)

	DECLARE @OUTPUT1 VARCHAR(MAX)
	DECLARE @OUTPUT2 VARCHAR(MAX)
	DECLARE @OUTPUT3 VARCHAR(MAX)
	DECLARE @OUTMESSAGE VARCHAR(MAX)
	DECLARE @TIPPAGESE VARCHAR(MAX)
	DECLARE @TIPKLIENT VARCHAR(MAX)
	DECLARE @SELF VARCHAR(MAX)
	DECLARE @NIPT VARCHAR(MAX)

	SET @NIPT=(SELECT NIPT FROM CONFND)
	SET @TEMPOUTPUT=''

	SET @TIPPAGESE=(SELECT top 1 KLASEPAGESE FROM SM A INNER JOIN FisMenPagese B ON  A.FISMENPAGESE=B.KOD WHERE A.NRRENDOR=@pNrRendor)
	--SET @TIPKLIENT=(SELECT top 1 CASE WHEN ISNULL(TIPNIPT,'')='' THEN 'NUIS' ELSE TIPNIPT END FROM SM A INNER JOIN KLIENT B ON A.KODFKL=B.KOD WHERE A.NRRENDOR=@pNrRendor)
	SET @TIPKLIENT=(SELECT top 1 TIPNIPT  FROM SM A INNER JOIN KLIENT B ON A.KODFKL=B.KOD WHERE A.NRRENDOR=@pNrRendor)
	--SET @SELF=(SELECT CASE WHEN A.NIPT=@NIPT AND ISNULL(A.KLASETVSH,'')<>'SANG' THEN  'SELF' 
	--								   WHEN A.KLASETVSH='SANG' THEN 'DOMESTIC' 
	--								   ELSE  NULL END FROM SM A WHERE A.NRRENDOR=@pNrRendor)
	SET @SELF=(SELECT CASE WHEN ISNULL(A.KLASETVSH,'') IN ('OTHER','AGREEMENT','SELF','SEXP') THEN  A.KLASETVSH
									   WHEN A.KLASETVSH='SANG' THEN 'DOMESTIC' 
									   ELSE  NULL END FROM SM A WHERE A.NRRENDOR=@pNrRendor)
	

	IF @TIPPAGESE='BANKE' AND @TIPKLIENT='NUIS' AND @SELF IS NULL
	--IF  @TIPKLIENT='NUIS' AND @SELF IS NULL
	BEGIN	
		IF EXISTS(SELECT 1 FROM SM WHERE NRRENDOR = @pNrRendor  AND FISKALIZUAR=1 AND ISNULL(FISEIC,'')<>'')
			BEGIN
				SET @OUTPUT1='0'
				SET @OUTPUT2='0'
			END
			ELSE
			BEGIN
						
				EXEC Isd_FiscalSM @pNrRendor,1,@OUTPUT2 OUTPUT
				IF @OUTPUT2 <> '0'
					SET @TEMPOUTPUT = ISNULL(@OUTPUT2,'') + char(10)+char(13)
				SET @OUTPUT1='0'
/*
				DECLARE @EIC VARCHAR(MAX)
				DECLARE @DATEDOK DATETIME

				SET @EIC=(SELECT FISEIC FROM SM WHERE NRRENDOR=@pNrRendor)
				SET @DATEDOK=(SELECT DATEDOK FROM SM WHERE NRRENDOR=@pNrRendor)
				IF ISNULL(@EIC,'')<>''
				EXEC __eInvoiceGetRequestStatus @EIC,'SELLER',@DATEDOK,@DATEDOK,@pNrRendor,@OUTPUT3 OUTPUT
*/
				--IF @OUTPUT3 <> '0'
				--	SET @TEMPOUTPUT = @OUTPUT3 + char(10)+char(13)


				IF @OUTPUT2 LIKE '%Einvoice with that FIC is allready received%'
				SET @OUTPUT2='0'
			END
									

	END
	ELSE
		BEGIN
				IF EXISTS(SELECT 1 FROM SM WHERE NRRENDOR = @pNrRendor 
						   AND FISLASTERRORFIC = '0'
						   AND (ISNULL(FISFIC, '') != '' AND FISKALIZUAR=1 AND ISNULL(FISRELATEDFIC,'')!=ISNULL(FISFIC, '') ) )	
					BEGIN
						SET @OUTPUT1='0'
					END
					ELSE
						BEGIN
									EXEC Isd_FiscalSM @pNrRendor,0,@OUTPUT1 OUTPUT
									--EXEC __FiscalCreateSalesXmlFJ2 @pNrRendor,@OUTPUT1 OUTPUT

									SET @OUTPUT2='0'
	
									IF ISNULL(@OUTPUT1,'') <> '0'
										SET @TEMPOUTPUT = ISNULL(@OUTPUT1,'') + char(10)+char(13)
						END
		END
		

	if  (ISNULL(@OUTPUT1,'0')='0' and ISNULL(@OUTPUT2,'0')='0')
	set @OUTMESSAGE=''
	ELSE
	set @OUTMESSAGE = 'Gabim gjate procesit te deklarimit tatime....'+char(10)+ char(13) + @TEMPOUTPUT


	select @OUTPUT1 AS KodError1,@OUTPUT2 AS KodError2,@OUTMESSAGE AS MsgError
	
END


GO
