SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CheckProductForDiscount](@kodart as varchar(50),@KMAG AS VARCHAR(50),@KODKLI AS VARCHAR(50),@SASI AS FLOAT)
AS

IF (SELECT COUNT(1) FROM GRUPEPERJASHTUAR G
		INNER JOIN ARTIKUJ A ON A.KLASIF2 = G.KOD
		WHERE A.KOD = @KODART)>=1
	BEGIN
		SELECT '0';
	END 
ELSE IF (SELECT TOP 1 CMSH FROM ARTIKUJ WHERE KOD = @KODART) <> (SELECT DBO.GETPRICE(@KODART,@KMAG,@KODKLI,@SASI))
	BEGIN
		SELECT '0';
	END
ELSE
	BEGIN
		SELECT '1';
	END
	
	
	
	
	
GO
