SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[P_ROUNDUP]
   (
    @TABELA AS VARCHAR(30),
    @KOLONA AS VARCHAR(30),
    @VLUP AS VARCHAR(30),
    @WHEREIN AS VARCHAR(4000)
   ) AS
BEGIN
DECLARE @QUERY AS NVARCHAR(4000) ;
SET @QUERY =
     ' UPDATE ['+@Tabela+'] SET ['+@KOLONA+']= DBO.F_ROUND('+@KOLONA+','+@VLUP+') '+@WHEREIN;
EXEC sp_executesql @QUERY
END

GO
