SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[Isd_GatiFiskalStatus]
(
 @pNrRendor Integer
)
AS
BEGIN
	SET NOCOUNT ON;
    
	DECLARE @EIC VARCHAR(MAX)
	DECLARE @OUTPUT3 VARCHAR(MAX)
	DECLARE @DATEDOK DATETIME

	SET @EIC=(SELECT FISEIC FROM FJ WHERE NRRENDOR=@pNrRendor)
	SET @DATEDOK=(SELECT DATEDOK FROM FJ WHERE NRRENDOR=@pNrRendor)
	EXEC __eInvoiceGetRequestStatus @EIC,'SELLER',@DATEDOK,@DATEDOK,@pNrRendor,@OUTPUT3 OUTPUT
	select @OUTPUT3 AS KodError1,KodError2='',MsgError=''
	
END
GO
