SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[VOUCHERCONSUME]
(
	@SERIAL VARCHAR(50),
	@KMAG   VARCHAR(50),
	@KKASE  VARCHAR(50),
	@USER	VARCHAR(50)
)
AS

DECLARE @DATA AS DATETIME
SET @DATA = (SELECT GETDATE());

EXEC QENDER.INVENTORY.DBO.VoucherCorrectionJournal 'RET',@SERIAL,@DATA,@DATA,@USER,'TOLLON NE SHITJE',@KKASE,@KMAG

DECLARE @A AS INT;
SET @A=1;
SELECT @A
GO
