SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO








CREATE        procedure [dbo].[UPDATE_DITARE_FF]
(
@PMODUL     AS VARCHAR(1), --'F'
@PTABLENAME AS VARCHAR(20),--'FF' rasti nga FF-ja, 'ARKA' rasti nga Arkascr,'BANKA' rastin nga Bankascr,'VS' rastin nga VSscr-ja
@PNRRENDOR  AS INT         --Nrrendori per tabelen e zgjedhur
)
AS

DECLARE @VTABLENAME AS VARCHAR(20)
DECLARE @VNRDITAR   AS VARCHAR(20)

SET @VTABLENAME=@PTABLENAME
SET @VNRDITAR  =0

IF @PMODUL='F'
  BEGIN

    --RASTI F NGA VS
    IF @PTABLENAME='VS'
      BEGIN
        SET @VNRDITAR=ISNULL((SELECT NRDITAR FROM VSSCR WHERE VSSCR.NRRENDOR=@PNRRENDOR),0)

        DELETE FROM DFU WHERE NRRENDOR=@VNRDITAR

        IF ISNULL((SELECT TOP 1 NRRENDOR FROM LFU A WHERE A.KOD=(SELECT KOD FROM VSSCR B WHERE B.NRRENDOR=@PNRRENDOR)),0)=0
          INSERT INTO LFU (KOD,PERSHKRIM,KMON,MBARTUR,MBARTURMV,GJ,GJMV,
                           SG1,SG2,SG3,SG4,SG5,SG6,SG7,SG8,SG9,SG10,TROW,TAGNR)
               SELECT      KOD=A.KOD,PERSHKRIM=A.PERSHKRIM,KMON=A.KMON,MBARTUR=0,MBARTURMV=0,GJ=0,GJMV=0,
                           SG1=A.LLOGARIPK,SG2=A.KMON,SG3='',SG4='',SG5='',SG6='',SG7='',SG8='',SG9='',SG10='',TROW=0,TAGNR=0
                 FROM VSSCR A
                WHERE A.NRRENDOR=@PNRRENDOR


        INSERT INTO DFU (NRDITAR,KOD,PERSHKRIM,KOMENT,KMON,KURS1,KURS2,
                         TIPDOK,NRDOK,FRAKSDOK,DATEDOK,VLEFTA,
                         VLEFTAMV,TREGDK,NRLIBER,
                         TIPFAT,NRFAT,DTFAT,ISDOKSHOQ,ORDERTD,KODMASTER,TROW,TAGNR)
        SELECT NRDITAR=A.NRDOK,KOD=B.KOD,PERSHKRIM=B.PERSHKRIM,KOMENT=B.KOMENT,KMON=B.KMON,KURS1=B.KURS1,KURS2=B.KURS2,
               TIPDOK='SP',NRDOK=A.NRDOK,FRAKSDOK=0,DATEDOK=A.DATEDOK,VLEFTA=(B.DB+B.KR),
               VLEFTAMV=CASE WHEN B.TREGDK='D' THEN B.DBKRMV ELSE -B.DBKRMV END,TREGDK=B.TREGDK,NRLIBER=ISNULL((SELECT TOP 1 NRRENDOR FROM LFU C WHERE C.KOD=B.KOD),0),
               TIPFAT=ISNULL(B.TIPREF,'FF'),NRFAT=ISNULL(B.NRDOKREF,'0'),DTFAT=ISNULL(B.DATEDOKREF,A.DATEDOK),ISDOKSHOQ=0,ORDERTD='',KODMASTER=B.LLOGARIPK,TROW=0,TAGNR=0
          FROM VS A INNER JOIN VSSCR B ON A.NRRENDOR=B.NRD
         WHERE B.NRRENDOR=@PNRRENDOR 
        
        SET @VNRDITAR=@@IDENTITY
        
        UPDATE VSSCR SET NRDITAR=@VNRDITAR WHERE VSSCR.NRRENDOR=@PNRRENDOR
    END 

    --RASTI F NGA ARKA
    IF @PTABLENAME='ARKA'
      BEGIN
        SET @VNRDITAR=ISNULL((SELECT NRDITAR FROM ARKASCR WHERE ARKASCR.NRRENDOR=@PNRRENDOR),0)

        DELETE FROM DFU WHERE NRRENDOR=@VNRDITAR

        IF ISNULL((SELECT TOP 1 NRRENDOR FROM LFU A WHERE A.KOD=(SELECT KOD FROM ARKASCR B WHERE B.NRRENDOR=@PNRRENDOR)),0)=0
          INSERT INTO LFU (KOD,PERSHKRIM,KMON,MBARTUR,MBARTURMV,GJ,GJMV,
                           SG1,SG2,SG3,SG4,SG5,SG6,SG7,SG8,SG9,SG10,TROW,TAGNR)
               SELECT      KOD=A.KOD,PERSHKRIM=A.PERSHKRIM,KMON=A.KMON,MBARTUR=0,MBARTURMV=0,GJ=0,GJMV=0,
                           SG1=A.LLOGARIPK,SG2=A.KMON,SG3='',SG4='',SG5='',SG6='',SG7='',SG8='',SG9='',SG10='',TROW=0,TAGNR=0
                 FROM ARKASCR A
                WHERE A.NRRENDOR=@PNRRENDOR


        INSERT INTO DFU (NRDITAR,KOD,PERSHKRIM,KOMENT,KMON,KURS1,KURS2,
                         TIPDOK,NRDOK,FRAKSDOK,DATEDOK,VLEFTA,
                         VLEFTAMV,TREGDK,NRLIBER,
                         TIPFAT,NRFAT,DTFAT,ISDOKSHOQ,ORDERTD,KODMASTER,TROW,TAGNR)
        SELECT NRDITAR=A.NUMDOK,KOD=B.KOD,PERSHKRIM=B.PERSHKRIM,KOMENT=B.KOMENT,KMON=B.KMON,KURS1=B.KURS1,KURS2=B.KURS2,
               TIPDOK=A.TIPDOK,NRDOK=A.NUMDOK,FRAKSDOK=0,DATEDOK=A.DATEDOK,VLEFTA=(B.DB+B.KR),
               VLEFTAMV=CASE WHEN B.TREGDK='D' THEN B.DBKRMV ELSE -B.DBKRMV END,TREGDK=B.TREGDK,NRLIBER=ISNULL((SELECT TOP 1 NRRENDOR FROM LFU C WHERE C.KOD=B.KOD),0),
               TIPFAT=ISNULL(B.TIPREF,'FJ'),NRFAT=ISNULL(B.NRDOKREF,'0'),DTFAT=ISNULL(B.DATEDOKREF,A.DATEDOK),ISDOKSHOQ=0,ORDERTD='',KODMASTER=A.KODAB,TROW=0,TAGNR=0
          FROM ARKA A INNER JOIN ARKASCR B ON A.NRRENDOR=B.NRD
         WHERE B.NRRENDOR=@PNRRENDOR 
        
        SET @VNRDITAR=@@IDENTITY
        
        UPDATE ARKASCR SET NRDITAR=@VNRDITAR WHERE ARKASCR.NRRENDOR=@PNRRENDOR
    END 

    --RASTI F NGA BANKA
    IF @PTABLENAME='BANKA'
      BEGIN
        SET @VNRDITAR=ISNULL((SELECT NRDITAR FROM BANKASCR WHERE BANKASCR.NRRENDOR=@PNRRENDOR),0)

        DELETE FROM DFU WHERE NRRENDOR=@VNRDITAR

        IF ISNULL((SELECT TOP 1 NRRENDOR FROM LFU A WHERE A.KOD=(SELECT KOD FROM BANKASCR B WHERE B.NRRENDOR=@PNRRENDOR)),0)=0
          INSERT INTO LFU (KOD,PERSHKRIM,KMON,MBARTUR,MBARTURMV,GJ,GJMV,
                           SG1,SG2,SG3,SG4,SG5,SG6,SG7,SG8,SG9,SG10,TROW,TAGNR)
               SELECT      KOD=A.KOD,PERSHKRIM=A.PERSHKRIM,KMON=A.KMON,MBARTUR=0,MBARTURMV=0,GJ=0,GJMV=0,
                           SG1=A.LLOGARIPK,SG2=A.KMON,SG3='',SG4='',SG5='',SG6='',SG7='',SG8='',SG9='',SG10='',TROW=0,TAGNR=0
                 FROM BANKASCR A
                WHERE A.NRRENDOR=@PNRRENDOR


        INSERT INTO DFU (NRDITAR,KOD,PERSHKRIM,KOMENT,KMON,KURS1,KURS2,
                         TIPDOK,NRDOK,FRAKSDOK,DATEDOK,VLEFTA,
                         VLEFTAMV,TREGDK,NRLIBER,
                         TIPFAT,NRFAT,DTFAT,ISDOKSHOQ,ORDERTD,KODMASTER,TROW,TAGNR)
        SELECT NRDITAR=A.NUMDOK,KOD=B.KOD,PERSHKRIM=B.PERSHKRIM,KOMENT=B.KOMENT,KMON=B.KMON,KURS1=B.KURS1,KURS2=B.KURS2,
               TIPDOK=A.TIPDOK,NRDOK=A.NUMDOK,FRAKSDOK=0,DATEDOK=A.DATEDOK,VLEFTA=(B.DB+B.KR),
               VLEFTAMV=CASE WHEN B.TREGDK='D' THEN B.DBKRMV ELSE -B.DBKRMV END,TREGDK=B.TREGDK,NRLIBER=ISNULL((SELECT TOP 1 NRRENDOR FROM LFU C WHERE C.KOD=B.KOD),0),
               TIPFAT=ISNULL(B.TIPREF,'FJ'),NRFAT=ISNULL(B.NRDOKREF,'0'),DTFAT=ISNULL(B.DATEDOKREF,A.DATEDOK),ISDOKSHOQ=0,ORDERTD='',KODMASTER=A.KODAB,TROW=0,TAGNR=0
          FROM BANKA A INNER JOIN BANKASCR B ON A.NRRENDOR=B.NRD
         WHERE B.NRRENDOR=@PNRRENDOR 
        
        SET @VNRDITAR=@@IDENTITY
        
        UPDATE BANKASCR SET NRDITAR=@VNRDITAR WHERE BANKASCR.NRRENDOR=@PNRRENDOR
    END 

    --RASTI 'F' NGA FF
    IF @PTABLENAME='FF'
      BEGIN
        SET @VNRDITAR=ISNULL((SELECT NRDITAR FROM FF WHERE FF.NRRENDOR=@PNRRENDOR),0)

        DELETE FROM DFU WHERE NRRENDOR=@VNRDITAR

        IF ISNULL((SELECT TOP 1 NRRENDOR FROM LFU A WHERE A.KOD=(SELECT KOD FROM FF B WHERE B.NRRENDOR=@PNRRENDOR)),0)=0
          INSERT INTO LFU (KOD,PERSHKRIM,KMON,MBARTUR,MBARTURMV,GJ,GJMV,
                           SG1,SG2,SG3,SG4,SG5,SG6,SG7,SG8,SG9,SG10,TROW,TAGNR)
               SELECT      KOD=A.KODFKL+'.'+A.KMON,PERSHKRIM=A.SHENIM1,KMON=A.KMON,MBARTUR=0,MBARTURMV=0,GJ=0,GJMV=0,
                           SG1=A.KODFKL,SG2=A.KMON,SG3='',SG4='',SG5='',SG6='',SG7='',SG8='',SG9='',SG10='',TROW=0,TAGNR=0
                 FROM FF A
                WHERE A.NRRENDOR=@PNRRENDOR


        INSERT INTO DFU (NRDITAR,KOD,PERSHKRIM,KOMENT,KMON,KURS1,KURS2,
                         TIPDOK,NRDOK,FRAKSDOK,DATEDOK,VLEFTA,
                         VLEFTAMV,TREGDK,NRLIBER,
                         TIPFAT,NRFAT,DTFAT,ISDOKSHOQ,ORDERTD,KODMASTER,TROW,TAGNR)
        SELECT NRDITAR=A.NRDOK,KOD=A.KODFKL+'.'+A.KMON,PERSHKRIM=A.SHENIM1,KOMENT=A.SHENIM2,KMON=A.KMON,KURS1=A.KURS1,KURS2=A.KURS2,
               TIPDOK='FF',NRDOK=A.NRDOK,FRAKSDOK=0,DATEDOK=A.DATEDOK,VLEFTA=A.VLERTOT,
               VLEFTAMV=A.VLERTOT*A.KURS2/A.KURS1,TREGDK='K',NRLIBER=ISNULL((SELECT TOP 1 NRRENDOR FROM LFU C WHERE C.KOD=A.KODFKL+'.'+A.KMON),0),
               TIPFAT='FF',NRFAT=A.NRDSHOQ,DTFAT=A.DTDSHOQ,ISDOKSHOQ=0,ORDERTD='',KODMASTER=A.KODFKL,TROW=0,TAGNR=0
          FROM FF A 
         WHERE A.NRRENDOR=@PNRRENDOR 
        
        SET @VNRDITAR=@@IDENTITY
        
        UPDATE FF SET NRDITAR=@VNRDITAR WHERE FF.NRRENDOR=@PNRRENDOR

        --Rasti i shlyerjes nga fatura pa mandat
        IF (SELECT PARAPG FROM FF WHERE FF.NRRENDOR=@PNRRENDOR)<>0 
          BEGIN
            SET @VNRDITAR=ISNULL((SELECT NRDITARSHL FROM FF WHERE FF.NRRENDOR=@PNRRENDOR),0)

            DELETE FROM DFU WHERE NRRENDOR=@VNRDITAR

            INSERT INTO DFU (NRDITAR,KOD,PERSHKRIM,KOMENT,KMON,KURS1,KURS2,
                             TIPDOK,NRDOK,FRAKSDOK,DATEDOK,VLEFTA,
                             VLEFTAMV,TREGDK,NRLIBER,
                             TIPFAT,NRFAT,DTFAT,ISDOKSHOQ,ORDERTD,KODMASTER,TROW,TAGNR)
            SELECT NRDITAR=A.NRDOK,KOD=A.KODFKL+'.'+A.KMON,PERSHKRIM=A.SHENIM1,KOMENT=A.SHENIM2+'/Shlyerje FF',KMON=A.KMON,KURS1=A.KURS1,KURS2=A.KURS2,
                   TIPDOK='FF',NRDOK=A.NRDOK,FRAKSDOK=0,DATEDOK=A.DATEDOK,VLEFTA=A.PARAPG,
                   VLEFTAMV=A.PARAPG*A.KURS2/A.KURS1,TREGDK='D',NRLIBER=ISNULL((SELECT TOP 1 NRRENDOR FROM LFU C WHERE C.KOD=A.KODFKL+'.'+A.KMON),0),
                   TIPFAT='FF',NRFAT=A.NRDSHOQ,DTFAT=A.DTDSHOQ,ISDOKSHOQ=0,ORDERTD='',KODMASTER=A.KODFKL,TROW=0,TAGNR=0
              FROM FF A 
             WHERE A.NRRENDOR=@PNRRENDOR 
        
            SET @VNRDITAR=@@IDENTITY
        
            UPDATE FF SET NRDITARSHL=@VNRDITAR WHERE FF.NRRENDOR=@PNRRENDOR
        END

    END 



END

--FUND MODULI FURNITOR









GO
