SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

create PROCEDURE [dbo].[P_ARTIKUJ_SELECT_FILTER] ( @MULTI_BC AS VARCHAR(20)) AS
IF @MULTI_BC='0'
BEGIN
SELECT
      A.KOD,A.BC,A.PERSHKRIM,A.CMSH AS CMIMI
      /*,A.CMSH1,A.CMSH2,A.CMSH3,A.CMSH4,A.CMSH5,A.CMSH6,A.CMSH7,A.CMSH8,A.CMSH9,
      A.KLASIF,A.KLASIF2,A.KLASIF3,A.KLASIF4,A.KLASIF5,A.KLASIF6*/ FROM ARTIKUJ a
END ELSE
SELECT
      A.KOD,ABC.BC,ISNULL(ABC.PERSHKRIM,A.PERSHKRIM) AS PERSHKRIM,A.CMSH AS CMIMI
      /*,A.CMSH1,A.CMSH2,A.CMSH3,A.CMSH4,A.CMSH5,A.CMSH6,A.CMSH7,A.CMSH8,A.CMSH9,
      A.KLASIF,A.KLASIF2,A.KLASIF3,A.KLASIF4,A.KLASIF5,A.KLASIF6*/ FROM ARTIKUJ a
      INNER JOIN ARTIKUJBCSCR ABC ON ABC.NRD=A.NRRENDOR

--P_SELECT_ARTIKUJ_FILTER '0'

GO
