SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




create procedure [dbo].[MG_CMIMMG]
(
@PMAG VARCHAR(5),
@PKOD VARCHAR(50)
)
AS

SELECT SA=SUM(SASI),VL=SUM(VLERE), 
       CM=CASE WHEN SUM(SASI)*SUM(VLERE)>0 THEN ROUND(SUM(VLERE)/SUM(SASI),3) ELSE MAX(ARTIKUJ.KOSTMES) END 
FROM ARTIKUJ LEFT JOIN LMG ON ARTIKUJ.KOD=LMG.SG2
WHERE (ARTIKUJ.KOD=@PKOD) AND (LMG.SG1=@PMAG)

GO
