SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [dbo].[VW_EXPIRATIONITEMS]
(@EXPDTFROM AS DATETIME,@EXPDTTO AS DATETIME,
@mnga as varchar(50),@mderi as varchar(50))
AS

if @mnga = ''
set @mnga = '0'
if @mderi = ''
set @mderi = 'ZZ'

SELECT  FURNITORKOD = A.FURNKOD,
		FURNITORPERSH = MIN(FUR.PERSHKRIM),
		KOD = FS.KARTLLG,
		BC=MIN(A.bc),
		PERSHKRIM = MIN(FS.PERSHKRIM),
		DATESKADENCE = FS.DTSKADENCE,
		DNGA = @EXPDTFROM,
		DDERI = @EXPDTTO,
		MNGA = @mnga,
		MDERI = @mderi
FROM FF F
INNER JOIN FFSCR FS ON FS.NRD = F.NRRENDOR
INNER JOIN ARTIKUJ A ON A.KOD = FS.KARTLLG
INNER JOIN FURNITOR FUR ON FUR.KOD = A.FURNKOD
WHERE ISNULL(A.NOTACTIV,0)= 0  
AND FS.DTSKADENCE >=@EXPDTFROM AND FS.DTSKADENCE<=@EXPDTTO
and KMAG >=@mnga and KMAG <= @mderi
GROUP BY A.FURNKOD,FS.DTSKADENCE,FS.KARTLLG
GO
