SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


create PROC [dbo].[VW_0SHITJE_TOP_ARTIKUJ]
(@DNGA AS DATETIME,@DDERI AS DATETIME,
 @FNGA AS VARCHAR(50),@FDERI AS VARCHAR(50),
 @KLASIFNGA AS VARCHAR(50),@KLASIFDERI AS VARCHAR(50),
 @KLS AS VARCHAR(50)
)
AS

CREATE TABLE #T(
	KOD varchar(50) NULL,
	CMB float NULL,
	CMSH float NULL)
CREATE NONCLUSTERED INDEX IX_T ON #T 
(
	KOD ASC
)


INSERT INTO #T(KOD,CMB,CMSH) 
SELECT KOD, (SELECT TOP 1 CMIMB= CASE WHEN SASI=0 THEN CMIMM ELSE VLERABS/SASI END FROM FFSCR 
INNER JOIN FF ON FF.NRRENDOR= FFSCR.NRD
WHERE FF.DATEDOK<=@DDERI AND FFSCR.KARTLLG = ARTIKUJ.Kod
ORDER BY FF.DATEDOK DESC)
AS CMB, (SELECT TOP 1 CMIMSH= CASE WHEN SASI=0 THEN CMIMM ELSE VLERABS/SASI END FROM FJSCR 
INNER JOIN FJ ON FJ.NRRENDOR= FJSCR.NRD
WHERE FJ.DATEDOK<=@DDERI AND FJSCR.KARTLLG = ARTIKUJ.Kod
ORDER BY FJ.DATEDOK DESC)
AS CMSH FROM ARTIKUJ


SELECT  TOP 10
		A.KOD,
		PERSHKRIM = MIN(A.PERSHKRIM),
		VLERA = CASE WHEN @KLS = 'SASI' THEN SUM(SASI)
				     WHEN @KLS = 'VLERE' THEN SUM(VLERTOT)
				     WHEN @KLS = 'MARZH' THEN SUM((#T.CMSH-#T.CMB)*SASI) 
				     ELSE 0 END,
		@DNGA AS DATANGA, 
		@DDERI AS DATADERI,
		@KLASIFNGA AS KLASIFNGA,
		@KLASIFDERI AS KLASIFDERI,
		@KLS AS KLS
FROM	SM S
INNER JOIN SMSCR SC ON SC.NRD = S.NRRENDOR
INNER JOIN ARTIKUJ A ON A.KOD = SC.KARTLLG
INNER JOIN FURNITOR F ON F.KOD = A.KLASIF--<--
--KUJDES ME LART DUHET FUSHA KU ESHTE MBUSHUR KODI I FURNITORIT
INNER JOIN #T ON #T.KOD = A.KOD
WHERE S.DATEDOK>=@DNGA AND S.DATEDOK<=@DDERI AND 
	  A.KLASIF2 >=@KLASIFNGA AND A.KLASIF2 <= @KLASIFDERI AND
	  A.KLASIF  >=@FNGA		 AND A.KLASIF  <= @FDERI--< KUJDES DUHET VENDOSUR KLASIFIKATORI I FURNITORIT
	  
	  
GROUP BY A..KOD
ORDER BY CASE WHEN @KLS = 'SASI' THEN SUM(SASI)
				     WHEN @KLS = 'VLERE' THEN SUM(VLERTOT)
				     WHEN @KLS = 'MARZH' THEN SUM((#T.CMSH-#T.CMB)*SASI) 
				     ELSE 0 END DESC
GO
