SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create PROCEDURE [dbo].[P_EKSPORT_NE_FINANCE](@UserComp AS VARCHAR(30)) as
UPDATE A  SET
    A.PERSHKRIM=B.PERSHKRIM,
    A.KLASIF=B.KLASIF,
    A.CMSH=B.CMSH,
    A.CMSH1=B.CMSH1,
    A.CMSH2=B.CMSH2,
    A.CMSH3=B.CMSH3,
    A.CMSH4=B.CMSH4,
    A.CMSH5=B.CMSH5,
    A.CMSH6=B.CMSH6,
    A.CMSH7=B.CMSH7,
    A.CMSH8=B.CMSH8,
    A.CMSH9=B.CMSH9,
    A.BC=B.BC,
    A.KLASIF2=B.KLASIF2,
    A.KLASIF3=B.KLASIF3,
    A.KLASIF4=B.KLASIF4,
    A.KLASIF5=B.KLASIF5,
    A.KLASIF6=B.KLASIF6,
    A.NOTACTIV=B.NOTACTIV,
    A.TATIM=B.TATIM
   FROM ARTIKUJ A INNER JOIN ARTIKUJCMAD B ON A.KOD=B.KOD
   WHERE ISNULL(B.UPDATED,0)=1 and ISNULL(B.USERN,'')=@UserComp;

GO
