SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[_FISKALIZIMAUTOMATIK] 
AS
DECLARE @NR AS INT

DECLARE CU CURSOR FOR 
SELECT NRRENDOR FROM SM 
WHERE ISNULL(FIC,'')=''

OPEN CU
FETCH NEXT FROM CU INTO @NR 
WHILE @@FETCH_STATUS=0
BEGIN
EXEC DBO._FiscalReportSaleXmlPOS @NR
FETCH NEXT FROM CU INTO @NR 
END
CLOSE CU
DEALLOCATE CU
GO
