SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO





CREATE      procedure [dbo].[UPDATE_DITARE]
(
@PMODUL     AS VARCHAR(1),
@PTABLENAME AS VARCHAR(20),
@PNRRENDOR  AS INT
)
AS

DECLARE @VTABLENAME AS VARCHAR(20)
DECLARE @VNRDITAR   AS VARCHAR(20)

SET @VTABLENAME=@PTABLENAME
SET @VNRDITAR  =0

IF @PMODUL='S'
  BEGIN
    --RASTI 'S' NGA VS
    IF @PTABLENAME='VS'
      BEGIN
        SET @VNRDITAR=ISNULL((SELECT NRDITAR FROM VSSCR WHERE VSSCR.NRRENDOR=@PNRRENDOR),0)

        DELETE FROM DKL WHERE NRRENDOR=@VNRDITAR

        IF ISNULL((SELECT NRRENDOR FROM LKL A WHERE A.KOD=(SELECT KOD FROM VSSCR B WHERE B.NRRENDOR=@PNRRENDOR)),0)=0
          INSERT INTO LKL (KOD,PERSHKRIM,KMON,MBARTUR,MBARTURMV,GJ,GJMV,
                           SG1,SG2,SG3,SG4,SG5,SG6,SG7,SG8,SG9,SG10,TROW,TAGNR)
               SELECT      KOD=A.KOD,PERSHKRIM=A.PERSHKRIM,KMON=A.KMON,MBARTUR=0,MBARTURMV=0,GJ=0,GJMV=0,
                           SG1=A.LLOGARIPK,SG2=A.KMON,SG3='',SG4='',SG5='',SG6='',SG7='',SG8='',SG9='',SG10='',TROW=0,TAGNR=0
                 FROM VSSCR A
                WHERE A.NRRENDOR=@PNRRENDOR


        INSERT INTO DKL (NRDITAR,KOD,PERSHKRIM,KOMENT,KMON,KURS1,KURS2,
                         TIPDOK,NRDOK,FRAKSDOK,DATEDOK,VLEFTA,
                         VLEFTAMV,TREGDK,NRLIBER,
                         TIPFAT,NRFAT,DTFAT,ISDOKSHOQ,ORDERTD,KODMASTER,TROW,TAGNR)
        SELECT NRDITAR=A.NRDOK,KOD=B.KOD,PERSHKRIM=B.PERSHKRIM,KOMENT=B.KOMENT,KMON=B.KMON,KURS1=B.KURS1,KURS2=B.KURS2,
               TIPDOK='SP',NRDOK=A.NRDOK,FRAKSDOK=0,DATEDOK=A.DATEDOK,VLEFTA=(B.DB+B.KR),
               VLEFTAMV=CASE WHEN B.TREGDK='D' THEN B.DBKRMV ELSE -B.DBKRMV END,TREGDK=B.TREGDK,NRLIBER=ISNULL((SELECT NRRENDOR FROM LKL C WHERE C.KOD=B.KOD),0),
               TIPFAT=ISNULL(B.TIPREF,'FJ'),NRFAT=ISNULL(B.NRDOKREF,'0'),DTFAT=ISNULL(B.DATEDOKREF,A.DATEDOK),ISDOKSHOQ=0,ORDERTD='',KODMASTER=B.LLOGARIPK,TROW=0,TAGNR=0
          FROM VS A INNER JOIN VSSCR B ON A.NRRENDOR=B.NRD
         WHERE B.NRRENDOR=@PNRRENDOR 
        
        SET @VNRDITAR=@@IDENTITY
        
        UPDATE VSSCR SET NRDITAR=@VNRDITAR WHERE VSSCR.NRRENDOR=@PNRRENDOR
    END 

    --RASTI 'S' NGA ARKA
    IF @PTABLENAME='ARKA'
      BEGIN
        SET @VNRDITAR=ISNULL((SELECT NRDITAR FROM ARKASCR WHERE ARKASCR.NRRENDOR=@PNRRENDOR),0)

        DELETE FROM DKL WHERE NRRENDOR=@VNRDITAR

        IF ISNULL((SELECT NRRENDOR FROM LKL A WHERE A.KOD=(SELECT KOD FROM ARKASCR B WHERE B.NRRENDOR=@PNRRENDOR)),0)=0
          INSERT INTO LKL (KOD,PERSHKRIM,KMON,MBARTUR,MBARTURMV,GJ,GJMV,
                           SG1,SG2,SG3,SG4,SG5,SG6,SG7,SG8,SG9,SG10,TROW,TAGNR)
               SELECT      KOD=A.KOD,PERSHKRIM=A.PERSHKRIM,KMON=A.KMON,MBARTUR=0,MBARTURMV=0,GJ=0,GJMV=0,
                           SG1=A.LLOGARIPK,SG2=A.KMON,SG3='',SG4='',SG5='',SG6='',SG7='',SG8='',SG9='',SG10='',TROW=0,TAGNR=0
                 FROM ARKASCR A
                WHERE A.NRRENDOR=@PNRRENDOR


        INSERT INTO DKL (NRDITAR,KOD,PERSHKRIM,KOMENT,KMON,KURS1,KURS2,
                         TIPDOK,NRDOK,FRAKSDOK,DATEDOK,VLEFTA,
                         VLEFTAMV,TREGDK,NRLIBER,
                         TIPFAT,NRFAT,DTFAT,ISDOKSHOQ,ORDERTD,KODMASTER,TROW,TAGNR)
        SELECT NRDITAR=A.NUMDOK,KOD=B.KOD,PERSHKRIM=B.PERSHKRIM,KOMENT=B.KOMENT,KMON=B.KMON,KURS1=B.KURS1,KURS2=B.KURS2,
               TIPDOK=A.TIPDOK,NRDOK=A.NUMDOK,FRAKSDOK=0,DATEDOK=A.DATEDOK,VLEFTA=(B.DB+B.KR),
               VLEFTAMV=CASE WHEN B.TREGDK='D' THEN B.DBKRMV ELSE -B.DBKRMV END,TREGDK=B.TREGDK,NRLIBER=ISNULL((SELECT NRRENDOR FROM LKL C WHERE C.KOD=B.KOD),0),
               TIPFAT=ISNULL(B.TIPREF,'FJ'),NRFAT=ISNULL(B.NRDOKREF,'0'),DTFAT=ISNULL(B.DATEDOKREF,A.DATEDOK),ISDOKSHOQ=0,ORDERTD='',KODMASTER=A.KODAB,TROW=0,TAGNR=0
          FROM ARKA A INNER JOIN ARKASCR B ON A.NRRENDOR=B.NRD
         WHERE B.NRRENDOR=@PNRRENDOR 
        
        SET @VNRDITAR=@@IDENTITY
        
        UPDATE ARKASCR SET NRDITAR=@VNRDITAR WHERE ARKASCR.NRRENDOR=@PNRRENDOR
    END 

    --RASTI 'S' NGA BANKA
    IF @PTABLENAME='BANKA'
      BEGIN
        SET @VNRDITAR=ISNULL((SELECT NRDITAR FROM BANKASCR WHERE BANKASCR.NRRENDOR=@PNRRENDOR),0)

        DELETE FROM DKL WHERE NRRENDOR=@VNRDITAR

        IF ISNULL((SELECT NRRENDOR FROM LKL A WHERE A.KOD=(SELECT KOD FROM BANKASCR B WHERE B.NRRENDOR=@PNRRENDOR)),0)=0
          INSERT INTO LKL (KOD,PERSHKRIM,KMON,MBARTUR,MBARTURMV,GJ,GJMV,
                           SG1,SG2,SG3,SG4,SG5,SG6,SG7,SG8,SG9,SG10,TROW,TAGNR)
               SELECT      KOD=A.KOD,PERSHKRIM=A.PERSHKRIM,KMON=A.KMON,MBARTUR=0,MBARTURMV=0,GJ=0,GJMV=0,
                           SG1=A.LLOGARIPK,SG2=A.KMON,SG3='',SG4='',SG5='',SG6='',SG7='',SG8='',SG9='',SG10='',TROW=0,TAGNR=0
                 FROM BANKASCR A
                WHERE A.NRRENDOR=@PNRRENDOR


        INSERT INTO DKL (NRDITAR,KOD,PERSHKRIM,KOMENT,KMON,KURS1,KURS2,
                         TIPDOK,NRDOK,FRAKSDOK,DATEDOK,VLEFTA,
                         VLEFTAMV,TREGDK,NRLIBER,
                         TIPFAT,NRFAT,DTFAT,ISDOKSHOQ,ORDERTD,KODMASTER,TROW,TAGNR)
        SELECT NRDITAR=A.NUMDOK,KOD=B.KOD,PERSHKRIM=B.PERSHKRIM,KOMENT=B.KOMENT,KMON=B.KMON,KURS1=B.KURS1,KURS2=B.KURS2,
               TIPDOK=A.TIPDOK,NRDOK=A.NUMDOK,FRAKSDOK=0,DATEDOK=A.DATEDOK,VLEFTA=(B.DB+B.KR),
               VLEFTAMV=CASE WHEN B.TREGDK='D' THEN B.DBKRMV ELSE -B.DBKRMV END,TREGDK=B.TREGDK,NRLIBER=ISNULL((SELECT NRRENDOR FROM LKL C WHERE C.KOD=B.KOD),0),
               TIPFAT=ISNULL(B.TIPREF,'FJ'),NRFAT=ISNULL(B.NRDOKREF,'0'),DTFAT=ISNULL(B.DATEDOKREF,A.DATEDOK),ISDOKSHOQ=0,ORDERTD='',KODMASTER=A.KODAB,TROW=0,TAGNR=0
          FROM BANKA A INNER JOIN BANKASCR B ON A.NRRENDOR=B.NRD
         WHERE B.NRRENDOR=@PNRRENDOR 
        
        SET @VNRDITAR=@@IDENTITY
        
        UPDATE BANKASCR SET NRDITAR=@VNRDITAR WHERE BANKASCR.NRRENDOR=@PNRRENDOR
    END 

    --RASTI 'S' NGA FJ
    IF @PTABLENAME='FJ'
      BEGIN
        SET @VNRDITAR=ISNULL((SELECT NRDITAR FROM FJ WHERE FJ.NRRENDOR=@PNRRENDOR),0)

        DELETE FROM DKL WHERE NRRENDOR=@VNRDITAR

        IF ISNULL((SELECT NRRENDOR FROM LKL A WHERE A.KOD=(SELECT KOD FROM FJ B WHERE B.NRRENDOR=@PNRRENDOR)),0)=0
          INSERT INTO LKL (KOD,PERSHKRIM,KMON,MBARTUR,MBARTURMV,GJ,GJMV,
                           SG1,SG2,SG3,SG4,SG5,SG6,SG7,SG8,SG9,SG10,TROW,TAGNR)
               SELECT      KOD=A.KODFKL+'.'+A.KMON,PERSHKRIM=A.SHENIM1,KMON=A.KMON,MBARTUR=0,MBARTURMV=0,GJ=0,GJMV=0,
                           SG1=A.KODFKL,SG2=A.KMON,SG3='',SG4='',SG5='',SG6='',SG7='',SG8='',SG9='',SG10='',TROW=0,TAGNR=0
                 FROM FJ A
                WHERE A.NRRENDOR=@PNRRENDOR


        INSERT INTO DKL (NRDITAR,KOD,PERSHKRIM,KOMENT,KMON,KURS1,KURS2,
                         TIPDOK,NRDOK,FRAKSDOK,DATEDOK,VLEFTA,
                         VLEFTAMV,TREGDK,NRLIBER,
                         TIPFAT,NRFAT,DTFAT,ISDOKSHOQ,ORDERTD,KODMASTER,TROW,TAGNR)
        SELECT NRDITAR=A.NRDOK,KOD=A.KODFKL+'.'+A.KMON,PERSHKRIM=A.SHENIM1,KOMENT=A.SHENIM2,KMON=A.KMON,KURS1=A.KURS1,KURS2=A.KURS2,
               TIPDOK='FJ',NRDOK=A.NRDOK,FRAKSDOK=0,DATEDOK=A.DATEDOK,VLEFTA=A.VLERTOT,
               VLEFTAMV=A.VLERTOT*A.KURS2/A.KURS1,TREGDK='D',NRLIBER=ISNULL((SELECT NRRENDOR FROM LKL C WHERE C.KOD=A.KODFKL+'.'+A.KMON),0),
               TIPFAT='FJ',NRFAT=A.NRDSHOQ,DTFAT=A.DTDSHOQ,ISDOKSHOQ=ISNULL(A.ISDOKSHOQ,0),ORDERTD='',KODMASTER=A.KODFKL,TROW=0,TAGNR=0
          FROM FJ A 
         WHERE A.NRRENDOR=@PNRRENDOR 
        
        SET @VNRDITAR=@@IDENTITY
        
        UPDATE FJ SET NRDITAR=@VNRDITAR WHERE FJ.NRRENDOR=@PNRRENDOR

        --Rasti i shlyerjes nga fatura pa mandat
        IF (SELECT PARAPG FROM FJ WHERE FJ.NRRENDOR=@PNRRENDOR)<>0 AND (SELECT ISNULL(MANDATFROMFJ,0) FROM CONFIGMG)=0
          BEGIN
            SET @VNRDITAR=ISNULL((SELECT NRDITARSHL FROM FJ WHERE FJ.NRRENDOR=@PNRRENDOR),0)

            DELETE FROM DKL WHERE NRRENDOR=@VNRDITAR

            INSERT INTO DKL (NRDITAR,KOD,PERSHKRIM,KOMENT,KMON,KURS1,KURS2,
                             TIPDOK,NRDOK,FRAKSDOK,DATEDOK,VLEFTA,
                             VLEFTAMV,TREGDK,NRLIBER,
                             TIPFAT,NRFAT,DTFAT,ISDOKSHOQ,ORDERTD,KODMASTER,TROW,TAGNR)
            SELECT NRDITAR=A.NRDOK,KOD=A.KODFKL+'.'+A.KMON,PERSHKRIM=A.SHENIM1,KOMENT=A.SHENIM2+'/Shlyerje FJ',KMON=A.KMON,KURS1=A.KURS1,KURS2=A.KURS2,
                   TIPDOK='FJ',NRDOK=A.NRDOK,FRAKSDOK=0,DATEDOK=A.DATEDOK,VLEFTA=A.PARAPG,
                   VLEFTAMV=A.PARAPG*A.KURS2/A.KURS1,TREGDK='K',NRLIBER=ISNULL((SELECT NRRENDOR FROM LKL C WHERE C.KOD=A.KODFKL+'.'+A.KMON),0),
                   TIPFAT='FJ',NRFAT=A.NRDSHOQ,DTFAT=A.DTDSHOQ,ISDOKSHOQ=ISNULL(A.ISDOKSHOQ,0),ORDERTD='',KODMASTER=A.KODFKL,TROW=0,TAGNR=0
              FROM FJ A 
             WHERE A.NRRENDOR=@PNRRENDOR 
        
            SET @VNRDITAR=@@IDENTITY
        
            UPDATE FJ SET NRDITARSHL=@VNRDITAR WHERE FJ.NRRENDOR=@PNRRENDOR
        END

    END 



END

--FUND MODULI SHITJE

ELSE
IF @PMODUL='F'
  BEGIN

    --RASTI F NGA VS
    IF @PTABLENAME='VS'
      BEGIN
        SET @VNRDITAR=ISNULL((SELECT NRDITAR FROM VSSCR WHERE VSSCR.NRRENDOR=@PNRRENDOR),0)

        DELETE FROM DFU WHERE NRRENDOR=@VNRDITAR

        IF ISNULL((SELECT NRRENDOR FROM LFU A WHERE A.KOD=(SELECT KOD FROM VSSCR B WHERE B.NRRENDOR=@PNRRENDOR)),0)=0
          INSERT INTO LFU (KOD,PERSHKRIM,KMON,MBARTUR,MBARTURMV,GJ,GJMV,
                           SG1,SG2,SG3,SG4,SG5,SG6,SG7,SG8,SG9,SG10,TROW,TAGNR)
               SELECT      KOD=A.KOD,PERSHKRIM=A.PERSHKRIM,KMON=A.KMON,MBARTUR=0,MBARTURMV=0,GJ=0,GJMV=0,
                           SG1=A.LLOGARIPK,SG2=A.KMON,SG3='',SG4='',SG5='',SG6='',SG7='',SG8='',SG9='',SG10='',TROW=0,TAGNR=0
                 FROM VSSCR A
                WHERE A.NRRENDOR=@PNRRENDOR


        INSERT INTO DFU (NRDITAR,KOD,PERSHKRIM,KOMENT,KMON,KURS1,KURS2,
                         TIPDOK,NRDOK,FRAKSDOK,DATEDOK,VLEFTA,
                         VLEFTAMV,TREGDK,NRLIBER,
                         TIPFAT,NRFAT,DTFAT,ISDOKSHOQ,ORDERTD,KODMASTER,TROW,TAGNR)
        SELECT NRDITAR=A.NRDOK,KOD=B.KOD,PERSHKRIM=B.PERSHKRIM,KOMENT=B.KOMENT,KMON=B.KMON,KURS1=B.KURS1,KURS2=B.KURS2,
               TIPDOK='SP',NRDOK=A.NRDOK,FRAKSDOK=0,DATEDOK=A.DATEDOK,VLEFTA=(B.DB+B.KR),
               VLEFTAMV=CASE WHEN B.TREGDK='D' THEN B.DBKRMV ELSE -B.DBKRMV END,TREGDK=B.TREGDK,NRLIBER=ISNULL((SELECT NRRENDOR FROM LFU C WHERE C.KOD=B.KOD),0),
               TIPFAT=ISNULL(B.TIPREF,'FF'),NRFAT=ISNULL(B.NRDOKREF,'0'),DTFAT=ISNULL(B.DATEDOKREF,A.DATEDOK),ISDOKSHOQ=0,ORDERTD='',KODMASTER=B.LLOGARIPK,TROW=0,TAGNR=0
          FROM VS A INNER JOIN VSSCR B ON A.NRRENDOR=B.NRD
         WHERE B.NRRENDOR=@PNRRENDOR 
        
        SET @VNRDITAR=@@IDENTITY
        
        UPDATE VSSCR SET NRDITAR=@VNRDITAR WHERE VSSCR.NRRENDOR=@PNRRENDOR
    END 

    --RASTI F NGA ARKA
    IF @PTABLENAME='ARKA'
      BEGIN
        SET @VNRDITAR=ISNULL((SELECT NRDITAR FROM ARKASCR WHERE ARKASCR.NRRENDOR=@PNRRENDOR),0)

        DELETE FROM DFU WHERE NRRENDOR=@VNRDITAR

        IF ISNULL((SELECT NRRENDOR FROM LFU A WHERE A.KOD=(SELECT KOD FROM ARKASCR B WHERE B.NRRENDOR=@PNRRENDOR)),0)=0
          INSERT INTO LFU (KOD,PERSHKRIM,KMON,MBARTUR,MBARTURMV,GJ,GJMV,
                           SG1,SG2,SG3,SG4,SG5,SG6,SG7,SG8,SG9,SG10,TROW,TAGNR)
               SELECT      KOD=A.KOD,PERSHKRIM=A.PERSHKRIM,KMON=A.KMON,MBARTUR=0,MBARTURMV=0,GJ=0,GJMV=0,
                           SG1=A.LLOGARIPK,SG2=A.KMON,SG3='',SG4='',SG5='',SG6='',SG7='',SG8='',SG9='',SG10='',TROW=0,TAGNR=0
                 FROM ARKASCR A
                WHERE A.NRRENDOR=@PNRRENDOR


        INSERT INTO DFU (NRDITAR,KOD,PERSHKRIM,KOMENT,KMON,KURS1,KURS2,
                         TIPDOK,NRDOK,FRAKSDOK,DATEDOK,VLEFTA,
                         VLEFTAMV,TREGDK,NRLIBER,
                         TIPFAT,NRFAT,DTFAT,ISDOKSHOQ,ORDERTD,KODMASTER,TROW,TAGNR)
        SELECT NRDITAR=A.NUMDOK,KOD=B.KOD,PERSHKRIM=B.PERSHKRIM,KOMENT=B.KOMENT,KMON=B.KMON,KURS1=B.KURS1,KURS2=B.KURS2,
               TIPDOK=A.TIPDOK,NRDOK=A.NUMDOK,FRAKSDOK=0,DATEDOK=A.DATEDOK,VLEFTA=(B.DB+B.KR),
               VLEFTAMV=CASE WHEN B.TREGDK='D' THEN B.DBKRMV ELSE -B.DBKRMV END,TREGDK=B.TREGDK,NRLIBER=ISNULL((SELECT NRRENDOR FROM LFU C WHERE C.KOD=B.KOD),0),
               TIPFAT=ISNULL(B.TIPREF,'FJ'),NRFAT=ISNULL(B.NRDOKREF,'0'),DTFAT=ISNULL(B.DATEDOKREF,A.DATEDOK),ISDOKSHOQ=0,ORDERTD='',KODMASTER=A.KODAB,TROW=0,TAGNR=0
          FROM ARKA A INNER JOIN ARKASCR B ON A.NRRENDOR=B.NRD
         WHERE B.NRRENDOR=@PNRRENDOR 
        
        SET @VNRDITAR=@@IDENTITY
        
        UPDATE ARKASCR SET NRDITAR=@VNRDITAR WHERE ARKASCR.NRRENDOR=@PNRRENDOR
    END 

    --RASTI F NGA BANKA
    IF @PTABLENAME='BANKA'
      BEGIN
        SET @VNRDITAR=ISNULL((SELECT NRDITAR FROM BANKASCR WHERE BANKASCR.NRRENDOR=@PNRRENDOR),0)

        DELETE FROM DFU WHERE NRRENDOR=@VNRDITAR

        IF ISNULL((SELECT NRRENDOR FROM LFU A WHERE A.KOD=(SELECT KOD FROM BANKASCR B WHERE B.NRRENDOR=@PNRRENDOR)),0)=0
          INSERT INTO LFU (KOD,PERSHKRIM,KMON,MBARTUR,MBARTURMV,GJ,GJMV,
                           SG1,SG2,SG3,SG4,SG5,SG6,SG7,SG8,SG9,SG10,TROW,TAGNR)
               SELECT      KOD=A.KOD,PERSHKRIM=A.PERSHKRIM,KMON=A.KMON,MBARTUR=0,MBARTURMV=0,GJ=0,GJMV=0,
                           SG1=A.LLOGARIPK,SG2=A.KMON,SG3='',SG4='',SG5='',SG6='',SG7='',SG8='',SG9='',SG10='',TROW=0,TAGNR=0
                 FROM BANKASCR A
                WHERE A.NRRENDOR=@PNRRENDOR


        INSERT INTO DFU (NRDITAR,KOD,PERSHKRIM,KOMENT,KMON,KURS1,KURS2,
                         TIPDOK,NRDOK,FRAKSDOK,DATEDOK,VLEFTA,
                         VLEFTAMV,TREGDK,NRLIBER,
                         TIPFAT,NRFAT,DTFAT,ISDOKSHOQ,ORDERTD,KODMASTER,TROW,TAGNR)
        SELECT NRDITAR=A.NUMDOK,KOD=B.KOD,PERSHKRIM=B.PERSHKRIM,KOMENT=B.KOMENT,KMON=B.KMON,KURS1=B.KURS1,KURS2=B.KURS2,
               TIPDOK=A.TIPDOK,NRDOK=A.NUMDOK,FRAKSDOK=0,DATEDOK=A.DATEDOK,VLEFTA=(B.DB+B.KR),
               VLEFTAMV=CASE WHEN B.TREGDK='D' THEN B.DBKRMV ELSE -B.DBKRMV END,TREGDK=B.TREGDK,NRLIBER=ISNULL((SELECT NRRENDOR FROM LFU C WHERE C.KOD=B.KOD),0),
               TIPFAT=ISNULL(B.TIPREF,'FJ'),NRFAT=ISNULL(B.NRDOKREF,'0'),DTFAT=ISNULL(B.DATEDOKREF,A.DATEDOK),ISDOKSHOQ=0,ORDERTD='',KODMASTER=A.KODAB,TROW=0,TAGNR=0
          FROM BANKA A INNER JOIN BANKASCR B ON A.NRRENDOR=B.NRD
         WHERE B.NRRENDOR=@PNRRENDOR 
        
        SET @VNRDITAR=@@IDENTITY
        
        UPDATE BANKASCR SET NRDITAR=@VNRDITAR WHERE BANKASCR.NRRENDOR=@PNRRENDOR
    END 

    --RASTI 'F' NGA FF
    IF @PTABLENAME='FF'
      BEGIN
        SET @VNRDITAR=ISNULL((SELECT NRDITAR FROM FF WHERE FF.NRRENDOR=@PNRRENDOR),0)

        DELETE FROM DFU WHERE NRRENDOR=@VNRDITAR

        IF ISNULL((SELECT NRRENDOR FROM LFU A WHERE A.KOD=(SELECT KOD FROM FF B WHERE B.NRRENDOR=@PNRRENDOR)),0)=0
          INSERT INTO LFU (KOD,PERSHKRIM,KMON,MBARTUR,MBARTURMV,GJ,GJMV,
                           SG1,SG2,SG3,SG4,SG5,SG6,SG7,SG8,SG9,SG10,TROW,TAGNR)
               SELECT      KOD=A.KODFKL+'.'+A.KMON,PERSHKRIM=A.SHENIM1,KMON=A.KMON,MBARTUR=0,MBARTURMV=0,GJ=0,GJMV=0,
                           SG1=A.KODFKL,SG2=A.KMON,SG3='',SG4='',SG5='',SG6='',SG7='',SG8='',SG9='',SG10='',TROW=0,TAGNR=0
                 FROM FF A
                WHERE A.NRRENDOR=@PNRRENDOR


        INSERT INTO DFU (NRDITAR,KOD,PERSHKRIM,KOMENT,KMON,KURS1,KURS2,
                         TIPDOK,NRDOK,FRAKSDOK,DATEDOK,VLEFTA,
                         VLEFTAMV,TREGDK,NRLIBER,
                         TIPFAT,NRFAT,DTFAT,ISDOKSHOQ,ORDERTD,KODMASTER,TROW,TAGNR)
        SELECT NRDITAR=A.NRDOK,KOD=A.KODFKL+'.'+A.KMON,PERSHKRIM=A.SHENIM1,KOMENT=A.SHENIM2,KMON=A.KMON,KURS1=A.KURS1,KURS2=A.KURS2,
               TIPDOK='FF',NRDOK=A.NRDOK,FRAKSDOK=0,DATEDOK=A.DATEDOK,VLEFTA=A.VLERTOT,
               VLEFTAMV=A.VLERTOT*A.KURS2/A.KURS1,TREGDK='K',NRLIBER=ISNULL((SELECT NRRENDOR FROM LFU C WHERE C.KOD=A.KODFKL+'.'+A.KMON),0),
               TIPFAT='FF',NRFAT=A.NRDSHOQ,DTFAT=A.DTDSHOQ,ISDOKSHOQ=0,ORDERTD='',KODMASTER=A.KODFKL,TROW=0,TAGNR=0
          FROM FF A 
         WHERE A.NRRENDOR=@PNRRENDOR 
        
        SET @VNRDITAR=@@IDENTITY
        
        UPDATE FF SET NRDITAR=@VNRDITAR WHERE FF.NRRENDOR=@PNRRENDOR

        --Rasti i shlyerjes nga fatura pa mandat
        IF (SELECT PARAPG FROM FF WHERE FF.NRRENDOR=@PNRRENDOR)<>0 
          BEGIN
            SET @VNRDITAR=ISNULL((SELECT NRDITARSHL FROM FF WHERE FF.NRRENDOR=@PNRRENDOR),0)

            DELETE FROM DFU WHERE NRRENDOR=@VNRDITAR

            INSERT INTO DFU (NRDITAR,KOD,PERSHKRIM,KOMENT,KMON,KURS1,KURS2,
                             TIPDOK,NRDOK,FRAKSDOK,DATEDOK,VLEFTA,
                             VLEFTAMV,TREGDK,NRLIBER,
                             TIPFAT,NRFAT,DTFAT,ISDOKSHOQ,ORDERTD,KODMASTER,TROW,TAGNR)
            SELECT NRDITAR=A.NRDOK,KOD=A.KODFKL+'.'+A.KMON,PERSHKRIM=A.SHENIM1,KOMENT=A.SHENIM2+'/Shlyerje FF',KMON=A.KMON,KURS1=A.KURS1,KURS2=A.KURS2,
                   TIPDOK='FF',NRDOK=A.NRDOK,FRAKSDOK=0,DATEDOK=A.DATEDOK,VLEFTA=A.PARAPG,
                   VLEFTAMV=A.PARAPG*A.KURS2/A.KURS1,TREGDK='D',NRLIBER=ISNULL((SELECT NRRENDOR FROM LFU C WHERE C.KOD=A.KODFKL+'.'+A.KMON),0),
                   TIPFAT='FF',NRFAT=A.NRDSHOQ,DTFAT=A.DTDSHOQ,ISDOKSHOQ=0,ORDERTD='',KODMASTER=A.KODFKL,TROW=0,TAGNR=0
              FROM FF A 
             WHERE A.NRRENDOR=@PNRRENDOR 
        
            SET @VNRDITAR=@@IDENTITY
        
            UPDATE FF SET NRDITARSHL=@VNRDITAR WHERE FF.NRRENDOR=@PNRRENDOR
        END

    END 



END

--FUND MODULI FURNITOR


ELSE
IF @PMODUL='A'
  BEGIN

    --RASTI A NGA VS
    IF @PTABLENAME='VS'
      BEGIN
        SET @VNRDITAR=ISNULL((SELECT NRDITAR FROM VSSCR WHERE VSSCR.NRRENDOR=@PNRRENDOR),0)

        DELETE FROM DAR WHERE NRRENDOR=@VNRDITAR

        IF ISNULL((SELECT NRRENDOR FROM LAR A WHERE A.KOD=(SELECT KOD FROM VSSCR B WHERE B.NRRENDOR=@PNRRENDOR)),0)=0
          INSERT INTO LAR (KOD,PERSHKRIM,KMON,MBARTUR,MBARTURMV,GJ,GJMV,
                           SG1,SG2,SG3,SG4,SG5,SG6,SG7,SG8,SG9,SG10,TROW,TAGNR)
               SELECT      KOD=A.KOD,PERSHKRIM=A.PERSHKRIM,KMON=A.KMON,MBARTUR=0,MBARTURMV=0,GJ=0,GJMV=0,
                           SG1=A.LLOGARIPK,SG2=A.KMON,SG3='',SG4='',SG5='',SG6='',SG7='',SG8='',SG9='',SG10='',TROW=0,TAGNR=0
                 FROM VSSCR A
                WHERE A.NRRENDOR=@PNRRENDOR


        INSERT INTO DAR (NRDITAR,KOD,PERSHKRIM,KOMENT,KMON,KURS1,KURS2,
                         TIPDOK,NRDOK,FRAKSDOK,DATEDOK,VLEFTA,
                         VLEFTAMV,TREGDK,NRLIBER,
                         TIPFAT,NRFAT,DTFAT,ISDOKSHOQ,KODMASTER,TROW,TAGNR)
        SELECT NRDITAR=A.NRDOK,KOD=B.KOD,PERSHKRIM=B.PERSHKRIM,KOMENT=B.KOMENT,KMON=B.KMON,KURS1=B.KURS1,KURS2=B.KURS2,
               TIPDOK='SP',NRDOK=A.NRDOK,FRAKSDOK=0,DATEDOK=A.DATEDOK,VLEFTA=(B.DB+B.KR),
               VLEFTAMV=CASE WHEN B.TREGDK='D' THEN B.DBKRMV ELSE -B.DBKRMV END,TREGDK=B.TREGDK,NRLIBER=ISNULL((SELECT NRRENDOR FROM LKL C WHERE C.KOD=B.KOD),0),
               TIPFAT=ISNULL(B.TIPREF,''),NRFAT=ISNULL(B.NRDOKREF,''),DTFAT=ISNULL(B.DATEDOKREF,A.DATEDOK),ISDOKSHOQ=0,KODMASTER=B.LLOGARIPK,TROW=0,TAGNR=0
          FROM VS A INNER JOIN VSSCR B ON A.NRRENDOR=B.NRD
         WHERE B.NRRENDOR=@PNRRENDOR 
        
        SET @VNRDITAR=@@IDENTITY
        
        UPDATE VSSCR SET NRDITAR=@VNRDITAR WHERE VSSCR.NRRENDOR=@PNRRENDOR
    END 

    --RASTI A NGA ARKA
    IF @PTABLENAME='ARKA'
      BEGIN
        SET @VNRDITAR=ISNULL((SELECT NRDITAR FROM ARKA WHERE ARKA.NRRENDOR=@PNRRENDOR),0)

        DELETE FROM DAR WHERE NRRENDOR=@VNRDITAR

        IF ISNULL((SELECT NRRENDOR FROM LAR A WHERE A.KOD=(SELECT B.KODAB+'.'+B.KMON FROM ARKA B WHERE B.NRRENDOR=@PNRRENDOR)),0)=0
          INSERT INTO LAR (KOD,PERSHKRIM,KMON,MBARTUR,MBARTURMV,GJ,GJMV,
                           SG1,SG2,SG3,SG4,SG5,SG6,SG7,SG8,SG9,SG10,TROW,TAGNR)
               SELECT      KOD=A.KODAB+'.'+A.KMON,PERSHKRIM=B.PERSHKRIM,KMON=A.KMON,MBARTUR=0,MBARTURMV=0,GJ=0,GJMV=0,
                           SG1=A.KODAB,SG2=A.KMON,SG3='',SG4='',SG5='',SG6='',SG7='',SG8='',SG9='',SG10='',TROW=0,TAGNR=0
                 FROM ARKA A INNER JOIN ARKAT B ON A.NRRENDORAB=B.NRRENDOR
                WHERE A.NRRENDOR=@PNRRENDOR


        INSERT INTO DAR (NRDITAR,KOD,PERSHKRIM,KOMENT,KMON,KURS1,KURS2,
                         TIPDOK,NRDOK,FRAKSDOK,DATEDOK,VLEFTA,
                         VLEFTAMV,TREGDK,NRLIBER,
                         TIPFAT,NRFAT,DTFAT,ISDOKSHOQ,KODMASTER,TROW,TAGNR)
        SELECT NRDITAR=A.NUMDOK,KOD=A.KODAB+'.'+A.KMON,PERSHKRIM=ISNULL(A.SHENIM1,''),KOMENT=ISNULL(A.SHENIM2,''),KMON=A.KMON,KURS1=A.KURS1,KURS2=A.KURS2,
               TIPDOK=A.TIPDOK,NRDOK=A.NUMDOK,FRAKSDOK=0,DATEDOK=A.DATEDOK,VLEFTA=A.VLERA,
               VLEFTAMV=A.VLERA*A.KURS2/A.KURS1,TREGDK=CASE WHEN TIPDOK='MA' THEN 'D' ELSE 'K' END,NRLIBER=ISNULL((SELECT NRRENDOR FROM LAR C WHERE C.KOD=A.KODAB+'.'+A.KMON),0),
               TIPFAT=A.TIPDOK,NRFAT=A.NUMDOK,DTFAT=A.DATEDOK,ISDOKSHOQ=0,KODMASTER=A.KODAB,TROW=0,TAGNR=0
          FROM ARKA A INNER JOIN ARKAT B ON A.NRRENDORAB=B.NRRENDOR
         WHERE A.NRRENDOR=@PNRRENDOR 
        
        SET @VNRDITAR=@@IDENTITY
        
        UPDATE ARKA SET NRDITAR=@VNRDITAR WHERE ARKA.NRRENDOR=@PNRRENDOR
    END 


END  

--FUND MODULI ARKA

ELSE
IF @PMODUL='B'
  BEGIN

    --RASTI NGA VS
    IF @PTABLENAME='VS'
      BEGIN
        SET @VNRDITAR=ISNULL((SELECT NRDITAR FROM VSSCR WHERE VSSCR.NRRENDOR=@PNRRENDOR),0)

        DELETE FROM DBA WHERE NRRENDOR=@VNRDITAR

        IF ISNULL((SELECT NRRENDOR FROM LBA A WHERE A.KOD=(SELECT KOD FROM VSSCR B WHERE B.NRRENDOR=@PNRRENDOR)),0)=0
          INSERT INTO LBA (KOD,PERSHKRIM,KMON,MBARTUR,MBARTURMV,GJ,GJMV,
                           SG1,SG2,SG3,SG4,SG5,SG6,SG7,SG8,SG9,SG10,TROW,TAGNR)
               SELECT      KOD=A.KOD,PERSHKRIM=A.PERSHKRIM,KMON=A.KMON,MBARTUR=0,MBARTURMV=0,GJ=0,GJMV=0,
                           SG1=A.LLOGARIPK,SG2=A.KMON,SG3='',SG4='',SG5='',SG6='',SG7='',SG8='',SG9='',SG10='',TROW=0,TAGNR=0
                 FROM VSSCR A
                WHERE A.NRRENDOR=@PNRRENDOR


        INSERT INTO DBA (NRDITAR,KOD,PERSHKRIM,KOMENT,KMON,KURS1,KURS2,
                         TIPDOK,NRDOK,FRAKSDOK,DATEDOK,VLEFTA,
                         VLEFTAMV,TREGDK,NRLIBER,
                         TIPFAT,NRFAT,DTFAT,ISDOKSHOQ,KODMASTER,TROW,TAGNR)
        SELECT NRDITAR=A.NRDOK,KOD=B.KOD,PERSHKRIM=B.PERSHKRIM,KOMENT=B.KOMENT,KMON=B.KMON,KURS1=B.KURS1,KURS2=B.KURS2,
               TIPDOK='SP',NRDOK=A.NRDOK,FRAKSDOK=0,DATEDOK=A.DATEDOK,VLEFTA=(B.DB+B.KR),
               VLEFTAMV=CASE WHEN B.TREGDK='D' THEN B.DBKRMV ELSE -B.DBKRMV END,TREGDK=B.TREGDK,NRLIBER=ISNULL((SELECT NRRENDOR FROM LKL C WHERE C.KOD=B.KOD),0),
               TIPFAT=ISNULL(B.TIPREF,''),NRFAT=ISNULL(B.NRDOKREF,''),DTFAT=ISNULL(B.DATEDOKREF,A.DATEDOK),ISDOKSHOQ=0,KODMASTER=B.LLOGARIPK,TROW=0,TAGNR=0
          FROM VS A INNER JOIN VSSCR B ON A.NRRENDOR=B.NRD
         WHERE B.NRRENDOR=@PNRRENDOR 
        
        SET @VNRDITAR=@@IDENTITY
        
        UPDATE VSSCR SET NRDITAR=@VNRDITAR WHERE VSSCR.NRRENDOR=@PNRRENDOR
    END 

    --RASTI B NGA BANKA
    IF @PTABLENAME='BANKA'
      BEGIN
        SET @VNRDITAR=ISNULL((SELECT NRDITAR FROM BANKA WHERE BANKA.NRRENDOR=@PNRRENDOR),0)

        DELETE FROM DBA WHERE NRRENDOR=@VNRDITAR

        IF ISNULL((SELECT NRRENDOR FROM LBA A WHERE A.KOD=(SELECT B.KODAB+'.'+B.KMON FROM BANKA B WHERE B.NRRENDOR=@PNRRENDOR)),0)=0
          INSERT INTO LBA (KOD,PERSHKRIM,KMON,MBARTUR,MBARTURMV,GJ,GJMV,
                           SG1,SG2,SG3,SG4,SG5,SG6,SG7,SG8,SG9,SG10,TROW,TAGNR)
               SELECT      KOD=A.KODAB+'.'+A.KMON,PERSHKRIM=B.PERSHKRIM,KMON=A.KMON,MBARTUR=0,MBARTURMV=0,GJ=0,GJMV=0,
                           SG1=A.KODAB,SG2=A.KMON,SG3='',SG4='',SG5='',SG6='',SG7='',SG8='',SG9='',SG10='',TROW=0,TAGNR=0
                 FROM BANKA A INNER JOIN BANKAT B ON A.NRRENDORAB=B.NRRENDOR
                WHERE A.NRRENDOR=@PNRRENDOR


        INSERT INTO DBA (NRDITAR,KOD,PERSHKRIM,KOMENT,KMON,KURS1,KURS2,
                         TIPDOK,NRDOK,FRAKSDOK,DATEDOK,VLEFTA,
                         VLEFTAMV,TREGDK,NRLIBER,
                         TIPFAT,NRFAT,DTFAT,ISDOKSHOQ,KODMASTER,TROW,TAGNR)
        SELECT NRDITAR=A.NUMDOK,KOD=A.KODAB+'.'+A.KMON,PERSHKRIM=ISNULL(A.SHENIM1,''),KOMENT=ISNULL(A.SHENIM2,''),KMON=A.KMON,KURS1=A.KURS1,KURS2=A.KURS2,
               TIPDOK=A.TIPDOK,NRDOK=A.NUMDOK,FRAKSDOK=0,DATEDOK=A.DATEDOK,VLEFTA=A.VLERA,
               VLEFTAMV=A.VLERA*A.KURS2/A.KURS1,TREGDK=CASE WHEN (TIPDOK='XK') OR (TIPDOK='AB') OR (TIPDOK='DB') THEN 'D' ELSE 'K' END,NRLIBER=ISNULL((SELECT NRRENDOR FROM LBA C WHERE C.KOD=A.KODAB+'.'+A.KMON),0),
               TIPFAT=A.TIPDOK,NRFAT=A.NUMDOK,DTFAT=A.DATEDOK,ISDOKSHOQ=0,KODMASTER=A.KODAB,TROW=0,TAGNR=0
          FROM BANKA A INNER JOIN BANKAT B ON A.NRRENDORAB=B.NRRENDOR
         WHERE A.NRRENDOR=@PNRRENDOR 
        
        SET @VNRDITAR=@@IDENTITY
        
        UPDATE BANKA SET NRDITAR=@VNRDITAR WHERE BANKA.NRRENDOR=@PNRRENDOR
    END 

END  
--FUND MODULI BANKA




GO
