SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [dbo].[CHECKOFFERBOUNDLE](@KODKLILOYAL AS VARCHAR(50),@VLERTOT AS FLOAT,@MAGAZINA AS VARCHAR(30),@BCPRODUCT AS VARCHAR(30))
AS

BEGIN
DECLARE @KODPROD AS VARCHAR(30);

IF (SELECT COUNT(1) FROM ARTIKUJ WHERE KOD = @BCPRODUCT)>=1 
	SET @KODPROD = @BCPRODUCT;
ELSE
	SET @KODPROD = (SELECT TOP 1 KOD FROM ARTIKUJ A
	LEFT JOIN ARTIKUJBCSCR AC ON AC.NRD = A.NRRENDOR
	WHERE A.BC =@BCPRODUCT OR AC.BC = @BCPRODUCT)


SELECT       OMB.KOD,
			 OMB.PERSHKRIM, 
			 OMB.ISHTE,
			 OMB.BEHET			 
FROM OFERTEMARKETING OM
INNER JOIN OFERTEMARKETINGBOUNDLE OMB ON OMB.NRD = OM.NRRENDOR
WHERE OM.NRRENDOR = @BCPRODUCT
  
END

GO
