SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[POSDTSKAD] (@KOD AS NVARCHAR(50))
AS
SELECT DATEADD(day,1,GETDATE()) AS DTSKAD, '12345' AS SERIA
union all
SELECT DATEADD(day,2,GETDATE()) AS DTSKAD, '23456' AS SERIA
union all
SELECT DATEADD(day,3,GETDATE()) AS DTSKAD, '34567' AS SERIA
union all
SELECT DATEADD(day,4,GETDATE()) AS DTSKAD, '45678' AS SERIA
union all
SELECT DATEADD(day,5,GETDATE()) AS DTSKAD, '56789' AS SERIA
union all
SELECT DATEADD(day,6,GETDATE()) AS DTSKAD, '01234' AS SERIA
union all
SELECT DATEADD(day,7,GETDATE()) AS DTSKAD, '22222' AS SERIA

GO
