SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO






CREATE      PROCEDURE [dbo].[KostoART2]
@MGKUFI  AS VARCHAR(10),
@MGKUFI1 AS VARCHAR(10),
@DTKUFI  AS DATETIME,
@DTKUFI1 AS DATETIME,
@ARTKP   AS VARCHAR(25),
@ARTKS   AS VARCHAR(25)
AS

SELECT NRRENDOR=0,TIP='H',KODAF=LEVIZJEHD.KARTLLG,LEVIZJEHD.KARTLLG, KMAG=MIN(LEVIZJEHD.KMAG),KMAGGR='1', NRDOK=0, 
       DTDOK=MAX(LEVIZJEHD.DATEDOK),NRFRAKS=0, 
       SASI=ROUND(SUM(CASE 
                    WHEN LEVIZJEHD.TIP='H' THEN LEVIZJEHD.SASIH
                    ELSE -1*LEVIZJEHD.SASID
                    END),3),
       VLERAM=ROUND(SUM(CASE 
                     WHEN LEVIZJEHD.TIP='H' THEN LEVIZJEHD.VLERAH
                     ELSE -1*LEVIZJEHD.VLERAD
                     END),3),
       CMIMM=ROUND(CASE 
                WHEN (SUM(CASE 
                    WHEN LEVIZJEHD.TIP='H' THEN LEVIZJEHD.SASIH
                    ELSE -1*LEVIZJEHD.SASID
                    END))*(SUM(CASE 
                     WHEN LEVIZJEHD.TIP='H' THEN LEVIZJEHD.VLERAH
                     ELSE -1*LEVIZJEHD.VLERAD
                     END))<=0 THEN 0
                ELSE (SUM(CASE 
                     WHEN LEVIZJEHD.TIP='H' THEN LEVIZJEHD.VLERAH
                     ELSE -1*LEVIZJEHD.VLERAD
                     END))/SUM(CASE 
                    WHEN LEVIZJEHD.TIP='H' THEN LEVIZJEHD.SASIH
                    ELSE -1*LEVIZJEHD.SASID
                    END)
                END,3), 
       NRD=0,FAT='F',DST='  ',BC=MAX(ARTIKUJ.BC),NRRENDORFAT=MAX(LEVIZJEHD.NRRENDORFAT), 
       TIPART=MAX(ARTIKUJ.TIP),TROW=-1
FROM  LEVIZJEHD LEFT JOIN ARTIKUJ ON LEVIZJEHD.KARTLLG=ARTIKUJ.KOD
                LEFT JOIN FJ ON LEVIZJEHD.NRRENDORFAT = FJ.NRRENDOR
WHERE  (LEVIZJEHD.KMAG>=@MGKUFI AND LEVIZJEHD.KMAG<=@MGKUFI1) AND (LEVIZJEHD.DATEDOK<@DTKUFI) AND (LEVIZJEHD.DATEDOK<@DTKUFI1)  AND (LEVIZJEHD.KARTLLG>=@ARTKP) AND ( LEVIZJEHD.KARTLLG<=@ARTKS)
GROUP BY LEVIZJEHD.KARTLLG

UNION ALL 
SELECT LEVIZJEHD.NRRENDOR,LEVIZJEHD.TIP,LEVIZJEHD.KODAF, LEVIZJEHD.KARTLLG, LEVIZJEHD.KMAG,KAGGR='1', LEVIZJEHD.NRDOK, LEVIZJEHD.DATEDOK, LEVIZJEHD.NRFRAKS, 
       ROUND(CASE WHEN LEVIZJEHD.TIP='H' THEN SASIH ELSE SASID END,3) , 
       ROUND(CASE WHEN LEVIZJEHD.TIP='H' THEN VLERAH ELSE VLERAD END,3),
       ROUND(LEVIZJEHD.CMIMM,3), NRD, 
       FAT=CASE 
             WHEN LEVIZJEHD.DOK_JB=1 THEN 'F'
             ELSE ' '
             END,
       LEVIZJEHD.DST,ARTIKUJ.BC,LEVIZJEHD.NRRENDORFAT, ARTIKUJ.TIP AS TIPARTIKULL,0 AS TROW
FROM  LEVIZJEHD LEFT JOIN ARTIKUJ ON LEVIZJEHD.KARTLLG=ARTIKUJ.KOD
                LEFT JOIN FJ ON LEVIZJEHD.NRRENDORFAT = FJ.NRRENDOR
WHERE (LEVIZJEHD.KMAG>=@MGKUFI AND LEVIZJEHD.KMAG<=@MGKUFI1) AND (LEVIZJEHD.DATEDOK>=@DTKUFI AND LEVIZJEHD.DATEDOK<=@DTKUFI1) AND
             (LEVIZJEHD.KARTLLG>=@ARTKP) AND ( LEVIZJEHD.KARTLLG<=@ARTKS)
ORDER BY KARTLLG, DTDOK, TIP DESC , NRDOK, NRRENDOR







GO
