SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO









CREATE   procedure [dbo].[DELETEALL]

AS

-- vetem dokumenta shiko me poshte 

DELETE FROM  AGJENTSHITJE

DELETE FROM  AQ
DELETE FROM  AQSCR
DELETE FROM  AQKARTELA

DELETE FROM  ARKA
DELETE FROM  ARKASCR
DELETE FROM  ARKAT

DELETE FROM  BANKA
DELETE FROM  BANKASCR
DELETE FROM  BANKAT

DELETE FROM  ARTIKUJ
DELETE FROM  ARTIKUJ_PATH
DELETE FROM  ARTIKUJ_RBOT

DELETE FROM  ARTIKUJ_RCD
DELETE FROM  ARTIKUJ_RMAK
DELETE FROM  ARTIKUJCM
DELETE FROM  ARTIKUJFIR
DELETE FROM  ARTIKUJKLS1
DELETE FROM  ARTIKUJKLS2
DELETE FROM  ARTIKUJKLS3
DELETE FROM  ARTIKUJSCR
DELETE FROM  ARTIKUJSIST
DELETE FROM  ArtikujCmime
DELETE FROM  ArtikujKtg

-- DELETE FROM  CONFIGLM
-- DELETE FROM  CONFIGMG
-- DELETE FROM  CONFND
-- DELETE FROM  PERIUDHE
-- DELETE FROM  SKEMELM


DELETE FROM  DAR
DELETE FROM  DBA
DELETE FROM  DEPARTAMENT
DELETE FROM  DFU
DELETE FROM  DG
DELETE FROM  DGSCR
DELETE FROM  DKL

DELETE FROM  FF
DELETE FROM  FFSCR

DELETE FROM  FH
DELETE FROM  FHSCR
DELETE FROM  FD
DELETE FROM  FDSCR

DELETE FROM  FJ
DELETE FROM  FJSCR
DELETE FROM  FJPG
DELETE FROM  FJSHOQERUES
DELETE FROM  FJT
DELETE FROM  FJTSCR

DELETE FROM  LAQ
DELETE FROM  LAR
DELETE FROM  LBA
DELETE FROM  LFU
DELETE FROM  LKL
DELETE FROM  LM
DELETE FROM  LMG

DELETE FROM  OFK
DELETE FROM  OFKSCR

DELETE FROM  ORF
DELETE FROM  ORFSCR

DELETE FROM  ORK
DELETE FROM  ORKSCR

DELETE FROM  ORDERITEMS
DELETE FROM  ORDERITEMSSCR

DELETE FROM  PROFITCENTER

DELETE FROM  SM
DELETE FROM  SMSCR
DELETE FROM  SMBak
DELETE FROM  SMBakScr


DELETE FROM  TATIM
DELETE FROM  TRANSPORT
DELETE FROM  VENDNDODHJE

DELETE FROM  VS
DELETE FROM  VSSCR

DELETE FROM  VSST
DELETE FROM  VSSTSCR

DELETE FROM  LLOGARI
DELETE FROM  BORDERO

DELETE FROM  FK
DELETE FROM  FKSCR
DELETE FROM  FKST
DELETE FROM  FKSTSCR


DELETE FROM  ZBRITJE
DELETE FROM  RAJON
DELETE FROM  SHERBIM
DELETE FROM  MAGAZINA
DELETE FROM  MGSHOQERUES
DELETE FROM  NENDITAR


DELETE FROM  KLIENT
DELETE FROM  KLIENTCM
DELETE FROM  KLIENTKART

DELETE FROM  FURNITOR
DELETE FROM  KATEGORI
DELETE FROM  GRUPIMFT
DELETE FROM  KALENDAR
DELETE FROM  KASE
DELETE FROM  KURSE
DELETE FROM  NJESI
DELETE FROM  Nipt

DELETE FROM  ListFiroD
DELETE FROM  ListFiroM
DELETE FROM  DitarVeprime
DELETE FROM  KODCHANGE
DELETE FROM  KODCHANGEFL
DELETE FROM  DRHUSER
DELETE FROM  DRHUSERKUFI

DELETE FROM  RP_Liste
DELETE FROM  TIPDOK
DELETE FROM  TBLSF
DELETE FROM  X_FORMDISPL
DELETE FROM  LISTE

/* -- vetem dokumenta 
USE ....

DELETE FROM  AQ
DELETE FROM  AQSCR

DELETE FROM  FK
DELETE FROM  FKSCR
DELETE FROM  VS
DELETE FROM  VSSCR
DELETE FROM  ARKA
DELETE FROM  ARKASCR
DELETE FROM  BANKA
DELETE FROM  BANKASCR

DELETE FROM  FH
DELETE FROM  FHSCR
DELETE FROM  FD
DELETE FROM  FDSCR
DELETE FROM  MGSHOQERUES
DELETE FROM  FF
DELETE FROM  FFSCR
DELETE FROM  DG
DELETE FROM  DGSCR
DELETE FROM  FJ
DELETE FROM  FJSCR
DELETE FROM  FJPG
DELETE FROM  FJSHOQERUES
DELETE FROM  FJT
DELETE FROM  FJTSCR

DELETE FROM  OFK
DELETE FROM  OFKSCR
DELETE FROM  ORF
DELETE FROM  ORFSCR
DELETE FROM  ORK
DELETE FROM  ORKSCR
DELETE FROM  SM
DELETE FROM  SMSCR
DELETE FROM  SMBak
DELETE FROM  SMBakScr
DELETE FROM  OrderItems
DELETE FROM  OrderItemsScr

DELETE FROM  DitarVeprime

Exec dbo.DELETEDITAR
Exec dbo.DeleteLibra


*/


Declare @Sql Varchar(100)
    Set @Sql = ' DBCC SHRINKDATABASE ('+Db_Name()+')'
   Exec (@Sql)

-- Procedura per Size te tabelave (Nr records)
--select t.name TableName, i.rows Records
--from SysObjects t, SysIndexes i
--where t.xtype = 'U' and i.id = t.id and i.indid in (0,1)
--order by TableName;
--
--
--declare @stats Table (n sysname, c int)
--insert into @stats
--    exec sp_msforeachtable 'select parsename(''?'', 1),  count(*) FROM  ?'
--
--  select * 
--    FROM  @stats
--order by c desc






GO
