SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROC [dbo].[VW_SHITJE_ORE](@DNGA AS DATETIME,@DDERI AS DATETIME,
							@TIPI AS VARCHAR(20),@VLERA AS VARCHAR(20))
AS

--DECLARE @TIPI AS VARCHAR(20)
--DECLARE @VLERA AS VARCHAR(20)

IF ISNULL(@TIPI,'') = ''
	SET @TIPI = 'ORE'
IF ISNULL(@VLERA,'') = ''
	SET @VLERA = 'VLERE'
	
SELECT VLERA  = CASE WHEN @VLERA = 'VLERE' 
						THEN round(SUM(VLERTOT)/1000,2) 
					ELSE
						     COUNT(1) END,
	   NDARJA = CASE WHEN @TIPI = 'ORE'
						THEN DATEPART(HOUR,TIMED)
					 WHEN @TIPI = 'DITEJAVE'
						THEN DATEPART(DW,TIMED)
					 ELSE 
							 DATEPART(DAY,TIMED) END,
	   TIPI  = @TIPI,
	   VLERE = @VLERA,
	   DNGA  = @DNGA,
	   DDERI = @DDERI
FROM   SMBAK S
--INNER JOIN SMBAKSCR SC ON SC.NRD = S.NRRENDOR
WHERE S.DATEDOK>=@DNGA AND S.DATEDOK<=@DDERI
GROUP BY CASE WHEN @TIPI = 'ORE'
						THEN DATEPART(HOUR,TIMED)
					 WHEN @TIPI = 'DITEJAVE'
						THEN DATEPART(DW,TIMED)
					 ELSE 
							 DATEPART(DAY,TIMED) END
ORDER BY CASE WHEN @TIPI = 'ORE'
						THEN DATEPART(HOUR,TIMED)
					 WHEN @TIPI = 'DITEJAVE'
						THEN DATEPART(DW,TIMED)
					 ELSE 
							 DATEPART(DAY,TIMED) END

GO
