SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




CREATE     PROCEDURE [dbo].[ZZ_GjenerimKTHIMEneFJ]

--(
--@DT1 AS DATETIME,
--@DT2 AS DATETIME,
--@NRDST AS BIGINT       --[Vlera Maximale e Tip G ne FJ]
--)


-- Mos Haro NRDST tek NRDITARPRMC	

AS

    DROP TABLE FJK

    DROP TABLE FJKSCR

    UPDATE FJ    SET TAGNR = 0 WHERE TAGNR<>0

    UPDATE FJSCR SET TAGNR = 0 WHERE TAGNR<>0


    UPDATE FJ 
       SET TAGNR = NRRENDOR
     WHERE LLOJDOK='K' AND (ISNULL(NRFATST,'0')<='0') AND DATEDOK>=DBO.DATEVALUE('01/06/2008') AND DATEDOK<=DBO.DATEVALUE('30/06/2008')

     SELECT FJ.* INTO FJK
       FROM FJ
      WHERE LLOJDOK='K' AND (ISNULL(NRFATST,'0')<='0') AND (DATEDOK>=DBO.DATEVALUE('01/06/2008') AND DATEDOK<=DBO.DATEVALUE('30/06/2008'))

     SELECT FJSCR.* INTO FJKSCR
       FROM FJ INNER JOIN FJSCR ON FJ.NRRENDOR=FJSCR.NRD
      WHERE LLOJDOK='K' AND (ISNULL(NRFATST,'0')<='0') AND (DATEDOK>=DBO.DATEVALUE('01/06/2008') AND DATEDOK<=DBO.DATEVALUE('30/06/2008'))

     UPDATE FJK 
        SET NRRENDDMG = 0, NRDMAG = 0,      NRDFK = 0, NRDITAR = 0, 
            NRDITARSHL= 0, NRDITARPRMC = 0, NRRENDKF = 0, 
            NRFRAKSKF = 0, NRDFTEXTRA = 0,  NRRENDOROF = 0, NRRENDOROR = 0, 
            NRRENDORORGFJ = 0, 
            LLOJDOK = 'G', 
            NRFATST = CAST(CAST(NRDOK AS BIGINT) AS VARCHAR), 
            DTFATST = DATEDOK, 
            VLPATVSH = 0-[VLPATVSH], VLTVSH = 0-[VLTVSH], 
            VLERZBR = 0-[VLERZBR], VLTAX = 0-[VLTAX], 
            VLERTOT = 0-[VLERTOT], PARAPG = 0-[PARAPG], 
            VLKASE = 0-[VLKASE]

     UPDATE FJKSCR 
        SET FJKSCR.TAGNR = [NRD], FJKSCR.SASI = 0-[SASI], 
            FJKSCR.VLERABS = 0-[VLERABS], FJKSCR.VLERAM = 0-[VLERAM], 
            FJKSCR.VLPATVSH = 0-[VLPATVSH], FJKSCR.VLTVSH = 0-[VLTVSH], 
            FJKSCR.VLTAX = 0-[VLTAX], FJKSCR.IFIZIK = 'I'


--    ALTER TABLE FJK DROP COLUMN NRRENDOR
--    ALTER TABLE FJK ADD COLUMN NRRENDOR AUTOINCREMENT
--   UPDATE FJK SET NRDOK = NRRENDOR+@NRDST   --[Vlera Maximale e Tip G ne FJ]

-- Rinumurimi
     UPDATE FJK SET NRDITARPRMC=0

     UPDATE FJK
        SET NRDITARPRMC=(SELECT COUNT(1) 
                         FROM FJK B 
                        WHERE B.DATEDOK<A.DATEDOK OR (B.DATEDOK=A.DATEDOK AND B.NRDOK<A.NRDOK))
       FROM FJK A 

     UPDATE FJK SET NRDOK = NRDITARPRMC+19427225
     UPDATE FJK SET NRDITARPRMC=0
-- Fund Rinumurimi


     UPDATE FJK 
        SET NRSERIAL = CAST(CAST(NRDOK AS BIGINT) AS VARCHAR), 
            NRDSHOQ  = CAST(CAST(NRDOK AS BIGINT) AS VARCHAR), 
            NRDMAG   = NRDOK

     UPDATE FJ 
        SET FJ.NRFATST = CAST(CAST(FJK.NRDOK AS BIGINT) AS VARCHAR), 
            FJ.DTFATST = FJK.DATEDOK
       FROM FJ INNER JOIN FJK ON FJ.TAGNR = FJK.TAGNR 

     UPDATE FJ SET TAGNR = 0 WHERE TAGNR<>0

     INSERT INTO FJ (DATEDOK, KTH, NRDOK, NRFRAKS, KOD, KODFKL, KODKART, KMON, KLASAKF, VENHUAJ, NIPT, NRSERIAL, KODFISKAL, RRETHI, SHENIM1, SHENIM2, SHENIM3, SHENIM4, NRDSHOQ, DTDSHOQ, NRRENDDMG, TIPDMG, NRMAG, KMAG, NRDMAG, FRDMAG, DTDMAG, MODPG, DTAF, DTDS, PERQDS, KURS1, KURS2, VLPATVSH, VLTVSH, VLERZBR, VLTAX, VLERTOT, PARAPG, PERQTVSH, PERQZBR, LLOGTVSH, LLOGZBR, LLOGARK, NRDFK, NRDITAR, POSTIM, LETER, FIRSTDOK, ISDG, NRDOKDG, DTDOKDG, TAGNR, NRDITARSHL, NRDITARPRMC, NRRENDKF, NRFRAKSKF, NRDFTEXTRA, ISDOKSHOQ, NRRENDOROF, NRRENDOROR, NRRENDORORGFJ, GRUPIMFT, KLASIFIKIM, LLOJDOK, NRFATST, DTFATST, VLKASE, ISPERMBLEDHES, PRINTKOMENT, USI, USM, TAG, TROW)
     SELECT FJK.DATEDOK, FJK.KTH, FJK.NRDOK, FJK.NRFRAKS, FJK.KOD, FJK.KODFKL, FJK.KODKART, FJK.KMON, FJK.KLASAKF, FJK.VENHUAJ, FJK.NIPT, FJK.NRSERIAL, FJK.KODFISKAL, FJK.RRETHI, FJK.SHENIM1, FJK.SHENIM2, FJK.SHENIM3, FJK.SHENIM4, FJK.NRDSHOQ, FJK.DTDSHOQ, FJK.NRRENDDMG, FJK.TIPDMG, FJK.NRMAG, FJK.KMAG, FJK.NRDMAG, FJK.FRDMAG, FJK.DTDMAG, FJK.MODPG, FJK.DTAF, FJK.DTDS, FJK.PERQDS, FJK.KURS1, FJK.KURS2, FJK.VLPATVSH, FJK.VLTVSH, FJK.VLERZBR, FJK.VLTAX, FJK.VLERTOT, FJK.PARAPG, FJK.PERQTVSH, FJK.PERQZBR, FJK.LLOGTVSH, FJK.LLOGZBR, FJK.LLOGARK, FJK.NRDFK, FJK.NRDITAR, FJK.POSTIM, FJK.LETER, FJK.FIRSTDOK, FJK.ISDG, FJK.NRDOKDG, FJK.DTDOKDG, FJK.TAGNR, FJK.NRDITARSHL, FJK.NRDITARPRMC, FJK.NRRENDKF, FJK.NRFRAKSKF, FJK.NRDFTEXTRA, FJK.ISDOKSHOQ, FJK.NRRENDOROF, FJK.NRRENDOROR, FJK.NRRENDORORGFJ, FJK.GRUPIMFT, FJK.KLASIFIKIM, FJK.LLOJDOK, FJK.NRFATST, FJK.DTFATST, FJK.VLKASE, FJK.ISPERMBLEDHES, FJK.PRINTKOMENT, FJK.USI, FJK.USM, FJK.TAG, FJK.TROW
       FROM FJK

     INSERT INTO FJSCR ( NRD, KOD, KODAF, KARTLLG, PERSHKRIM, NRRENDKLLG, LLOGARIPK, NJESI, CMSHZB0, CMIMM, SASI, PERQDSCN, CMIMBS, VLERABS, VLERAM, VLPATVSH, VLTVSH, PERQTVSH, VLTAX, KOEFSHB, NJESINV, TIPKLL, BC, KOMENT, PROMOC, PROMOCTIP, NOTMAG, RIMBURSIM, DTSKADENCE, TIPREF, DATEDOKREF, SERI, NRDOKREF, KODKR, TIPKTH, NRDITAR, IFIZIK, TROW, TAGNR, LLOGLM, CMSHZB0K )
     SELECT FJKSCR.NRD, FJKSCR.KOD, FJKSCR.KODAF, FJKSCR.KARTLLG, FJKSCR.PERSHKRIM, FJKSCR.NRRENDKLLG, FJKSCR.LLOGARIPK, FJKSCR.NJESI, FJKSCR.CMSHZB0, FJKSCR.CMIMM, FJKSCR.SASI, FJKSCR.PERQDSCN, FJKSCR.CMIMBS, FJKSCR.VLERABS, FJKSCR.VLERAM, FJKSCR.VLPATVSH, FJKSCR.VLTVSH, FJKSCR.PERQTVSH, FJKSCR.VLTAX, FJKSCR.KOEFSHB, FJKSCR.NJESINV, FJKSCR.TIPKLL, FJKSCR.BC, FJKSCR.KOMENT, FJKSCR.PROMOC, FJKSCR.PROMOCTIP, FJKSCR.NOTMAG, FJKSCR.RIMBURSIM, FJKSCR.DTSKADENCE, FJKSCR.TIPREF, FJKSCR.DATEDOKREF, FJKSCR.SERI, FJKSCR.NRDOKREF, FJKSCR.KODKR, FJKSCR.TIPKTH, FJKSCR.NRDITAR, FJKSCR.IFIZIK, FJKSCR.TROW, FJKSCR.TAGNR, FJKSCR.LLOGLM, FJKSCR.CMSHZB0K
       FROM FJKSCR

     UPDATE FJSCR 
        SET FJSCR.NRD = [FJ].[NRRENDOR]
       FROM FJ INNER JOIN FJSCR ON FJ.TAGNR = FJSCR.TAGNR 
      WHERE (FJ.TAGNR<>0)

     UPDATE DKL SET DKL.TAGNR = 0 WHERE TAGNR<>0

     INSERT INTO DKL (DATEDOK, NRDOK, TIPDOK, KOD, KMON, PERSHKRIM, KOMENT, NRFAT, DTFAT, FRAKSDOK, KURS1, KURS2, VLEFTA, VLEFTAMV, TREGDK, KODMASTER, LLOJDOK, TAGNR )
     SELECT FJ.DATEDOK, FJ.NRDOK, 'FJ' AS Expr3, FJ.KOD, FJ.KMON, FJ.SHENIM1, FJ.SHENIM2, FJ.NRDSHOQ, FJ.DTDSHOQ, 0 AS Expr2, FJ.KURS1, FJ.KURS2, FJ.VLERTOT, FJ.VLERTOT, 'D' AS Expr1, FJ.KODFKL, FJ.LLOJDOK, FJ.NRRENDOR
       FROM FJ
      WHERE FJ.NRDITAR=0

     UPDATE FJ 
        SET FJ.NRDITAR = [DKL].[NRRENDOR]
       FROM FJ INNER JOIN DKL ON FJ.NRRENDOR = DKL.TAGNR 
      WHERE (FJ.TAGNR<>0)

     UPDATE DKL SET DKL.TAGNR = 0 WHERE TAGNR<>0


SET QUOTED_IDENTIFIER OFF 

GO
