SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO










CREATE   procedure [dbo].[UPDATEKMAGEHW]

AS

--ALTER TABLE MAGAZINA ADD KODNEW VARCHAR(10)


UPDATE MAGAZINA 
   SET KODNEW=KOD

UPDATE MAGAZINA 
   SET KODNEW='D'+SUBSTRING(KOD,3,30)
 WHERE LEFT(KOD,2)='MS' AND LEN(KOD)>3

UPDATE MAGAZINA 
   SET KODNEW='D13'
 WHERE KOD='MS0'



---   F H  ----

--Rreshta FHscr
UPDATE A
   SET A.KOD=C.KODNEW+SUBSTRING(A.KOD,CHARINDEX('.',A.KOD),30) 
  FROM FHSCR A INNER JOIN FH B ON A.NRD=B.NRRENDOR
               INNER JOIN MAGAZINA C ON C.KOD=B.KMAG
 WHERE LEFT(C.KODNEW,1)='D'

--Koka FH
UPDATE A
   SET A.KMAG=B.KODNEW
  FROM FH A INNER JOIN MAGAZINA B ON A.KMAG=B.KOD
 WHERE LEFT(B.KODNEW,1)='D'

UPDATE A
   SET A.KMAGRF=B.KODNEW
  FROM FH A INNER JOIN MAGAZINA B ON A.KMAGRF=B.KOD
 WHERE LEFT(B.KODNEW,1)='D'

UPDATE A
   SET A.KMAGLNK=B.KODNEW
  FROM FH A INNER JOIN MAGAZINA B ON A.KMAGLNK=B.KOD
 WHERE LEFT(B.KODNEW,1)='D'
--Fund FH


-- F D ----

--Rreshta FDscr
UPDATE A
   SET A.KOD=C.KODNEW+SUBSTRING(A.KOD,CHARINDEX('.',A.KOD),30) 
  FROM FDSCR A INNER JOIN FD B ON A.NRD=B.NRRENDOR
               INNER JOIN MAGAZINA C ON C.KOD=B.KMAG
 WHERE LEFT(C.KODNEW,1)='D'

--Koka Fd
UPDATE A
   SET A.KMAG=B.KODNEW
  FROM FD A INNER JOIN MAGAZINA B ON A.KMAG=B.KOD
 WHERE LEFT(B.KODNEW,1)='D'

UPDATE A
   SET A.KMAGRF=B.KODNEW
  FROM FD A INNER JOIN MAGAZINA B ON A.KMAGRF=B.KOD
 WHERE LEFT(B.KODNEW,1)='D'

UPDATE A
   SET A.KMAGLNK=B.KODNEW
  FROM FD A INNER JOIN MAGAZINA B ON A.KMAGLNK=B.KOD
 WHERE LEFT(B.KODNEW,1)='D'

--Fund FD

-- F F ---

--Rreshta FFscr
UPDATE A
   SET A.KOD=C.KODNEW+SUBSTRING(A.KOD,CHARINDEX('.',A.KOD),30) 
  FROM FFSCR A INNER JOIN FF B ON A.NRD=B.NRRENDOR
               INNER JOIN MAGAZINA C ON C.KOD=B.KMAG
 WHERE LEFT(C.KODNEW,1)='D' AND A.TIPKLL='K' 


--Koka FF
UPDATE A
   SET A.KMAG=B.KODNEW
  FROM FF A INNER JOIN MAGAZINA B ON A.KMAG=B.KOD
 WHERE LEFT(B.KODNEW,1)='D'


--Fund FF

-- F J ---

--Rreshta FJscr
UPDATE A
   SET A.KOD=C.KODNEW+SUBSTRING(A.KOD,CHARINDEX('.',A.KOD),30) 
  FROM FJSCR A INNER JOIN FJ B ON A.NRD=B.NRRENDOR
               INNER JOIN MAGAZINA C ON C.KOD=B.KMAG
 WHERE LEFT(C.KODNEW,1)='D' AND A.TIPKLL='K' 


--Koka FJ
UPDATE A
   SET A.KMAG=B.KODNEW
  FROM FJ A INNER JOIN MAGAZINA B ON A.KMAG=B.KOD
 WHERE LEFT(B.KODNEW,1)='D'

--Fund FJ


-- S M ---

--Rreshta SMscr
UPDATE A
   SET A.KOD=C.KODNEW+SUBSTRING(A.KOD,CHARINDEX('.',A.KOD),30) 
  FROM SMSCR A INNER JOIN SM B       ON A.NRD=B.NRRENDOR
               INNER JOIN MAGAZINA C ON C.KOD=B.KMAG
 WHERE LEFT(C.KODNEW,1)='D' AND A.TIPKLL='K' 


--Koka SM
UPDATE A
   SET A.KMAG=B.KODNEW
  FROM SM A INNER JOIN MAGAZINA B ON A.KMAG=B.KOD
 WHERE LEFT(B.KODNEW,1)='D'

--Fund SM

-- OFK ---

--Rreshta OFKscr
UPDATE A
   SET A.KOD=C.KODNEW+SUBSTRING(A.KOD,CHARINDEX('.',A.KOD),30) 
  FROM OFKSCR A INNER JOIN OFK B ON A.NRD=B.NRRENDOR
               INNER JOIN MAGAZINA C ON C.KOD=B.KMAG
 WHERE LEFT(C.KODNEW,1)='D' AND A.TIPKLL='K' 


--Koka OFK
UPDATE A
   SET A.KMAG=B.KODNEW
  FROM OFK A INNER JOIN MAGAZINA B ON A.KMAG=B.KOD
WHERE LEFT(B.KODNEW,1)='D'

--Fund OFK


-- ORK ---

--Rreshta ORKscr
UPDATE A
   SET A.KOD=C.KODNEW+SUBSTRING(A.KOD,CHARINDEX('.',A.KOD),30) 
  FROM ORKSCR A INNER JOIN ORK B ON A.NRD=B.NRRENDOR
               INNER JOIN MAGAZINA C ON C.KOD=B.KMAG
 WHERE LEFT(C.KODNEW,1)='D' AND A.TIPKLL='K' 


--Koka ORK
UPDATE A
   SET A.KMAG=B.KODNEW
  FROM ORK A INNER JOIN MAGAZINA B ON A.KMAG=B.KOD
 WHERE LEFT(B.KODNEW,1)='D'

--Fund ORK


-- ORF ---

--Rreshta ORFscr
UPDATE A
   SET A.KOD=C.KODNEW+SUBSTRING(A.KOD,CHARINDEX('.',A.KOD),30) 
  FROM ORFSCR A INNER JOIN ORF B ON A.NRD=B.NRRENDOR
               INNER JOIN MAGAZINA C ON C.KOD=B.KMAG
 WHERE LEFT(C.KODNEW,1)='D' AND A.TIPKLL='K' 


--Koka ORF
UPDATE A
   SET A.KMAG=B.KODNEW
  FROM ORF A INNER JOIN MAGAZINA B ON A.KMAG=B.KOD
 WHERE LEFT(B.KODNEW,1)='D'

--Fund ORF


-- FJT ---

--Rreshta FJTscr
UPDATE A
   SET A.KOD=C.KODNEW+SUBSTRING(A.KOD,CHARINDEX('.',A.KOD),30) 
  FROM FJTSCR A INNER JOIN FJT B ON A.NRD=B.NRRENDOR
               INNER JOIN MAGAZINA C ON C.KOD=B.KMAG
 WHERE LEFT(C.KODNEW,1)='D' AND A.TIPKLL='K' 


--Koka FJT
UPDATE A
   SET A.KMAG=B.KODNEW
  FROM FJT A INNER JOIN MAGAZINA B ON A.KMAG=B.KOD
 WHERE LEFT(B.KODNEW,1)='D'

--Fund FJT

--LMG--
UPDATE A
   SET A.SG1=B.KODNEW,
       A.KOD=B.KODNEW+'.'+ISNULL(A.SG2,'')+'.'+ISNULL(A.SG3,'')+'.'+ISNULL(A.SG4,'')+'.'+ISNULL(A.SG5,'')
  FROM LMG A INNER JOIN MAGAZINA B ON A.SG1=B.KOD
 WHERE LEFT(B.KODNEW,1)='D'
-- Fund Magazina


-- Kontabiliteti ---
-- FK -- 
UPDATE A
   SET A.KMAG=B.KODNEW,A.REFERDOK=B.KODNEW
  FROM FK A INNER JOIN MAGAZINA B ON A.KMAG=B.KOD
WHERE LEFT(B.KODNEW,1)='D'

-- LM ---
UPDATE A
   SET A.SG4=B.KODNEW
  FROM LM A INNER JOIN MAGAZINA B ON A.SG4=B.KOD
 WHERE LEFT(B.KODNEW,1)='D'

-- FKSCR --
UPDATE A
   SET A.KOD=B.SG1+'.'+ISNULL(B.SG2,'')+'.'+ISNULL(B.SG3,'')+'.'+ISNULL(B.SG4,'')+'.'+ISNULL(B.SG5,'')
  FROM FKSCR A INNER JOIN LM B ON A.KOD=B.KOD
 WHERE LEFT(B.SG4,1)='D'

-- LM Kod ---
UPDATE A
   SET A.KOD=A.SG1+'.'+ISNULL(A.SG2,'')+'.'+ISNULL(A.SG3,'')+'.'+ISNULL(A.SG4,'')+'.'+ISNULL(A.SG5,'')
  FROM LM A 
 WHERE LEFT(A.SG4,1)='D'
-- Fund LM --

--KLIENT

UPDATE A
   SET A.KMAG=B.KODNEW
  FROM KLIENT A INNER JOIN MAGAZINA B ON A.KMAG=B.KOD
 WHERE LEFT(B.KODNEW,1)='D'

--FUND KLIENT --

--DRHUSER

UPDATE A
   SET A.KODREF=B.KODNEW
  FROM DRHUSER A INNER JOIN MAGAZINA B ON A.KODREF=B.KOD
 WHERE LEFT(B.KODNEW,1)='D'

--FUND DRHUSER --


-- MAGAZINA --- 
UPDATE A
   SET A.KOD=A.KODNEW
  FROM MAGAZINA A
 WHERE LEFT(A.KODNEW,1)='D'

--ALTER TABLE MAGAZINA DROP COLUMN KODNEW
--FUND MAGAZINA--






GO
