SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[FISKPOROSI]

AS
BEGIN

SELECT NRRENDOR,POROSIGRP INTO POROSIFISK FROM POROSI WHERE STATUSPOROSI=0

DECLARE @NRD AS INT
declare cu cursor for
select NRRENDOR FROM POROSIFISK WHERE ISNULL(FIC,'')=''

OPEN CU
FETCH NEXT FROM CU INTO @NRD
WHILE @@FETCH_STATUS = 0
BEGIN
EXEC [dbo].[_FiscalCreateSalesXmlPOS] @NRD
FETCH NEXT FROM CU INTO @NRD
END
CLOSE CU
DEALLOCATE CU

END
GO
