SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
--InsertOfferCoupon 3,1000,FALSE



create Proc [dbo].[InsertOfferCoupon](@VALIDITY AS INT, @VALUE AS FLOAT,@ISPERCENTAGE AS BIT)
as

DECLARE @NRRADHES AS FLOAT;
DECLARE @MAXNR AS VARCHAR(50)


SET @MAXNR = (SELECT MAX(SUBSTRING(NRKUPON,3,11)) FROM KUPONA WHERE LEN(NRKUPON)=13)

IF @MAXNR IS NULL
	SET @MAXNR = '2800000000001'
ELSE
	BEGIN
		SET @MAXNR = (SELECT CONVERT(VARCHAR(50),CONVERT(FLOAT, @MAXNR)+1))
		SET @MAXNR = (SELECT '28' + RIGHT('00000000000'+@MAXNR,11))
	END
INSERT INTO KUPONA(
						NRKUPON,
						DNGA,
						DDERI,
						AKTIV,
						VALUE,
						ISPERCENTAGE,
						PASSKEY
				  )
	   VALUES	  (		@MAXNR,
						GETDATE(),
						DATEADD(DAY,@VALIDITY,GETDATE()),
						1,
						@VALUE,
						@ISPERCENTAGE,
						round(10000*RAND(),0)
				  )

SELECT @MAXNR,GETDATE(),DATEADD(DAY,@VALIDITY,GETDATE()),@VALUE,@ISPERCENTAGE,round(10000*RAND(),0)
GO
