SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO









CREATE         procedure [dbo].[UPDATE_DITARE_AB]
(
@PMODUL     AS VARCHAR(1), --'A' ne rastin e arkes,'B' ne rastin e bankes
@PTABLENAME AS VARCHAR(20),--'ARKA' kur behet fjale per Arken,'BANKA' ne rastin Banke dhe 'VS' kur vijne nga vs-te
@PNRRENDOR  AS INT         --Nrrendori per tabelen nga vjen
)
AS

DECLARE @VTABLENAME AS VARCHAR(20)
DECLARE @VNRDITAR   AS VARCHAR(20)

SET @VTABLENAME=@PTABLENAME
SET @VNRDITAR  =0


IF @PMODUL='A'
  BEGIN

    --RASTI A NGA VS
    IF @PTABLENAME='VS'
      BEGIN
        SET @VNRDITAR=ISNULL((SELECT NRDITAR FROM VSSCR WHERE VSSCR.NRRENDOR=@PNRRENDOR),0)

        DELETE FROM DAR WHERE NRRENDOR=@VNRDITAR

        IF ISNULL((SELECT TOP 1 NRRENDOR FROM LAR A WHERE A.KOD=(SELECT KOD FROM VSSCR B WHERE B.NRRENDOR=@PNRRENDOR)),0)=0
          INSERT INTO LAR (KOD,PERSHKRIM,KMON,MBARTUR,MBARTURMV,GJ,GJMV,
                           SG1,SG2,SG3,SG4,SG5,SG6,SG7,SG8,SG9,SG10,TROW,TAGNR)
               SELECT      KOD=A.KOD,PERSHKRIM=A.PERSHKRIM,KMON=A.KMON,MBARTUR=0,MBARTURMV=0,GJ=0,GJMV=0,
                           SG1=A.LLOGARIPK,SG2=A.KMON,SG3='',SG4='',SG5='',SG6='',SG7='',SG8='',SG9='',SG10='',TROW=0,TAGNR=0
                 FROM VSSCR A
                WHERE A.NRRENDOR=@PNRRENDOR


        INSERT INTO DAR (NRDITAR,KOD,PERSHKRIM,KOMENT,KMON,KURS1,KURS2,
                         TIPDOK,NRDOK,FRAKSDOK,DATEDOK,VLEFTA,
                         VLEFTAMV,TREGDK,NRLIBER,
                         TIPFAT,NRFAT,DTFAT,ISDOKSHOQ,KODMASTER,TROW,TAGNR)
        SELECT NRDITAR=A.NRDOK,KOD=B.KOD,PERSHKRIM=B.PERSHKRIM,KOMENT=B.KOMENT,KMON=B.KMON,KURS1=B.KURS1,KURS2=B.KURS2,
               TIPDOK='SP',NRDOK=A.NRDOK,FRAKSDOK=0,DATEDOK=A.DATEDOK,VLEFTA=(B.DB+B.KR),
               VLEFTAMV=CASE WHEN B.TREGDK='D' THEN B.DBKRMV ELSE -B.DBKRMV END,TREGDK=B.TREGDK,NRLIBER=ISNULL((SELECT TOP 1 NRRENDOR FROM LAR C WHERE C.KOD=B.KOD),0),
               TIPFAT=ISNULL(B.TIPREF,''),NRFAT=ISNULL(B.NRDOKREF,''),DTFAT=ISNULL(B.DATEDOKREF,A.DATEDOK),ISDOKSHOQ=0,KODMASTER=B.LLOGARIPK,TROW=0,TAGNR=0
          FROM VS A INNER JOIN VSSCR B ON A.NRRENDOR=B.NRD
         WHERE B.NRRENDOR=@PNRRENDOR 
        
        SET @VNRDITAR=@@IDENTITY
        
        UPDATE VSSCR SET NRDITAR=@VNRDITAR WHERE VSSCR.NRRENDOR=@PNRRENDOR
    END 

    --RASTI A NGA ARKA
    IF @PTABLENAME='ARKA'
      BEGIN
        SET @VNRDITAR=ISNULL((SELECT NRDITAR FROM ARKA WHERE ARKA.NRRENDOR=@PNRRENDOR),0)

        DELETE FROM DAR WHERE NRRENDOR=@VNRDITAR

        IF ISNULL((SELECT TOP 1 NRRENDOR FROM LAR A WHERE A.KOD=(SELECT B.KODAB+'.'+B.KMON FROM ARKA B WHERE B.NRRENDOR=@PNRRENDOR)),0)=0
          INSERT INTO LAR (KOD,PERSHKRIM,KMON,MBARTUR,MBARTURMV,GJ,GJMV,
                           SG1,SG2,SG3,SG4,SG5,SG6,SG7,SG8,SG9,SG10,TROW,TAGNR)
               SELECT      KOD=A.KODAB+'.'+A.KMON,PERSHKRIM=B.PERSHKRIM,KMON=A.KMON,MBARTUR=0,MBARTURMV=0,GJ=0,GJMV=0,
                           SG1=A.KODAB,SG2=A.KMON,SG3='',SG4='',SG5='',SG6='',SG7='',SG8='',SG9='',SG10='',TROW=0,TAGNR=0
                 FROM ARKA A INNER JOIN ARKAT B ON A.NRRENDORAB=B.NRRENDOR
                WHERE A.NRRENDOR=@PNRRENDOR


        INSERT INTO DAR (NRDITAR,KOD,PERSHKRIM,KOMENT,KMON,KURS1,KURS2,
                         TIPDOK,NRDOK,FRAKSDOK,DATEDOK,VLEFTA,
                         VLEFTAMV,TREGDK,NRLIBER,
                         TIPFAT,NRFAT,DTFAT,ISDOKSHOQ,KODMASTER,TROW,TAGNR)
        SELECT NRDITAR=A.NUMDOK,KOD=A.KODAB+'.'+A.KMON,PERSHKRIM=ISNULL(A.SHENIM1,''),KOMENT=ISNULL(A.SHENIM2,''),KMON=A.KMON,KURS1=A.KURS1,KURS2=A.KURS2,
               TIPDOK=A.TIPDOK,NRDOK=A.NUMDOK,FRAKSDOK=0,DATEDOK=A.DATEDOK,VLEFTA=A.VLERA,
               VLEFTAMV=A.VLERAMV,TREGDK=CASE WHEN TIPDOK='MA' THEN 'D' ELSE 'K' END,NRLIBER=ISNULL((SELECT TOP 1 NRRENDOR FROM LAR C WHERE C.KOD=A.KODAB+'.'+A.KMON),0),
               TIPFAT=A.TIPDOK,NRFAT=A.NUMDOK,DTFAT=A.DATEDOK,ISDOKSHOQ=0,KODMASTER=A.KODAB,TROW=0,TAGNR=0
          FROM ARKA A INNER JOIN ARKAT B ON A.NRRENDORAB=B.NRRENDOR
         WHERE A.NRRENDOR=@PNRRENDOR 
        
        SET @VNRDITAR=@@IDENTITY
        
        UPDATE ARKA SET NRDITAR=@VNRDITAR WHERE ARKA.NRRENDOR=@PNRRENDOR
    END 


END  

--FUND MODULI ARKA

ELSE
IF @PMODUL='B'
  BEGIN

    --RASTI NGA VS
    IF @PTABLENAME='VS'
      BEGIN
        SET @VNRDITAR=ISNULL((SELECT NRDITAR FROM VSSCR WHERE VSSCR.NRRENDOR=@PNRRENDOR),0)

        DELETE FROM DBA WHERE NRRENDOR=@VNRDITAR

        IF ISNULL((SELECT TOP 1 NRRENDOR FROM LBA A WHERE A.KOD=(SELECT KOD FROM VSSCR B WHERE B.NRRENDOR=@PNRRENDOR)),0)=0
          INSERT INTO LBA (KOD,PERSHKRIM,KMON,MBARTUR,MBARTURMV,GJ,GJMV,
                           SG1,SG2,SG3,SG4,SG5,SG6,SG7,SG8,SG9,SG10,TROW,TAGNR)
               SELECT      KOD=A.KOD,PERSHKRIM=A.PERSHKRIM,KMON=A.KMON,MBARTUR=0,MBARTURMV=0,GJ=0,GJMV=0,
                           SG1=A.LLOGARIPK,SG2=A.KMON,SG3='',SG4='',SG5='',SG6='',SG7='',SG8='',SG9='',SG10='',TROW=0,TAGNR=0
                 FROM VSSCR A
                WHERE A.NRRENDOR=@PNRRENDOR


        INSERT INTO DBA (NRDITAR,KOD,PERSHKRIM,KOMENT,KMON,KURS1,KURS2,
                         TIPDOK,NRDOK,FRAKSDOK,DATEDOK,VLEFTA,
                         VLEFTAMV,TREGDK,NRLIBER,
                         TIPFAT,NRFAT,DTFAT,ISDOKSHOQ,KODMASTER,TROW,TAGNR)
        SELECT NRDITAR=A.NRDOK,KOD=B.KOD,PERSHKRIM=B.PERSHKRIM,KOMENT=B.KOMENT,KMON=B.KMON,KURS1=B.KURS1,KURS2=B.KURS2,
               TIPDOK='SP',NRDOK=A.NRDOK,FRAKSDOK=0,DATEDOK=A.DATEDOK,VLEFTA=(B.DB+B.KR),
               VLEFTAMV=CASE WHEN B.TREGDK='D' THEN B.DBKRMV ELSE -B.DBKRMV END,TREGDK=B.TREGDK,NRLIBER=ISNULL((SELECT TOP 1 NRRENDOR FROM LBA C WHERE C.KOD=B.KOD),0),
               TIPFAT=ISNULL(B.TIPREF,''),NRFAT=ISNULL(B.NRDOKREF,''),DTFAT=ISNULL(B.DATEDOKREF,A.DATEDOK),ISDOKSHOQ=0,KODMASTER=B.LLOGARIPK,TROW=0,TAGNR=0
          FROM VS A INNER JOIN VSSCR B ON A.NRRENDOR=B.NRD
         WHERE B.NRRENDOR=@PNRRENDOR 
        
        SET @VNRDITAR=@@IDENTITY
        
        UPDATE VSSCR SET NRDITAR=@VNRDITAR WHERE VSSCR.NRRENDOR=@PNRRENDOR
    END 

    --RASTI B NGA BANKA
    IF @PTABLENAME='BANKA'
      BEGIN
        SET @VNRDITAR=ISNULL((SELECT NRDITAR FROM BANKA WHERE BANKA.NRRENDOR=@PNRRENDOR),0)

        DELETE FROM DBA WHERE NRRENDOR=@VNRDITAR

        IF ISNULL((SELECT TOP 1 NRRENDOR FROM LBA A WHERE A.KOD=(SELECT B.KODAB+'.'+B.KMON FROM BANKA B WHERE B.NRRENDOR=@PNRRENDOR)),0)=0
          INSERT INTO LBA (KOD,PERSHKRIM,KMON,MBARTUR,MBARTURMV,GJ,GJMV,
                           SG1,SG2,SG3,SG4,SG5,SG6,SG7,SG8,SG9,SG10,TROW,TAGNR)
               SELECT      KOD=A.KODAB+'.'+A.KMON,PERSHKRIM=B.PERSHKRIM,KMON=A.KMON,MBARTUR=0,MBARTURMV=0,GJ=0,GJMV=0,
                           SG1=A.KODAB,SG2=A.KMON,SG3='',SG4='',SG5='',SG6='',SG7='',SG8='',SG9='',SG10='',TROW=0,TAGNR=0
                 FROM BANKA A INNER JOIN BANKAT B ON A.NRRENDORAB=B.NRRENDOR
                WHERE A.NRRENDOR=@PNRRENDOR


        INSERT INTO DBA (NRDITAR,KOD,PERSHKRIM,KOMENT,KMON,KURS1,KURS2,
                         TIPDOK,NRDOK,FRAKSDOK,DATEDOK,VLEFTA,
                         VLEFTAMV,TREGDK,NRLIBER,
                         TIPFAT,NRFAT,DTFAT,ISDOKSHOQ,KODMASTER,TROW,TAGNR)
        SELECT NRDITAR=A.NUMDOK,KOD=A.KODAB+'.'+A.KMON,PERSHKRIM=ISNULL(A.SHENIM1,''),KOMENT=ISNULL(A.SHENIM2,''),KMON=A.KMON,KURS1=A.KURS1,KURS2=A.KURS2,
               TIPDOK=A.TIPDOK,NRDOK=A.NUMDOK,FRAKSDOK=0,DATEDOK=A.DATEDOK,VLEFTA=A.VLERA,
               VLEFTAMV=A.VLERAMV,TREGDK=CASE WHEN (TIPDOK='XK') OR (TIPDOK='AB') OR (TIPDOK='DB') THEN 'D' ELSE 'K' END,NRLIBER=ISNULL((SELECT TOP 1 NRRENDOR FROM LBA C WHERE C.KOD=A.KODAB+'.'+A.KMON),0),
               TIPFAT=A.TIPDOK,NRFAT=A.NUMDOK,DTFAT=A.DATEDOK,ISDOKSHOQ=0,KODMASTER=A.KODAB,TROW=0,TAGNR=0
          FROM BANKA A INNER JOIN BANKAT B ON A.NRRENDORAB=B.NRRENDOR
         WHERE A.NRRENDOR=@PNRRENDOR 
        
        SET @VNRDITAR=@@IDENTITY
        
        UPDATE BANKA SET NRDITAR=@VNRDITAR WHERE BANKA.NRRENDOR=@PNRRENDOR
    END 

END  
--FUND MODULI BANKA








GO
