SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO







CREATE       procedure [dbo].[ZZ_UpdateKMAG]
(
@KMAGOLD AS VARCHAR(3),
@KMAGNEW AS VARCHAR(3)
)
AS

UPDATE MAGAZINA SET KOD=@KMAGNEW WHERE KOD=@KMAGOLD

UPDATE FH  SET KMAG=@KMAGNEW WHERE KMAG=@KMAGOLD;
UPDATE FHSCR
   SET KOD=@KMAGNEW+RIGHT(KOD,LEN(KOD)-LEN(@KMAGOLD))
 WHERE LEFT(KOD,LEN(@KMAGOLD)+1)=@KMAGOLD+'.'

UPDATE FD  SET KMAG=@KMAGNEW WHERE KMAG=@KMAGOLD;
UPDATE FDSCR
   SET KOD=@KMAGNEW+RIGHT(KOD,LEN(KOD)-LEN(@KMAGOLD))
 WHERE LEFT(KOD,LEN(@KMAGOLD)+1)=@KMAGOLD+'.'

UPDATE FJ  SET KMAG=@KMAGNEW WHERE KMAG=@KMAGOLD;
UPDATE FJSCR
   SET KOD=@KMAGNEW+RIGHT(KOD,LEN(KOD)-LEN(@KMAGOLD))
 WHERE LEFT(KOD,LEN(@KMAGOLD)+1)=@KMAGOLD+'.' AND TIPKLL='K'

UPDATE FF  SET KMAG=@KMAGNEW WHERE KMAG=@KMAGOLD
UPDATE FFSCR
   SET KOD=@KMAGNEW+RIGHT(KOD,LEN(KOD)-LEN(@KMAGOLD))
 WHERE TIPKLL='K' AND LEFT(KOD,LEN(@KMAGOLD)+1)=@KMAGOLD+'.'

UPDATE OFK SET KMAG=@KMAGNEW WHERE KMAG=@KMAGOLD
UPDATE OFKSCR
   SET KOD=@KMAGNEW+RIGHT(KOD,LEN(KOD)-LEN(@KMAGOLD))
 WHERE TIPKLL='K' AND LEFT(KOD,LEN(@KMAGOLD)+1)=@KMAGOLD+'.'

UPDATE ORF SET KMAG=@KMAGNEW WHERE KMAG=@KMAGOLD
UPDATE ORFSCR
   SET KOD=@KMAGNEW+RIGHT(KOD,LEN(KOD)-LEN(@KMAGOLD))
 WHERE TIPKLL='K' AND LEFT(KOD,LEN(@KMAGOLD)+1)=@KMAGOLD+'.'

UPDATE ORK SET KMAG=@KMAGNEW WHERE KMAG=@KMAGOLD
UPDATE ORKSCR
   SET KOD=@KMAGNEW+RIGHT(KOD,LEN(KOD)-LEN(@KMAGOLD))
 WHERE TIPKLL='K' AND LEFT(KOD,LEN(@KMAGOLD)+1)=@KMAGOLD+'.'

UPDATE FJT SET KMAG=@KMAGNEW WHERE KMAG=@KMAGOLD
UPDATE FJTSCR
   SET KOD=@KMAGNEW+RIGHT(KOD,LEN(KOD)-LEN(@KMAGOLD))
 WHERE TIPKLL='K' AND LEFT(KOD,LEN(@KMAGOLD)+1)=@KMAGOLD+'.'

UPDATE SM SET KMAG=@KMAGNEW WHERE KMAG=@KMAGOLD
UPDATE SMSCR
   SET KOD=@KMAGNEW+RIGHT(KOD,LEN(KOD)-LEN(@KMAGOLD))
 WHERE TIPKLL='K' AND LEFT(KOD,LEN(@KMAGOLD)+1)=@KMAGOLD+'.'






GO
