SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[Isd_GatiFiskalPdf]
(
 @pNrRendor Integer
)
AS
BEGIN
	SET NOCOUNT ON;
    


	DECLARE @EIC VARCHAR(MAX)
	DECLARE @OUTPUT1 VARCHAR(MAX)
	DECLARE @DATEDOK DATETIME

	SET @EIC=(SELECT FISEIC FROM FJ WHERE NRRENDOR=@pNrRendor)
	SET @DATEDOK=(SELECT DATEDOK FROM FJ WHERE NRRENDOR=@pNrRendor)
	EXEC __eInvoiceGetRequest @EIC,'SELLER',@DATEDOK,@DATEDOK,@pNrRendor,@OUTPUT1 OUT

	
END
GO
