SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROC [dbo].[CheckBarcodeForOffer]
	@BARCODE AS VARCHAR(50)
AS
BEGIN
	IF (SELECT COUNT(1)  FROM KUPONA 
	WHERE NRKUPON = @BARCODE
	  AND DNGA   <=GETDATE()
	  AND DDERI  >=GETDATE()
	  AND AKTIV  = 1)>=1

	BEGIN

	--	SELECT TOP 1 
	--			@VALUE			= VALUE,
	--			@ISPERCENTAGE	= ISPERCENTAGE,
	--			@NRRENDOR		= NRRENDOR
	--	FROM KUPONA 
	--	WHERE NRKUPON = @BARCODE
	--  AND DNGA   <=GETDATE()
	--  AND DDERI  >=GETDATE()
	--  AND AKTIV  = 1
  
	--UPDATE KUPONA SET AKTIV = 0 WHERE NRRENDOR = @NRRENDOR

		SELECT NRKUPON, VALUE, ISPERCENTAGE, NRRENDOR
		FROM KUPONA
		WHERE NRKUPON = @BARCODE
		  AND DNGA   <=GETDATE()
		  AND DDERI  >=GETDATE()
		  AND AKTIV  = 1;
	END
END
GO
