SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE procedure [dbo].[IMPORT](@DESTINACION AS NVARCHAR(30))
as
--DEKLARATAT E VARIABLAVE
DECLARE @KOD AS INT;
DECLARE @PERSHKRIM AS INT
DECLARE @INSTC AS NVARCHAR(50);
DECLARE @NDERM AS NVARCHAR(100);
DECLARE @QUERY AS NVARCHAR(4000);

	--DELETE FK/FKSCR
	DELETE FROM FK;
	DELETE FROM FKSCR;	
	
	--KURSORI QE BREDH NDERMARRJET QE DO KOPJOHEN
	DECLARE JOBSET CURSOR FOR
	select KOD,PERSHKRIM from DRH.DBO.NDERMARRJE
	
	OPEN JOBSET
	FETCH NEXT FROM JOBSET into @KOD,@PERSHKRIM

	WHILE @@FETCH_STATUS = 0
	BEGIN

		--KOPIM FK		
		SET @QUERY = 'INSERT INTO '+@DESTINACION+'.DBO.FK([KODNENDITAR], [NRDFK], 
				[NRDOK], [DATEDOK], [PERSHKRIM1], [PERSHKRIM2], [KMON], [KURS1], 
				[KURS2], [POSTIM], [LETER], [ORG], [FIRSTDOK], [TIPDOK], [NUMDOK], 
				[REFERDOK], [KMAG], [FORMAT], [KLASIFIKIM], [USI], [USM], [TROW], [TAGNR])
				SELECT  [KODNENDITAR], [NRDFK], [NRDOK], [DATEDOK], [PERSHKRIM1], [PERSHKRIM2], 
				[KMON], [KURS1], [KURS2], [POSTIM], [LETER], [ORG], [FIRSTDOK], [TIPDOK], 
				[NUMDOK], [REFERDOK], [KMAG], [FORMAT], [KLASIFIKIM], [USI], [USM], 
				[TROW], [NRRENDOR] FROM ['+@KOD+'].[dbo].[FK]';
		EXEC SP_EXECUTESQL @QUERY;
		
		--KOPIM FKSCR
		SET @QUERY = 'INSERT INTO '+@DESTINACION+'.DBO.FKSCR( 
				[NRD], [KOD], [LLOGARI], [LLOGARIPK], [PERSHKRIM], [KOMENT], [KMON], [KURS1], 
				[KURS2], [DB], [KR], [DBKRMV], [TREGDK], [TAG], [ORDPOST], [TROW], [TAGNR]) 
				SELECT  [NRD], [KOD], [LLOGARI], [LLOGARIPK], [PERSHKRIM], [KOMENT], 
				[KMON], [KURS1], [KURS2], [DB], [KR], [DBKRMV], [TREGDK], [TAG], [ORDPOST], 
				[TROW], NRD FROM ['+@KOD+'].[dbo].[FKSCR]';
		EXEC SP_EXECUTESQL @QUERY;
		
		--LIDHJA NDERMJET FK<-->FKSCR
		UPDATE FKSCR SET NRD = (SELECT NRRENDOR FROM FK WHERE FK.TAGNR = FKSCR.TAGNR 
					AND TAGNR <> 0) WHERE TAGNR<>0;	
		
		--PREGATITJA E TAGNR PER NDERMARJEN TJETER
		UPDATE FK SET TAGNR = 0;
		UPDATE FKSCR SET TAGNR =0;

		FETCH NEXT FROM JOBSET into @KOD,@PERSHKRIM
	END
CLOSE JOBSET;
DEALLOCATE JOBSET;

GO
