SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[P_LISTA_ART_LEFT_ARTWEB] AS
 SELECT A.KOD,A.BC,A.PERSHKRIM,A.KLASIF,A.KLASIF2,A.KLASIF3,A.KLASIF4,A.KLASIF5,A.KLASIF6,A.CMB,
 A.cmsh,A.CMSH1,A.CMSH2,A.CMSH3,A.CMSH4,A.CMSH5,A.CMSH6,A.CMSH7,A.CMSH8,A.CMSH9,
 ISNULL(AW.IMAZHPATH,'X') AS KAIMAZH,ISNULL(AW.KOD,'X') AS KASKEME FROM ARTIKUJ a
 LEFT JOIN UPDART.DBO.ARTWEB AW ON AW.KOD=A.KOD
GO
