SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [RS].[SP_CalculateCustomDateValues_MC]
AS 
BEGIN
	
	DECLARE @SQL NVARCHAR(MAX),
			@RowID INT,
			@DBNAME VARCHAR(10)


	DECLARE DB_CURSOR CURSOR FOR
	SELECT RowID,DBNAME=MAX(CASE WHEN (ISNULL(DBNAME,'')='') OR (DB_ID(DBNAME) IS NULL) THEN DB_NAME() ELSE DBNAME END)
	FROM ##RAP_ROWS
	WHERE ISNULL(CUSTOM_DATE,0)<>0
	GROUP BY RowID

	OPEN DB_CURSOR;
	FETCH NEXT FROM DB_CURSOR INTO @RowID,@DBNAME

	WHILE @@FETCH_STATUS=0
	BEGIN
		SET @SQL=N'
					UPDATE ##RAP_ROWS 
							SET VALUE=(
											SELECT VALUE=SUM(CASE WHEN L.AKTPASIV=''A'' THEN DBKRMV ELSE 0-DBKRMV END)
											FROM ['+@DBNAME+']..FK
											INNER JOIN ['+@DBNAME+']..FKSCR ON FKSCR.NRD=FK.NRRENDOR
											INNER JOIN ['+@DBNAME+'].RS.CellLlogs SCL ON SCL.Kod=FKSCR.LLOGARIPK
											INNER JOIN ['+@DBNAME+']..LLOGARI L ON L.KOD=FKSCR.LLOGARIPK
											WHERE DATEDOK <=##RAP_ROWS.CUSTOM_DATE
											AND SCL.CellID=##RAP_ROWS.CellID
									   )

					WHERE RowID=@RowID AND ISNULL(IsValue,0)=0'
		EXEC sp_executesql @SQL,N'@RowID INT OUTPUT',@RowID OUTPUT
		
		FETCH NEXT FROM DB_CURSOR INTO @RowID,@DBNAME	
	END	
	CLOSE DB_CURSOR;
	DEALLOCATE DB_CURSOR; 
END
GO
