SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [RS].[SP_CalculateFormuleRow_MC]
@RowID INT
AS
BEGIN
	--DECLARE @RowID int=596 --RESHTI FORMULE  SELECT * FROM RS.CONFIG


	DECLARE @CellID INT,
			@R_ID INT,
			@fRowID INT,--RowID
			@fColID INT,--ColID
			@fCellID INT,--ColID
			@CellValue FLOAT,
			@SQL NVARCHAR(MAX),
			@FORMULE VARCHAR(100),
			@F VARCHAR(100),
			@F_VALUE VARCHAR(500), --FORMULA ME VLERA PSH. 0.5+[51]==>0.5*40=2, SHENIM: supozojme se [51]=40
			@TEMP_STR VARCHAR(100)

	SELECT
		@F=MAX(Formula)
	FROM ##RAP_ROWS
	WHERE RowID=@RowID

	

	DECLARE DB_CURSOR CURSOR FOR
	SELECT 
		RowID,ColID,CellID
	FROM ##RAP_ROWS
	WHERE RowID=@RowID AND ISNULL(IsValue,0)=0 --nqs nuk eshte vlere manueale,

	OPEN DB_CURSOR;
	FETCH NEXT FROM DB_CURSOR INTO @fRowID,@fColID,@fCellID

	WHILE @@FETCH_STATUS=0
	BEGIN
		SET @F_VALUE=@F
		SET @FORMULE=@F
		WHILE CHARINDEX('[',@FORMULE)<>0
		BEGIN
			SET @TEMP_STR=SUBSTRING(@Formule, CHARINDEX('[', @Formule), CHARINDEX(']',@Formule) - CHARINDEX('[', @Formule) + Len(']'))
			SET @R_ID=REPLACE(REPLACE(@TEMP_STR,'[',''),']','')	
			 
			SELECT @CellValue=ISNULL(Value,0) FROM ##RAP_ROWS WHERE RowID=@R_ID AND ColID=@fColID

			SET @F_VALUE=REPLACE(@F_VALUE,@TEMP_STR,CAST(@CellValue AS VARCHAR))

			SET @Formule=REPLACE(@Formule,@TEMP_STR,'')
		END
    SET @SQL=N'UPDATE ##RAP_ROWS SET Value='+@F_VALUE+' WHERE CellID='+CAST(@fCellID AS VARCHAR)
	Exec  sp_executesql @SQL

	FETCH NEXT FROM DB_CURSOR INTO @fRowID,@fColID,@fCellID
	END
	CLOSE DB_CURSOR;
	DEALLOCATE DB_CURSOR;

END
GO
