SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [RS].[SP_CALCULATE_TOT_ROWS_MC]
AS
BEGIN
UPDATE ##RAP_ROWS
	SET Value=B.Value
From ##RAP_ROWS A 
INNER JOIN 
	(
		SELECT RowID=B.RowID,ColID=A.ColID,Value=SUM(A.Value)
		FROM ##RAP_ROWS A
		INNER JOIN RS.TotRows B ON A.RowID=B.TotRowID
		GROUP BY B.RowID,ColID
	)AS B ON A.RowID=B.RowID AND A.ColID=B.ColID
WHERE ISNULL(IsValue,0)=0
END
GO
