CREATE TABLE [dbo].[FJPG]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[NRD] [int] NULL,
[KMONSHL] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KURSSHL] [float] NULL,
[VLEFTESHL] [float] NULL,
[VLEFTESHLMV] [float] NULL,
[VLEFTESHLFAT] [float] NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL,
[STATROW] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORDERSCR] [int] NULL CONSTRAINT [DF_FJPG_ORDERSCR] DEFAULT ((0))
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [NRD_FJPG] ON [dbo].[FJPG] ([NRD]) ON [PRIMARY]
GO
