CREATE TABLE [dbo].[OBJECTSLINK]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[NRD] [int] NULL,
[PERSHKRIM] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TABELA] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OBJEKT] [image] NULL,
[OBJEKTPATHLOCATION] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OBJEKTPATHLOADED] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OBJEKTEXT] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NOTACTIV] [bit] NULL,
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATECREATE] [datetime] NULL CONSTRAINT [DF_OLN_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_OLN_DATEEDIT] DEFAULT (getdate()),
[TROW] [bit] NULL,
[TAGNR] [int] NULL,
[PDFOBJEKT] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PDFOBJEKTPATHLOCATION] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PDFOBJEKTPATHLOADED] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PDFOBJEKTEXT] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
