CREATE TABLE [dbo].[FJTPG]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[NRD] [int] NULL,
[KMONSHL] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KURSSHL] [float] NULL,
[VLEFTESHL] [float] NULL,
[VLEFTESHLMV] [float] NULL,
[VLEFTESHLFAT] [float] NULL,
[STATROW] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORDERSCR] [int] NULL CONSTRAINT [DF_FJTPG_ORDERSCR] DEFAULT ((0)),
[TROW] [bit] NULL,
[TAGNR] [int] NULL
) ON [PRIMARY]
GO
