CREATE TABLE [dbo].[AQKartela]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[KOD] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIMSH] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NJESI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KATEGORI] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRUP] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NOTACTIV] [bit] NULL,
[DTBL] [datetime] NULL,
[CMIMBL] [float] NULL,
[VLERABL] [float] NULL,
[DTPERD] [datetime] NULL,
[DTCE] [datetime] NULL,
[VLERACE] [float] NULL,
[VLERAAMCE] [float] NULL,
[DTSH] [datetime] NULL,
[VLERASH] [float] NULL,
[VLERAAMSH] [float] NULL,
[DTAM] [datetime] NULL,
[VLERAAM] [float] NULL,
[VLERAAMCUM] [float] NULL,
[SKEMEAM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODLM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERDORUES] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VENDNDODH] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DHURATE] [bit] NULL,
[FURNITOR] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MODEL] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MODELNR] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SERIALNR] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BC] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODFIN] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEP] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LIST] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VLERABLMON] [float] NULL,
[KOMENT] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAGNR] [int] NULL,
[TROW] [bit] NULL,
[KMAG] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KMON] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF5] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF6] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATECREATE] [datetime] NULL CONSTRAINT [DF_AQKartela_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_AQKartela_DATEEDIT] DEFAULT (getdate()),
[AQSTATUS] [int] NULL,
[AQSTATUSDATE] [datetime] NULL,
[KODORIGJINE] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AMDATESTART] [datetime] NULL,
[AMDATESTARTAPLIKIM] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [@KOD_AQKartela] ON [dbo].[AQKartela] ([KOD]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [@NRRENDOR_AQKartela] ON [dbo].[AQKartela] ([NRRENDOR]) ON [PRIMARY]
GO
