CREATE TABLE [dbo].[USER_FORM_FILTERS]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[USERNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FORM_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FILTER_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FILTER_DATA] [varbinary] (max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[USER_FORM_FILTERS] ADD CONSTRAINT [PK__USER_FOR__2E8B20C7787FB0F7] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
