CREATE TABLE [dbo].[ISD]
(
[BC] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SASIA] [float] NULL,
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ISD] ADD CONSTRAINT [PK__ISD__2E8B20C7324898F0] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
