CREATE TABLE [dbo].[X_TMPTABLES]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[TABLENORG] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TABLENDST] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LISTFIELDN] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SQLTEXT] [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTIV] [bit] NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
