CREATE TABLE [dbo].[DGSCR]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[NRD] [int] NULL,
[TATIM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KARTLLG] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIMKLL] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NJESI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KMON] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SASI] [float] NULL,
[CMIMDSH] [float] NULL,
[CMIMBS] [float] NULL,
[PERQTVSH] [float] NULL,
[KURS1] [float] NULL,
[KURS2] [float] NULL,
[TIPKLL] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VLERATAT] [float] NULL,
[VLERATAX] [float] NULL,
[KOMENT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL,
[APLINVESTIM] [bit] NULL,
[CMRIMBURSIM] [float] NULL,
[VLRIMBURSIM] [float] NULL,
[ORDERSCR] [int] NULL,
[STATROW] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAGRND] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISNOTFIRO] [bit] NULL,
[GARANCI] [int] NULL,
[KODKLF] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [{DD5D4E81-CE06-4A8F-8630-8B8D8B4327C3}] ON [dbo].[DGSCR] ([NRD]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [@NRD_DGSCR] ON [dbo].[DGSCR] ([NRRENDOR], [NRD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DGSCR] WITH NOCHECK ADD CONSTRAINT [FK_DGSCR_DG] FOREIGN KEY ([NRD]) REFERENCES [dbo].[DG] ([NRRENDOR]) ON DELETE CASCADE ON UPDATE CASCADE
GO
