CREATE TABLE [dbo].[FK]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[KODNENDITAR] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRDFK] [bigint] NULL,
[NRDOK] [bigint] NULL,
[DATEDOK] [datetime] NULL,
[PERSHKRIM1] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM2] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KMON] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KURS1] [float] NULL,
[KURS2] [float] NULL,
[POSTIM] [bit] NULL,
[LETER] [bit] NULL,
[ORG] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIRSTDOK] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIPDOK] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMDOK] [bigint] NULL,
[REFERDOK] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KMAG] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FORMAT] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIFIKIM] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL,
[EXTEXPKOMENT] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTIMPKOMENT] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANNUMBER] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DST] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KONFIRM] [bit] NULL,
[EXTIMPID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTEXP] [bit] NULL,
[DATECREATE] [datetime] NULL CONSTRAINT [DF_FK_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_FK_DATEEDIT] DEFAULT (getdate()),
[TAGRND] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOBCREATE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIME] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [@NRRENDOR_FK] ON [dbo].[FK] ([NRRENDOR]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [NUMDOK] ON [dbo].[FK] ([NUMDOK]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [@ORIGJINE_FK] ON [dbo].[FK] ([ORG], [DATEDOK]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [@NRDOK] ON [dbo].[FK] ([ORG], [DATEDOK], [NRDOK]) ON [PRIMARY]
GO
