CREATE TABLE [dbo].[AQKategori]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[KOD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIFIKIM] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAGNR] [int] NULL,
[TROW] [bit] NULL,
[NORMEAM] [float] NULL,
[NRTIMEAM] [int] NULL,
[AMVLEREMBET] [bit] NULL,
[NORMEAM2] [float] NULL,
[NRTIMEAM2] [int] NULL,
[ACTIVAM2] [bit] NULL,
[AMVLEREMBET2] [bit] NULL,
[NOTACTIV] [bit] NULL,
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATECREATE] [datetime] NULL CONSTRAINT [DF_AQKATEGORI_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_AQKATEGORI_DATEEDIT] DEFAULT (getdate()),
[VLEREMINAM] [float] NULL,
[PERQINDMINAM] [float] NULL,
[APLVLEREMINAM] [int] NULL,
[VLEREMINAM2] [float] NULL,
[PERQINDMINAM2] [float] NULL,
[APLVLEREMINAM2] [int] NULL
) ON [PRIMARY]
GO
