CREATE TABLE [dbo].[SEGMENTE]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[PERSHKRIM] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VLNGA] [float] NOT NULL CONSTRAINT [DF_SEGMENTE_VLNGA] DEFAULT ((0)),
[VLDERI] [float] NOT NULL CONSTRAINT [DF_SEGMENTE_VLDERI] DEFAULT ((0)),
[LIMIT] [float] NOT NULL CONSTRAINT [DF_SEGMENTE_LIMIT] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SEGMENTE] ADD CONSTRAINT [PK_SEGMENTE] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
