CREATE TABLE [dbo].[pagesaPOS]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[NRDSM] [int] NULL,
[KODAB] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHAB] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MONEDHE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VLERE] [float] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[pagesaPOS] ADD CONSTRAINT [PK_pagesaPOS] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
