CREATE TABLE [dbo].[DGA]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[NRRENDORSM] [int] NOT NULL,
[VOUCHER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SMARTCARD] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DGA] ADD CONSTRAINT [PK__DGA__2E8B20C76AC1FC3D] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
