CREATE TABLE [dbo].[GrumbullimScr]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[NRD] [int] NULL,
[KOD] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODAF] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODAGJ] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIMAGJ] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SASI01_GR] [float] NULL,
[SASI02_GR] [float] NULL,
[SASI03_GR] [float] NULL,
[SASI04_GR] [float] NULL,
[SASI01_PR] [float] NULL,
[SASI02_PR] [float] NULL,
[SASI03_PR] [float] NULL,
[SASI04_PR] [float] NULL,
[SASI01_DF] [float] NULL,
[SASI02_DF] [float] NULL,
[SASI03_DF] [float] NULL,
[SASI04_DF] [float] NULL,
[TOTAL_GR] [float] NULL,
[TOTAL_PR] [float] NULL,
[TOTAL_DF] [float] NULL,
[NIPTActiv] [bit] NULL,
[NRORDER] [int] NULL,
[KODORDER] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIPKLL] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRROW] [int] NULL,
[STATROW] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORDERSCR] [int] NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL,
[CMIM01] [float] NULL,
[CMIM02] [float] NULL,
[CMIM03] [float] NULL,
[CMIM04] [float] NULL,
[GETSASI] [bit] NULL CONSTRAINT [DF_GrumbullimScr_GETSASI] DEFAULT ((0)),
[NotDocumentFat] [bit] NULL,
[DATESTART] [datetime] NULL,
[DATEEND] [datetime] NULL,
[DAYDIFF] [int] NULL
) ON [PRIMARY]
GO
