CREATE TABLE [dbo].[VENDNDODHJE]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[KOD] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIFIKIM] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL,
[KOEFICENT] [float] NULL CONSTRAINT [DF_VENDNDODHJE_KOEFICENT] DEFAULT ((0)),
[NOTACTIV] [bit] NULL CONSTRAINT [DF_VENDNDODHJE_NOTACTIV] DEFAULT ((0)),
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATECREATE] [datetime] NULL CONSTRAINT [DF_VND_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_VND_DATEEDIT] DEFAULT (getdate()),
[KODCOUNTRY] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [KOD_VEN] ON [dbo].[VENDNDODHJE] ([KOD]) ON [PRIMARY]
GO
