CREATE TABLE [dbo].[KlasaTatim]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[KOD] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERQINDJE] [float] NULL CONSTRAINT [DF_KLASATATIM_PERQINDJE] DEFAULT ((0)),
[TIP] [int] NULL,
[LLOGARIDB] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LLOGARIKR] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIFIKIM] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NOTACTIV] [bit] NULL,
[DATECREATE] [datetime] NULL CONSTRAINT [DF_KTA_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_KTA_DATEEDIT] DEFAULT (getdate()),
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL,
[KODTVSHFIC] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODTVSHEIC] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[KlasaTatim] ADD CONSTRAINT [PK_KLASATATIM] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
