CREATE TABLE [dbo].[TABLESLINK]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[TABLENAME] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TABLEFIELD] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REFERTABLE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REFERFIELD] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REFERWHERE] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIELDEMPTY] [bit] NULL,
[ERRORMSG] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL
) ON [PRIMARY]
GO
