CREATE TABLE [dbo].[CONFIGSP]
(
[NRRENDOR] [int] NULL,
[ARTKLTIT] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARTKL1PR] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARTKL1KP] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARTKL1KS] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARTKL1GR] [int] NULL,
[ARTKL2PR] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARTKL2KP] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARTKL2KS] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARTKL2GR] [int] NULL,
[ARTKL3PR] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARTKL3KP] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARTKL3KS] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARTKL3GR] [int] NULL,
[ARTKL4PR] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARTKL4KP] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARTKL4KS] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARTKL4GR] [int] NULL,
[MAGKLTIT] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAGKL1PR] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAGKL1KP] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAGKL1KS] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAGKL2PR] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAGKL2KP] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAGKL2KS] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAGKL3PR] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAGKL3KP] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAGKL3KS] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAGKL4PR] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAGKL4KP] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAGKL4KS] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLIKLTIT] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLIKL1PR] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLIKL1KP] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLIKL1KS] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLIKL2PR] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLIKL2KP] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLIKL2KS] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLIKL3PR] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLIKL3KP] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLIKL3KS] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLIKL4PR] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLIKL4KP] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLIKL4KS] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOKKLTIT] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOKKL1PR] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOKKL1KP] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOKKL1KS] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOKKL2PR] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOKKL2KP] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOKKL2KS] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOKKL3PR] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOKKL3KP] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOKKL3KS] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOKKL4PR] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOKKL4KP] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOKKL4KS] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAGNR] [int] NULL,
[TROW] [bit] NULL
) ON [PRIMARY]
GO
