CREATE TABLE [dbo].[GJENDJEARTIKULL]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[KODMAG] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_GJENDJEARTIKULL_KODMAG] DEFAULT ((-1)),
[KODART] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_GJENDJEARTIKULL_KODART] DEFAULT ((-1)),
[SASIMIN] [float] NOT NULL CONSTRAINT [DF_GJENDJEARTIKULL_SASIMIN] DEFAULT ((-1)),
[SASIMES] [float] NOT NULL CONSTRAINT [DF_GJENDJEARTIKULL_SASIMES] DEFAULT ((-1)),
[SASIMAX] [float] NOT NULL CONSTRAINT [DF_GJENDJEARTIKULL_SASIMAX] DEFAULT ((-1)),
[TAGNR] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GJENDJEARTIKULL] ADD CONSTRAINT [PK_GJENDJEARTIKULL] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
