CREATE TABLE [dbo].[NIPT]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[KOD] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NIPT] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADRESA1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADRESA2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADRESA3] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIPNJESI] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LLOJBIZNES] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RRETHI] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OBJEKT] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERFAQESUES] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TELEFON1] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TELEFON2] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAX] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODPOSTAR] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LLOGARIBANKE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIFIKIM1] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIFIKIM2] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMAIL] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INTERNET] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRUP] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KATEGORI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VENDNDODHJE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RAJON] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODFISKAL] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRLICENCE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NIPTCERTIFIKATE] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODBASHKI] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODF5] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTIV] [bit] NULL,
[NOTACTIV] [bit] NULL,
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATECREATE] [datetime] NULL CONSTRAINT [DF_NPT_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_NPT_DATEEDIT] DEFAULT (getdate()),
[TROW] [bit] NULL,
[TAGNR] [int] NULL
) ON [PRIMARY]
GO
