CREATE TABLE [dbo].[LLOGARI1]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[KOD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUP] [int] NULL,
[NIV] [int] NULL,
[PERSHKRIM] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASA] [int] NULL,
[POZIC] [bit] NULL,
[TIPI] [int] NULL,
[AKTPASIV] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USI] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAG] [bit] NULL,
[ORIGJINA] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VEPRIMLM] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LLOGARI1] ADD CONSTRAINT [PK__LLOGARI1__2E8B20C7081D54FA] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [@KOD_LLOGARI] ON [dbo].[LLOGARI1] ([KOD]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [@NRRENDOR_LLOGARI] ON [dbo].[LLOGARI1] ([NRRENDOR]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ORIGJINA] ON [dbo].[LLOGARI1] ([ORIGJINA], [KOD]) ON [PRIMARY]
GO
