CREATE TABLE [dbo].[AFLISTE]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[KOD] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QUERY] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRID] [image] NULL,
[TAGNR] [int] NULL,
[TROW] [bit] NULL,
[NRORDER] [int] NULL,
[DOKDST] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOKORG] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WHERECONST] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WHERENEW] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROMPTLIST] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
