CREATE TABLE [dbo].[KlientCmim]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[KOD] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTIV] [bit] NULL,
[DATESTART] [datetime] NULL,
[DATEEND] [datetime] NULL,
[SHENIME] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOEFICENT1] [float] NULL,
[ZGJIDH] [bit] NULL,
[NOTACTIV] [bit] NULL,
[DATECREATE] [datetime] NULL CONSTRAINT [DF_KLC_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_KLC_DATEEDIT] DEFAULT (getdate()),
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[KlientCmim] ADD CONSTRAINT [PK_KlientCmim] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [Kodi] ON [dbo].[KlientCmim] ([KOD]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [Nrrendori] ON [dbo].[KlientCmim] ([NRRENDOR]) ON [PRIMARY]
GO
