CREATE TABLE [dbo].[BUXHET]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[LLOGARI_KOD] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEPARTAMENT_KOD] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LISTE_KOD] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAGAZINA_KOD] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BUXHET_KOD] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VLERA] [float] NULL,
[DATA] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BUXHET] ADD CONSTRAINT [PK_BUXHET_LIST] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
