CREATE TABLE [dbo].[INVENTAR_ART]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[KOD] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BC] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SASI_ISHTE] [float] NULL,
[SASI] [float] NULL,
[DATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INVENTAR_ART] ADD CONSTRAINT [PK_INVENTAR_ART] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
