CREATE TABLE [dbo].[SMTEMP]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[DATEDOK] [datetime] NULL,
[KTH] [bit] NULL,
[NRDOK] [float] NULL,
[NRFRAKS] [int] NULL,
[KOD] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODFKL] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KMON] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASAKF] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KASE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VENHUAJ] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NIPT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRSERIAL] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODFISKAL] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RRETHI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM1] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM2] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM3] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM4] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRDSHOQ] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTDSHOQ] [datetime] NULL,
[NRRENDDMG] [int] NULL,
[TIPDMG] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRMAG] [int] NULL,
[KMAG] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRDMAG] [float] NULL,
[FRDMAG] [int] NULL,
[DTDMAG] [datetime] NULL,
[MODPG] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTAF] [int] NULL,
[DTDS] [int] NULL,
[PERQDS] [float] NULL,
[KURS1] [float] NULL,
[KURS2] [float] NULL,
[VLPATVSH] [float] NULL,
[VLTVSH] [float] NULL,
[VLERZBR] [float] NULL,
[VLERTOT] [float] NULL,
[PARAPG] [float] NULL,
[PERQTVSH] [float] NULL,
[PERQZBR] [float] NULL,
[LLOGTVSH] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LLOGZBR] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LLOGARK] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRDFK] [int] NULL,
[NRDITAR] [int] NULL,
[POSTIM] [bit] NULL,
[LETER] [bit] NULL,
[FIRSTDOK] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISDG] [bit] NULL,
[NRDOKDG] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTDOKDG] [datetime] NULL,
[TAGNR] [int] NULL,
[NRDITARSHL] [int] NULL,
[NRRENDKF] [int] NULL,
[NRFRAKSKF] [int] NULL,
[NRDFTEXTRA] [int] NULL,
[ISDOKSHOQ] [bit] NULL,
[NRRENDOROF] [int] NULL,
[NRRENDOROR] [int] NULL,
[TIMED] [datetime] NULL,
[KLASIFIKIM] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USI] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAG] [bit] NULL,
[TROW] [bit] NULL,
[VLTAX] [float] NULL,
[PGKLIENT] [float] NULL,
[KLIENTID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KARTE] [float] NOT NULL CONSTRAINT [DF_SMTEMP_KARTE] DEFAULT ((0)),
[PIKE] [float] NOT NULL CONSTRAINT [DF_SMTEMP_PIKE] DEFAULT ((0)),
[LASTMODIF] [datetime] NOT NULL CONSTRAINT [DF_SMTEMP_LASTMODIF] DEFAULT (getdate()),
[NRDSKONTO] [int] NOT NULL CONSTRAINT [DF_SMTEMP_NRDSKONTO] DEFAULT ((-1)),
[EMERKOMP] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SMTEMP] ADD CONSTRAINT [PK_SMTEMP] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
