CREATE TABLE [dbo].[LLOGARISKK]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[KOD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUP] [int] NULL,
[NIV] [int] NULL,
[PERSHKRIM] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM1] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASA] [int] NULL,
[POZIC] [bit] NULL,
[TIPI] [int] NULL,
[AKTPASIV] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USI] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAG] [bit] NULL,
[ORIGJINA] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODSKK] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODORG] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VEPRIMLM] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LLOGARISKK] ADD CONSTRAINT [PK__LLOGARIS__2E8B20C70DD62E50] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [KODLLGSKK] ON [dbo].[LLOGARISKK] ([KOD]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [KODORGLLGSKK] ON [dbo].[LLOGARISKK] ([KODORG]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [NRRENDORLLGSKK] ON [dbo].[LLOGARISKK] ([NRRENDOR]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ORRIGJINALLGSKK] ON [dbo].[LLOGARISKK] ([ORIGJINA]) ON [PRIMARY]
GO
