CREATE TABLE [dbo].[NENDITAR]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[KOD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IE] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MINIMAL] [int] NULL,
[MAKSIMAL] [int] NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL,
[NOTACTIV] [bit] NULL,
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATECREATE] [datetime] NULL CONSTRAINT [DF_NND_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_NND_DATEEDIT] DEFAULT (getdate())
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [KOD] ON [dbo].[NENDITAR] ([KOD]) ON [PRIMARY]
GO
