CREATE TABLE [dbo].[SHERBIM]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[PERSHKRIM] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOD] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIFIKIM] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NJESI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMSH] [float] NULL,
[CMSH1] [float] NULL,
[CMSH2] [float] NULL,
[CMSH3] [float] NULL,
[DSCNTKLA] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLB] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLC] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLD] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TATIM] [bit] NULL,
[LLOGSH] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAG] [bit] NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL,
[DSCNTKLE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODTVSH] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BC] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMSH4] [float] NULL,
[CMSH5] [float] NULL,
[CMSH6] [float] NULL,
[CMSH7] [float] NULL,
[CMSH8] [float] NULL,
[CMSH9] [float] NULL,
[CMB] [float] NULL,
[DSCNTKLF] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLG] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLH] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLJ] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LISTE] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEP] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORG] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LLOGB] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NOTACTIV] [bit] NULL CONSTRAINT [DF_SHERBIM_NOTACTIV] DEFAULT ((0)),
[DATECREATE] [datetime] NULL CONSTRAINT [DF_SHR_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_SHR_DATEEDIT] DEFAULT (getdate())
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [@KOD_SHERBIM] ON [dbo].[SHERBIM] ([KOD]) ON [PRIMARY]
GO
