CREATE TABLE [dbo].[FKSTSCR]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[NRD] [int] NULL,
[KOD] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LLOGARI] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LLOGARIPK] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KMON] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KURS1] [float] NULL,
[KURS2] [float] NULL,
[DB] [float] NULL,
[KR] [float] NULL,
[DBKRMV] [float] NULL,
[KOMENT] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TREGDK] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAG] [bit] NULL,
[ORDPOST] [int] NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL,
[FAKLS] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FADESTIN] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAART] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATROW] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORDERSCR] [int] NULL,
[TAGRND] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [{1881CEEB-3848-491E-B133-D39E8FD912F9}] ON [dbo].[FKSTSCR] ([NRD]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FKSTSCRNRRENDOR] ON [dbo].[FKSTSCR] ([NRRENDOR]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [@NRD_FKSCR] ON [dbo].[FKSTSCR] ([NRRENDOR], [NRD]) ON [PRIMARY]
GO
