CREATE TABLE [dbo].[AQHistoriScr]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[NRD] [int] NULL,
[KOD] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODAF] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KARTLLG] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BC] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SASI] [float] NULL,
[NJESI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VLERABS] [float] NULL,
[NORMEAM] [float] NULL,
[VLERAAM] [float] NULL,
[CMIMBS] [float] NULL,
[KODOPER] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATEOPER] [datetime] NULL,
[TIPDOK] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRDOK] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATEDOK] [datetime] NULL,
[SHENIM1] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM2] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VLERAFT] [float] NULL,
[KMON] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KURS1] [float] NULL,
[KURS2] [float] NULL,
[KOMENT] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODLOCATION] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIMLOCATION] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODPRONESI] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIMPRONESI] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODFKL] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIMFKL] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VLERAFAT] [float] NULL,
[VLERAFATMV] [float] NULL,
[VLERAEXTMV] [float] NULL,
[STATROW] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORDERSCR] [int] NULL,
[DATECREATE] [datetime] NULL CONSTRAINT [DF_AQHistoriScr_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_AQHistoriScr_DATEEDIT] DEFAULT (getdate()),
[TROW] [bit] NULL,
[TAGNR] [int] NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [AQKartelaHistNrd] ON [dbo].[AQHistoriScr] ([NRD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AQHistoriScr] ADD CONSTRAINT [AQKartelaHistNrRendor] UNIQUE NONCLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AQHistoriScr] WITH NOCHECK ADD CONSTRAINT [FK_AQKartelaHist_AQKartela] FOREIGN KEY ([NRD]) REFERENCES [dbo].[AQKartela] ([NRRENDOR]) ON DELETE CASCADE ON UPDATE CASCADE
GO
