CREATE TABLE [dbo].[ArtikujMonedhe]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[KOD] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MONKLSA] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MONKLSB] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MONKLSC] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MONKLSD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MONKLSE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MONKLSF] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MONKLSG] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MONKLSH] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MONKLSI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MONKLSJ] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MONKLSK] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MONKLSL] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MONKLSM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MONKLSN] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MONKLSO] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MONKLSP] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MONKLSQ] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MONKLSR] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MONKLSS] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MONKLST] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATECREATE] [datetime] NULL CONSTRAINT [DF_ARTMON_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_ARTMON_DATEEDIT] DEFAULT (getdate()),
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAG] [bit] NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL
) ON [PRIMARY]
GO
