CREATE TABLE [dbo].[zzTransportData01]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[NRD] [int] NULL,
[GRUPI] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOD] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODFIN] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODDEP] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODLIST] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F001] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F002] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F003] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F004] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F005] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F006] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F007] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F008] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F009] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F010] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F011] [datetime] NULL,
[F012] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F013] [datetime] NULL,
[F014] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F101] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F102] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F103] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F104] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F105] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F106] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F107] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F108] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F109] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F110] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F111] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F112] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F201] [float] NULL,
[F202] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F203] [float] NULL,
[F204] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F205] [float] NULL,
[F206] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F207] [float] NULL,
[F208] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F209] [float] NULL,
[F210] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F211] [float] NULL,
[F212] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F213] [float] NULL,
[F214] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F215] [float] NULL,
[F216] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F217] [float] NULL,
[F218] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F219] [float] NULL,
[F220] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F221] [float] NULL,
[F222] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F223] [float] NULL,
[F224] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F225] [float] NULL,
[F226] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F227] [float] NULL,
[F228] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F301] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F302] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F303] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F304] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F305] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F306] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F307] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F308] [datetime] NULL,
[F309] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F901] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOTO1] [image] NULL,
[FOTO2] [image] NULL,
[FOTO3] [image] NULL,
[FOTO4] [image] NULL,
[OBJEKTPATH1LOADED] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OBJEKTTEXT1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OBJEKTPATH2LOADED] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OBJEKTTEXT2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OBJEKTPATH3LOADED] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OBJEKTTEXT3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OBJEKTPATH4LOADED] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OBJEKTTEXT4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATECREATE] [datetime] NULL CONSTRAINT [DF_zzTransportData01_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_zzTransportData01_DATEEDIT] DEFAULT (getdate()),
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
