CREATE TABLE [dbo].[SptPacients]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[KOD] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MBIEMER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ATESI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GJINI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATELINDJE] [datetime] NULL,
[ADRESE1] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADRESE2] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KARTEIDENTITET] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RRETH] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHTET] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TELEFON1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TELEFON2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMAIL] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROFESION] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIFIKIM1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIFIKIM2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM1] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRRENDORKLIENT] [int] NULL,
[NOTACTIV] [bit] NULL CONSTRAINT [DF_SptPacients_NOTACTIV] DEFAULT ((0)),
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATECREATE] [datetime] NULL CONSTRAINT [DF_SptPacients_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_SptPacients_DATEEDIT] DEFAULT (getdate()),
[TROW] [bit] NULL,
[TAGNR] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
