CREATE TABLE [dbo].[JAVA]
(
[NRRENDOR] [int] NOT NULL,
[KOD] [int] NOT NULL,
[PERSHKRIM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[JAVA] ADD CONSTRAINT [PK__JAVA__2E8B20C7464F919D] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
