CREATE TABLE [dbo].[ARTIKUJBCSCR]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[NRD] [int] NULL,
[BC] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_ARTIKUJBCSCR_BC] DEFAULT (''),
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAG] [bit] NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL,
[NGJYRE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MASE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERIMETER] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM2] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM1] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORDERSCR] [int] NULL,
[STATROW] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMSH] [float] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [BC] ON [dbo].[ARTIKUJBCSCR] ([BC]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [NRD] ON [dbo].[ARTIKUJBCSCR] ([NRD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ARTIKUJBCSCR] WITH NOCHECK ADD CONSTRAINT [FK_ARTIKUJBCSCR_ARTIKUJ] FOREIGN KEY ([NRD]) REFERENCES [dbo].[ARTIKUJ] ([NRRENDOR]) ON DELETE CASCADE ON UPDATE CASCADE
GO
