CREATE TABLE [dbo].[AQCelje]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[NRD] [int] NULL,
[KOD] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODAF] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KARTLLG] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOMENT] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BC] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NJESI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SASI] [float] NULL,
[CMIMBS] [float] NULL,
[VLERABS] [float] NULL,
[NORMEAM] [float] NULL,
[VLERAAM] [float] NULL,
[CMIMOR] [float] NULL,
[VLERAOR] [float] NULL,
[CMIMSH] [float] NULL,
[VLERASH] [float] NULL,
[KMON] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KURS1] [float] NULL,
[KURS2] [float] NULL,
[DATEOPER] [datetime] NULL,
[KODOPER] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODFKL] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIMFKL] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODPRONESI] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIMPRONESI] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODLOCATION] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIMLOCATION] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VLERAFAT] [float] NULL,
[VLERAFATMV] [float] NULL,
[VLERAEXTMV] [float] NULL,
[NRSERIAL] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIPKLL] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRRENDKLLG] [int] NULL,
[STATROW] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORDERSCR] [int] NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL,
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_AQCelje_DATEEDIT] DEFAULT (getdate()),
[DATECREATE] [datetime] NULL CONSTRAINT [DF_AQCelje_DATECREATE] DEFAULT (getdate()),
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AMVLEREMBET] [bit] NULL
) ON [PRIMARY]
GO
