CREATE TABLE [dbo].[Oferte]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[KOD] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PERSHKRIM] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STARTDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[AKTIV] [bit] NOT NULL,
[MEORAR] [bit] NOT NULL,
[KMAG] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KKLI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VLFIX] [bit] NOT NULL CONSTRAINT [DF_Oferte_VLFIX] DEFAULT ((1)),
[PERHERSHEM] [bit] NOT NULL CONSTRAINT [DF_Oferte_PERHERSHEM] DEFAULT ((0)),
[DNGABLERJE] [datetime] NOT NULL CONSTRAINT [DF_Oferte_DNGABLERJE] DEFAULT (getdate()),
[DDERIBLERJE] [datetime] NOT NULL CONSTRAINT [DF_Oferte_DDERIBLERJE] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Oferte] ADD CONSTRAINT [PK__Oferte__2E8B20C724B993A8] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
