CREATE TABLE [dbo].[KONTRATASCR]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[NRD] [int] NULL,
[KOD] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMIM] [float] NULL,
[FIRSTFAT] [bit] NULL CONSTRAINT [DF_KONTRATASCR_FIRSTFAT] DEFAULT ((0)),
[ARDHSHTYRE] [bit] NULL CONSTRAINT [DF_KONTRATASCR_ARDHSHTYRE] DEFAULT ((1)),
[MACADRES] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOMENT] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAGNR] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[KONTRATASCR] ADD CONSTRAINT [PK__KONTRATA__2E8B20C75A568A4A] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PKKONTRATASCR] ON [dbo].[KONTRATASCR] ([NRRENDOR]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [KONTRATSCRNRD] ON [dbo].[KONTRATASCR] ([NRRENDOR], [NRD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[KONTRATASCR] WITH NOCHECK ADD CONSTRAINT [FK_KONTRATASCR_KONTRATA] FOREIGN KEY ([NRD]) REFERENCES [dbo].[KONTRATA] ([NRRENDOR]) ON DELETE CASCADE ON UPDATE CASCADE
GO
