CREATE TABLE [dbo].[IMPORTDOCUMENTS]
(
[NRRENDOR] [int] NOT NULL,
[KOD] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTIV] [bit] NULL,
[TABDISPLAY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOADPROCEDURE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOADPARAMETERS] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TESTPROCEDURE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TESTPARAMETERS] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IMPORTPROCEDURE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IMPORTPARAMETERS] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMPANY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WITHWORKINGPATH] [bit] NOT NULL,
[ORDER] [int] NOT NULL,
[ID] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IMPORTDOCUMENTS] ADD CONSTRAINT [PK__IMPORTDO__3214EC272C8FBF9A] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
