CREATE TABLE [dbo].[FKSCR]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[NRD] [int] NULL,
[KOD] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LLOGARI] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LLOGARIPK] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOMENT] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KMON] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KURS1] [float] NULL,
[KURS2] [float] NULL,
[DB] [float] NULL,
[KR] [float] NULL,
[DBKRMV] [float] NULL,
[TREGDK] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAG] [bit] NULL,
[ORDPOST] [int] NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL,
[FAART] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FADESTIN] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAKLS] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODREF] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIPKLLREF] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATROW] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORDERSCR] [int] NULL,
[TAGRND] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [{34D93D65-B81B-4CCC-C196739D1C03}] ON [dbo].[FKSCR] ([NRD]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [@NRD_FKSCR] ON [dbo].[FKSCR] ([NRRENDOR], [NRD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FKSCR] WITH NOCHECK ADD CONSTRAINT [FK_FKSCR_FK] FOREIGN KEY ([NRD]) REFERENCES [dbo].[FK] ([NRRENDOR]) ON DELETE CASCADE ON UPDATE CASCADE
GO
