CREATE TABLE [dbo].[BUXHET_EMRA]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[KOD] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIMENSION1] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIMENSION2] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIMENSION3] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIMENSION4] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AKTIV] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BUXHET_EMRA] ADD CONSTRAINT [PK_BUXHET_LISTA] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
