CREATE TABLE [dbo].[MAGAZINA]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[KOD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERGJ] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GJNEG] [bit] NULL,
[GJENDJE] [float] NULL,
[NRFHF] [float] NULL,
[NRFDF] [float] NULL,
[VF_MG] [float] NULL,
[TAG] [bit] NULL,
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TROW] [bit] NULL,
[DEP] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODLM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAGNR] [int] NULL,
[ZONA] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LIST] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISDOGANE] [bit] NULL,
[GRUP] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QELLIM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NIPT] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NIPTCERTIFIKATE] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TELEFON1] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIPI] [int] NULL,
[CMPRODCALCUL] [bit] NULL,
[KLIENTKASE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRPRODUKTKP] [int] NULL,
[NRPRODUKTKS] [int] NULL,
[NRPERSONEL] [int] NULL,
[NJESIADMIN] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODNEW] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NOTACTIV] [bit] NULL CONSTRAINT [DF_MAGAZINA_NOTACTIV] DEFAULT ((0)),
[DATECREATE] [datetime] NULL CONSTRAINT [DF_MAG_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_MAG_DATEEDIT] DEFAULT (getdate()),
[FISOBJECT] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FISBUSINESSUNIT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [@KOD_MAGAZINA] ON [dbo].[MAGAZINA] ([KOD]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [@NRRENDOR_MAGAZINA] ON [dbo].[MAGAZINA] ([NRRENDOR]) ON [PRIMARY]
GO
