CREATE TABLE [dbo].[ARTIKUJKFSCR]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[NRD] [int] NULL CONSTRAINT [DF_ARTIKUJKFSCR_NRD] DEFAULT ((0)),
[BC] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOD] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NJESI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SASIMIN] [float] NULL,
[SASIMAX] [float] NULL,
[ORDERSCR] [int] NULL CONSTRAINT [DF_ARTIKUJKFSCR_ORDERSCR] DEFAULT ((0)),
[STATROW] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ARTIKUJKFSCR_NRD] ON [dbo].[ARTIKUJKFSCR] ([NRD]) ON [PRIMARY]
GO
