CREATE TABLE [dbo].[KlientCmimCm]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[NRD] [int] NULL,
[KOD] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SASI] [float] NULL,
[CMIM] [float] NULL,
[STATROW] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAGNR] [int] NULL,
[TROW] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[KlientCmimCm] ADD CONSTRAINT [PK_KlientCmimCm] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [I_Kod] ON [dbo].[KlientCmimCm] ([KOD]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_KlientCmimCm_NRD] ON [dbo].[KlientCmimCm] ([NRD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[KlientCmimCm] ADD CONSTRAINT [FJ_KlientCmimCm_KlientCmimArt] FOREIGN KEY ([NRD]) REFERENCES [dbo].[KlientCmimArt] ([NRRENDOR]) ON DELETE CASCADE ON UPDATE CASCADE
GO
