CREATE TABLE [dbo].[ISD4]
(
[BC] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SASIA] [float] NULL,
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ISD4] ADD CONSTRAINT [PK__ISD4__2E8B20C73DBA4B9C] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
