CREATE TABLE [dbo].[ArtikujOrd]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[DATEDOK] [datetime] NULL,
[KOD] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM1] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM2] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KMAG] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COLUMNLIST] [varchar] (5000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LISTORDEREDMK] [varchar] (5000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LISTORDEREDDQ] [varchar] (5000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LISTORDEREDKL] [varchar] (5000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAGNR] [int] NULL,
[TROW] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ArtikujOrd] ADD CONSTRAINT [PK_ArtikujOrd] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
