CREATE TABLE [dbo].[OferteScr]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[NRD] [int] NOT NULL,
[MENUELEMENTID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CMIM] [float] NOT NULL,
[CMB] [float] NOT NULL CONSTRAINT [DF_OferteScr_CMB] DEFAULT ((0)),
[PIKE] [float] NOT NULL CONSTRAINT [DF_OferteScr_PIKE] DEFAULT ((0)),
[sasi] [int] NOT NULL CONSTRAINT [DF__OferteScr__sasi__0591F557] DEFAULT ((9999999)),
[SASIOFERTE] [int] NOT NULL CONSTRAINT [DF__OferteScr__sasio__751D5EE4] DEFAULT ((1))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OferteScr] ADD CONSTRAINT [PK__OferteSc__2E8B20C72D4ED9A9] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
