CREATE TABLE [dbo].[ISD8]
(
[BC] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SASIA] [float] NULL,
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ISD8] ADD CONSTRAINT [PK__ISD8__2E8B20C737577209] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
