CREATE TABLE [dbo].[SHERBIMESPECIALE]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[KOD] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TYPE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SHERBIMESPECIALE] ADD CONSTRAINT [PK_SHEBIMESPECIALE] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
