CREATE TABLE [dbo].[AQDetailData01]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[NRD] [int] NULL,
[GRUPI] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODFIN] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F001] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F002] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F003] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F004] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F005] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F006] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F007] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F101] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F102] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F103] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F104] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F105] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F106] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F107] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F108] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F109] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F110] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F111] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F112] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F113] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F114] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F115] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F116] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F117] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F118] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F119] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F120] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F121] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F122] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F123] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F124] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F125] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F126] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F127] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F128] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F129] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F130] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F131] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F132] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F133] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F134] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F135] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F136] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F137] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F138] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F139] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F140] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F141] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F142] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F143] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F144] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F145] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F201] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F202] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F203] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F204] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F205] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F206] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F207] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F208] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F209] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F210] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F211] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F212] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F213] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F214] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F215] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F216] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F217] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F218] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F301] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F302] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F303] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F304] [bit] NULL,
[F305] [bit] NULL,
[F306] [bit] NULL,
[F307] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F308] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F309] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F310] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F311] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F312] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F313] [bit] NULL,
[F314] [bit] NULL,
[F315] [bit] NULL,
[F316] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F317] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F318] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F319] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F320] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F321] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F322] [bit] NULL,
[F323] [bit] NULL,
[F324] [bit] NULL,
[F325] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F326] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F327] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F901] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOTO1] [image] NULL,
[FOTO2] [image] NULL,
[FOTO3] [image] NULL,
[FOTO4] [image] NULL,
[OBJEKTPATH1LOADED] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OBJEKTTEXT1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OBJEKTPATH2LOADED] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OBJEKTTEXT2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OBJEKTPATH3LOADED] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OBJEKTTEXT3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OBJEKTPATH4LOADED] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OBJEKTTEXT4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATECREATE] [datetime] NULL CONSTRAINT [DF_AQTableData01_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_AQTableData01_DATEEDIT] DEFAULT (getdate()),
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
