CREATE TABLE [dbo].[FKST]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[KODNENDITAR] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRDFK] [int] NULL,
[NRDOK] [int] NULL,
[DATEDOK] [datetime] NULL,
[PERSHKRIM1] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM2] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KMON] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KURS1] [float] NULL,
[KURS2] [float] NULL,
[POSTIM] [bit] NULL,
[LETER] [bit] NULL,
[ORG] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIRSTDOK] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIPDOK] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMDOK] [int] NULL,
[REFERDOK] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KMAG] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FORMAT] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTEXP] [bit] NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL,
[DST] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTIMPID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTIMPKOMENT] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTEXPKOMENT] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KONFIRM] [bit] NULL,
[DATECREATE] [datetime] NULL CONSTRAINT [DF_FKST_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_FKST_DATEEDIT] DEFAULT (getdate()),
[TAGRND] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOBCREATE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIME] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [@NRRENDOR_FKST] ON [dbo].[FKST] ([NRRENDOR]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [NUMDOK] ON [dbo].[FKST] ([NUMDOK]) ON [PRIMARY]
GO
