CREATE TABLE [dbo].[RAJON]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[KOD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIFIKIM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL,
[KOEFICENT] [float] NULL CONSTRAINT [DF_RAJON_KOEFICENT] DEFAULT ((0)),
[NOTACTIV] [bit] NULL CONSTRAINT [DF_RAJON_NOTACTIV] DEFAULT ((0)),
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATECREATE] [datetime] NULL CONSTRAINT [DF_RAJ_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_RAJ_DATEEDIT] DEFAULT (getdate())
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [KOD_RJ] ON [dbo].[RAJON] ([KOD]) ON [PRIMARY]
GO
