CREATE TABLE [dbo].[KURSE]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[NRD] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRRENDMON] [int] NULL,
[KMON] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATA] [datetime] NULL,
[KURS1] [float] NULL,
[KURS2] [float] NULL,
[TIPCATALOG] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [@NRD] ON [dbo].[KURSE] ([NRD]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [@CELES_KU] ON [dbo].[KURSE] ([NRRENDMON], [DATA]) ON [PRIMARY]
GO
