CREATE TABLE [dbo].[TableConfigs]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[FORMNAME] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TABLENAME] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIELDSPREVIOUS] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIELDSNOTEMPTY] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTIVFIELDSPRVS] [bit] NULL,
[ACTIVFIELDSNOTEMP] [bit] NULL,
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATECREATE] [datetime] NULL CONSTRAINT [DF_TableConfigs_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_TableConfigs_DATEEDIT] DEFAULT (getdate()),
[TAGNR] [int] NULL,
[TROW] [bit] NULL,
[FIELDSEARCH2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIELDSEARCH2PROMPT] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIELDSEARCH2ACTIV] [bit] NULL
) ON [PRIMARY]
GO
