CREATE TABLE [dbo].[SISTEMIMMGSCR]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[KOD] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NJESI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KMAG] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF4] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF5] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF6] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF7] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF8] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF9] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOSTMES] [float] NULL,
[CMIMART] [float] NULL,
[CMB] [float] NULL,
[CMSH] [float] NULL,
[CMSH1] [float] NULL,
[CMSH2] [float] NULL,
[CMSH3] [float] NULL,
[CMSH4] [float] NULL,
[CMSH5] [float] NULL,
[CMSH6] [float] NULL,
[CMSH7] [float] NULL,
[CMSH8] [float] NULL,
[CMSH9] [float] NULL,
[CMSH10] [float] NULL,
[CMSH11] [float] NULL,
[CMSH12] [float] NULL,
[CMSH13] [float] NULL,
[CMSH14] [float] NULL,
[CMSH15] [float] NULL,
[CMSH16] [float] NULL,
[CMSH17] [float] NULL,
[CMSH18] [float] NULL,
[CMSH19] [float] NULL,
[CMSHPLM1] [float] NULL,
[CMSHPLM2] [float] NULL,
[BC] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POZIC] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATEDOK] [datetime] NULL,
[NRDOK] [float] NULL,
[NRFRAKS] [int] NULL,
[ACTIV] [bit] NULL,
[QKOSTO] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VLERADIF] [float] NULL,
[SASIOLD] [float] NULL,
[CMIMOLD] [float] NULL,
[VLERAOLD] [float] NULL,
[SASINEW] [float] NULL,
[CMIMNEW] [float] NULL,
[VLERANEW] [float] NULL,
[KOSTMESND] [float] NULL,
[KOSTMESMG] [float] NULL,
[STATUSST] [int] NULL,
[NRD] [int] NOT NULL CONSTRAINT [DF_SISTEMIMMG_NRD] DEFAULT ((0)),
[NRRENDKLLG] [int] NULL,
[STATROW] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAG] [bit] NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SISTEMIMMGSCR] WITH NOCHECK ADD CONSTRAINT [FK_SISTEMIMMGSCR_SIST] FOREIGN KEY ([NRD]) REFERENCES [dbo].[SISTEMIMMG] ([NRRENDOR]) ON DELETE CASCADE ON UPDATE CASCADE
GO
