CREATE TABLE [dbo].[ARTIKUJCMADBAK]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[KOD] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOSTMES] [float] NULL,
[KOSTMES_MAN] [float] NULL,
[KOSTPLAN] [float] NULL,
[NJESI] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NEGST] [bit] NULL,
[POZIC] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIP] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NJESB] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOEFB] [float] NULL,
[CMB] [float] NULL,
[CMSH] [float] NULL,
[CMSHTVSH] [float] NULL,
[CMSHPATVSH] [float] NULL,
[CMSH1] [float] NULL,
[CMSH2] [float] NULL,
[CMSH3] [float] NULL,
[CMSH4] [float] NULL,
[CMSH5] [float] NULL,
[CMSH6] [float] NULL,
[CMSH7] [float] NULL,
[CMSH8] [float] NULL,
[CMSH9] [float] NULL,
[CMSH10] [float] NULL,
[CMSH11] [float] NULL,
[CMSH12] [float] NULL,
[CMSH13] [float] NULL,
[CMSH14] [float] NULL,
[CMSH15] [float] NULL,
[CMSH16] [float] NULL,
[CMSH17] [float] NULL,
[CMSH18] [float] NULL,
[CMSH19] [float] NULL,
[USM] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAG] [bit] NULL,
[TROW] [bit] NULL,
[BC] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF2] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF3] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF4] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF5] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF6] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAGNR] [int] NULL,
[NOTACTIV] [bit] NULL,
[TATIM] [bit] NULL,
[PERQINDJE] [float] NULL,
[USERN] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TVSH] [float] NULL,
[UPDATED] [bit] NULL,
[NGJYRE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MASE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OF_CMSH] [float] NULL,
[OF_DTFILLIM] [datetime] NULL,
[OF_DITE] [int] NULL,
[OF_APLIKUAR] [bit] NULL,
[MINI] [float] NULL,
[MAKS] [float] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ARTIKUJCMADBAK] ADD CONSTRAINT [PK__ARTIKUJC__2E8B20C72617CC35] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
