CREATE TABLE [dbo].[KODET]
(
[KODIISHTE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODIBEHET] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[KODET] ADD CONSTRAINT [PK__KODET__2E8B20C7549DB0F4] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
