CREATE TABLE [dbo].[TIPEOFERTASH]
(
[NRRENDOR] [int] NOT NULL,
[KOD] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TIPEOFERTASH] ADD CONSTRAINT [PK__TIPEOFER__2E8B20C708DC6F09] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
