CREATE TABLE [dbo].[ARTIKUJISP]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[TEMPLATENUMBER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TEMPLATEDATE] [datetime] NULL,
[INVOICENUMBER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INVOICEDATE] [datetime] NULL,
[INVOICECUSTOMERNAME] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PC] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCMODULI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCCATEG] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LABEL] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LABELCATEG] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LABELNUMBER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LABELDENOMINATION] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LABELPRICE] [float] NULL,
[LABELSERIALNUMBER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOCATION] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOCATIONSTATE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOCATIONCITY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOCATIONBRANCH] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOCATIONAREA] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOCATIONAREANO] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOCATIONWORKPOSITION] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOCATIONORDEREDBY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[locationapprovedby] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOCATIONMISCODE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOCATIONPOSADDRESS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCCONTRACT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCNOTE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AKTIV] [bit] NOT NULL CONSTRAINT [DF_ARTIKUJISP_AKTIV] DEFAULT ((1)),
[USER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ARTIKUJISP] ADD CONSTRAINT [PK_ARTIKUJISP] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
