CREATE TABLE [dbo].[FisBusUnit]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[KOD] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADRESE1] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADRESE2] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM3] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM4] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERGJEGJES] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRUP] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIFIKIM] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QELLIM] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NIPT] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NIPTCERTIFIKATE] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TELEFON1] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIPI] [int] NULL,
[ZONA] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLIENTKASE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NJESIADMIN] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NOTACTIV] [bit] NULL CONSTRAINT [DF_FISBUSUNIT_NOTACTIV] DEFAULT ((0)),
[DATECREATE] [datetime] NULL CONSTRAINT [DF_FISBUSUNIT_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_FISBUSUNIT_DATEEDIT] DEFAULT (getdate()),
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TROW] [bit] NULL,
[TAG] [bit] NULL,
[TAGNR] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [@NRRENDOR_FISBUSSUNIT] ON [dbo].[FisBusUnit] ([NRRENDOR]) ON [PRIMARY]
GO
