CREATE TABLE [dbo].[VSST]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[KODNENDITAR] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRDOK] [int] NULL,
[DATEDOK] [datetime] NULL,
[PERSHKRIM1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KMON] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KURS1] [float] NULL,
[KURS2] [float] NULL,
[NRDFK] [int] NULL,
[POSTIM] [bit] NULL,
[LETER] [bit] NULL,
[FIRSTDOK] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL,
[KLASIFIKIM] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DST] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTIMPID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTIMPKOMENT] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTEXP] [bit] NULL,
[EXTEXPKOMENT] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KONFIRM] [bit] NULL,
[DATECREATE] [datetime] NULL CONSTRAINT [DF_VSST_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_VSST_DATEEDIT] DEFAULT (getdate()),
[TAGRND] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOBCREATE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIME] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [@NRDOK_VSST] ON [dbo].[VSST] ([NRDOK]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [@NRRENDOR_VSST] ON [dbo].[VSST] ([NRRENDOR]) ON [PRIMARY]
GO
