CREATE TABLE [dbo].[FisBusUnitScr]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[NRD] [int] NULL,
[KODBU] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODAF] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATROW] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORDERSCR] [int] NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL,
[KODTCR] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [@NRD_FISBUSSUNITSCR] ON [dbo].[FisBusUnitScr] ([NRD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FisBusUnitScr] ADD CONSTRAINT [FK_FISBUSSUNITSCR_FISBUSSUNIT] FOREIGN KEY ([NRD]) REFERENCES [dbo].[FisBusUnit] ([NRRENDOR]) ON DELETE CASCADE ON UPDATE CASCADE
GO
