CREATE TABLE [dbo].[ARTIKUJ_COPY]
(
[NRRENDOR] [int] NOT NULL,
[KOD] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF2] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF3] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF4] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF5] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF6] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOSTMES] [float] NULL,
[KOSTPLAN] [float] NULL,
[NJESI] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MINI] [float] NULL,
[MAKS] [float] NULL,
[NEGST] [bit] NULL,
[POZIC] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIP] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NJESB] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOEFB] [float] NULL,
[CMB] [float] NULL,
[NJESSH] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOEFSH] [float] NULL,
[CMSH] [float] NULL,
[CMSH1] [float] NULL,
[CMSH2] [float] NULL,
[CMSH3] [float] NULL,
[CMSH4] [float] NULL,
[CMSH5] [float] NULL,
[CMSH6] [float] NULL,
[CMSH7] [float] NULL,
[CMSH8] [float] NULL,
[CMSH9] [float] NULL,
[DSCNTKLA] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLB] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLC] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLF] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLG] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TATIM] [bit] NULL,
[PESHA] [float] NULL,
[KONV1] [float] NULL,
[KONV2] [float] NULL,
[KONVNJESI] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BC] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODORG] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOEFICPERB] [float] NULL,
[AUTOSHKLPFJ] [bit] NULL,
[AUTOSHKLPFDBR] [bit] NULL,
[RIMBURSIM] [bit] NULL,
[NOTACTIV] [bit] NULL,
[KODLM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEP] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LIST] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORG] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USI] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAG] [bit] NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL,
[VLTAX] [float] NULL,
[KOEFICENT] [float] NULL,
[FISKAL] [bit] NULL,
[GARSASI] [int] NULL,
[KODTVSH] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODFKL] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SKADENCE] [bit] NULL,
[OFERTE] [bit] NULL,
[SENT] [bit] NULL,
[SERIALSETI] [bit] NULL,
[GARSETI] [bit] NULL,
[CMSHKLI] [float] NULL,
[FURNKOD] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF8] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ARTIKUJ_COPY] ADD CONSTRAINT [PK__ARTIKUJ___2E8B20C7DE7E470A] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
