CREATE TABLE [dbo].[KURSET]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[DATA] [datetime] NULL,
[KOD] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODMON] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHMON] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KURS1] [float] NOT NULL CONSTRAINT [DF_KURSET_KURS1] DEFAULT ((1)),
[KURS2] [float] NOT NULL CONSTRAINT [DF_KURSET_KURS2] DEFAULT ((1)),
[DATAORA] [datetime] NOT NULL CONSTRAINT [DF_KURSET_DATAORA] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[KURSET] ADD CONSTRAINT [PK_KURSET] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
