CREATE TABLE [dbo].[CKVERRORS]
(
[KOD] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PERSHKRIM] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CKVERRORS] ADD CONSTRAINT [PK__CKVERROR__2E8B20C73D5C1412] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
