CREATE TABLE [dbo].[FF]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[DATEDOK] [datetime] NULL,
[KTH] [bit] NULL,
[NRDOK] [float] NULL,
[NRFRAKS] [int] NULL,
[KOD] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODFKL] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KMON] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASAKF] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VENHUAJ] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NIPT] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRSERIAL] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODFISKAL] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RRETHI] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM3] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM4] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRDSHOQ] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTDSHOQ] [datetime] NULL,
[NRRENDDMG] [int] NULL,
[TIPDMG] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRMAG] [int] NULL,
[KMAG] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRDMAG] [float] NULL,
[FRDMAG] [int] NULL,
[DTDMAG] [datetime] NULL,
[MODPG] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTAF] [smallint] NULL,
[DTDS] [int] NULL,
[PERQDS] [float] NULL,
[KURS1] [float] NULL,
[KURS2] [float] NULL,
[VLPATVSH] [float] NULL,
[VLTVSH] [float] NULL,
[VLERZBR] [float] NULL,
[VLERTOT] [float] NULL,
[PARAPG] [float] NULL,
[PERQTVSH] [float] NULL,
[PERQZBR] [float] NULL,
[LLOGTVSH] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LLOGZBR] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LLOGARK] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRDFK] [int] NULL,
[NRDITAR] [int] NULL,
[NRDITARSHL] [int] NULL CONSTRAINT [DF_FF_NRDITARSHL] DEFAULT ((0)),
[POSTIM] [bit] NULL,
[LETER] [bit] NULL,
[FIRSTDOK] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISDG] [bit] NULL,
[NRDOKDG] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTDOKDG] [datetime] NULL,
[KODDG] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAGNR] [int] NULL,
[NRDFTEXTRA] [int] NULL,
[NRRENDOROR] [int] NULL,
[TIPFT] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIFIKIM] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAG] [bit] NULL,
[TROW] [bit] NULL,
[VLTAX] [float] NULL,
[KLASETVSH] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODARK] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATEARK] [datetime] NULL,
[NRRENDORAR] [int] NULL,
[GRUP] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRFATST] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTFATST] [datetime] NULL,
[NRRENDORAQ] [int] NULL CONSTRAINT [DF_FF_NRDITARAQ] DEFAULT ((0)),
[KLASIFIKIM1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LLOJDOK] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAGESEARK] [float] NULL,
[IMPORTTAG] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRRENDORAMB] [int] NULL,
[NRRENDORFJT] [int] NULL,
[EXTIMPID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTIMPKOMENT] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTEXP] [bit] NULL,
[EXTEXPKOMENT] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KONFIRM] [bit] NULL,
[DATECREATE] [datetime] NULL CONSTRAINT [DF_FF_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_FF_DATEEDIT] DEFAULT (getdate()),
[TAGRND] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAGLM] [bit] NULL,
[FISTCR] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fisfic] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FISBUSINESSUNIT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nrfiskalizim] [int] NULL,
[JOBCREATE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIME] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FISDATEPARE] [datetime] NULL,
[FISDATEFUND] [datetime] NULL,
[FISTVSHEFEKT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FISKALIZUAR] [bit] NULL,
[FISUUID] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FISLASTERRORFIC] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FISLASTERRORTEXTFIC] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FISLASTERROREIC] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FISLASTERRORTEXTEIC] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FISQRCODELINK] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FISRELATEDFIC] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FISIIC] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FISIICSIG] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FISPDF] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FISEIC] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FISRESPONSEXMLFIC] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FISRESPONSEXMLEIC] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FISXMLSTRING] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FISXMLSIGNED] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FISSTATUS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FISKODOPERATOR] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FISPROCES] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FISMENPAGESE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FISTIPDOK] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISDOCFISCAL] [bit] NULL,
[FISKODREASON] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [@KODFKL_FF] ON [dbo].[FF] ([KODFKL]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [@NRRENDOR_FF] ON [dbo].[FF] ([NRRENDOR]) ON [PRIMARY]
GO
