CREATE TABLE [dbo].[DYQDEP]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[DYQAN] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_DYQDEP_DYQAN] DEFAULT (''),
[DEPARTAMENT] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_DYQDEP_DEPARTAMENT] DEFAULT (''),
[KMAG] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_DYQDEP_KMAG] DEFAULT (''),
[TAGNR] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DYQDEP] ADD CONSTRAINT [PK_DYQDEP] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
