CREATE TABLE [dbo].[TRANSPORT]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[KOD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MBIEMER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MJET] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TARGE] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOMPANI] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADRESA1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADRESA2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADRESA3] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TELEFON1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TELEFON2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAX] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NIPT] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRLICENCE] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODFISKAL] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LINKKLIENT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL,
[NIPTCERTIFIKATE] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LINKKMAG] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SASINGARKIM] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NJESINGARKIM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LISTMAGAZINA] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NOTACTIV] [bit] NULL CONSTRAINT [DF_TRANSPORT_NOTACIV] DEFAULT ((0)),
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATECREATE] [datetime] NULL CONSTRAINT [DF_TRA_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_TRA_DATEEDIT] DEFAULT (getdate()),
[RRETHI] [nchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VehOwner] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [@KOD_TRANS] ON [dbo].[TRANSPORT] ([KOD]) ON [PRIMARY]
GO
