CREATE TABLE [dbo].[SISTEMIMMG]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[KOD] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KMAG] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATEDOK] [datetime] NULL,
[NRDOK] [float] NULL,
[NRFRAKS] [int] NULL,
[PERSHKRIM] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM1] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATEFILLIM] [datetime] NULL,
[DATEFUND] [datetime] NULL,
[QKOSTO] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DST] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATUS] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATUSST] [int] NULL,
[ACTIV] [bit] NULL,
[TRANNUMBER] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATECREATE] [datetime] NULL CONSTRAINT [DF_SISTEMIMMG_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_SISTEMIMMG_DATEEDIT] DEFAULT (getdate()),
[TAG] [bit] NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SISTEMIMMG] ADD CONSTRAINT [PK_SISTEMIMMG] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
