CREATE TABLE [dbo].[FJT]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[DATEDOK] [datetime] NULL,
[KTH] [bit] NULL,
[NRDOK] [float] NULL,
[NRFRAKS] [int] NULL,
[KOD] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODFKL] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KMON] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASAKF] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VENHUAJ] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NIPT] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRSERIAL] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODFISKAL] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RRETHI] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM1] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM2] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM3] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM4] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRDSHOQ] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTDSHOQ] [datetime] NULL,
[NRRENDDMG] [int] NULL,
[TIPDMG] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRMAG] [int] NULL,
[KMAG] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRDMAG] [float] NULL,
[FRDMAG] [int] NULL,
[DTDMAG] [datetime] NULL,
[MODPG] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTAF] [int] NULL,
[DTDS] [int] NULL,
[PERQDS] [float] NULL,
[KURS1] [float] NULL,
[KURS2] [float] NULL,
[VLPATVSH] [float] NULL,
[VLTVSH] [float] NULL,
[VLERZBR] [float] NULL,
[VLERTOT] [float] NULL,
[PARAPG] [float] NULL,
[PERQTVSH] [float] NULL,
[PERQZBR] [float] NULL,
[LLOGTVSH] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LLOGZBR] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LLOGARK] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRDFK] [int] NULL,
[NRDITAR] [int] NULL,
[POSTIM] [bit] NULL,
[LETER] [bit] NULL,
[FIRSTDOK] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISDG] [bit] NULL,
[NRDOKDG] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTDOKDG] [datetime] NULL,
[TAGNR] [int] NULL,
[NRDITARSHL] [int] NULL,
[NRRENDKF] [int] NULL,
[NRFRAKSKF] [int] NULL,
[NRDFTEXTRA] [int] NULL,
[ISDOKSHOQ] [bit] NULL,
[NRRENDOROF] [int] NULL,
[NRRENDOROR] [int] NULL,
[GRUPIMFT] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GJENERUARFJ] [bit] NULL,
[KLASIFIKIM] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAG] [bit] NULL,
[TROW] [bit] NULL,
[VLTAX] [float] NULL,
[KLASIFIKIM1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASETVSH] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AGJENTSHITJE] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRFATST] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTFATST] [datetime] NULL,
[LLOGDOK] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTIVFJKOMENT] [bit] NULL,
[GRUP] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODARK] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODKART] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LLOJDOK] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIPFT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAGESEARK] [float] NULL,
[VLKASE] [float] NULL,
[ISPERMBLEDHES] [bit] NULL,
[PRINTKOMENT] [bit] NULL,
[NRLINKAPL1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IMPORTTAG] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATEARK] [datetime] NULL,
[EXTIMPID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTIMPKOMENT] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXTEXP] [bit] NULL,
[EXTEXPKOMENT] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AGJENTSHITJELINK] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KONFIRM] [bit] NULL,
[NRDITARPRMC] [int] NULL,
[NRRENDORAR] [int] NULL,
[NRRENDORAQ] [int] NULL,
[NRRENDORAMB] [int] NULL,
[NRRENDORORGFJ] [int] NULL,
[NRRENDORFJT] [int] NULL,
[DATECREATE] [datetime] NULL CONSTRAINT [DF_FJT_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_FJT_DATEEDIT] DEFAULT (getdate()),
[TAGLM] [bit] NULL,
[TAGRND] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODPACIENT] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODDOCTEGZAM] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODDOCTREFER] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOBCREATE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIME] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FISDATEPARE] [datetime] NULL,
[FISDATEFUND] [datetime] NULL,
[FISTVSHEFEKT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRFISKALIZIM] [int] NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [@KODFKL_FJT] ON [dbo].[FJT] ([KODFKL]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [@NRRENDOR_FJT] ON [dbo].[FJT] ([NRRENDOR]) ON [PRIMARY]
GO
