CREATE TABLE [dbo].[ZBRITJE]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[KOD] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LLOJI] [bit] NULL,
[RRUMBULL] [int] NULL,
[MINI1] [float] NULL,
[DISCNT1] [float] NULL,
[MINI2] [float] NULL,
[DISCNT2] [float] NULL,
[MINI3] [float] NULL,
[DISCNT3] [float] NULL,
[MINI4] [float] NULL,
[DISCNT4] [float] NULL,
[MINI5] [float] NULL,
[DISCNT5] [float] NULL,
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL,
[NOTACTIV] [bit] NULL CONSTRAINT [DF_ZBRITJE_NOTACTIV] DEFAULT ((0)),
[DATECREATE] [datetime] NULL CONSTRAINT [DF_ZBD_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_ZBD_DATEEDIT] DEFAULT (getdate())
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [@KOD_ZBRITJE] ON [dbo].[ZBRITJE] ([KOD]) ON [PRIMARY]
GO
