CREATE TABLE [dbo].[EDITVALUE]
(
[NRRENDOR] [int] NOT NULL,
[KOD] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRORDER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIELDPROMPT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIELDNAME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIELDVALUE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL
) ON [PRIMARY]
GO
