CREATE TABLE [dbo].[MGSHOQERUES]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[NRD] [int] NULL,
[KOD] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOMPANI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MJET] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TARGE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANSPORTUES] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TELEFON1] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TELEFON2] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAX] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NIPT] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRLICENCE] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODFISKAL] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE] [datetime] NULL,
[TIME] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL,
[NIPTCERTIFIKATE] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NGARKIM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHKARKIM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AGJENSIDG1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AGJENSIDG2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SASINGARKIM] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NJESINGARKIM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOMENT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NOTACTIV] [bit] NULL,
[DATECREATE] [datetime] NULL CONSTRAINT [DF_MGSH_DATECRAETE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_MGSH_DATEEDIT] DEFAULT (getdate()),
[AGJENT] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZONE] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODZONE] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZONA] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VehOwner] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StartAdress] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StartCity] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StartPoint] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestinDate] [datetime] NULL,
[DestinTime] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestinShenim1] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestinShenim2] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestinShenim3] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestinPoint] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrierIDNum] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CarrierName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CarrierAdress] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CarrierTown] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PackType] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PackNum] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GoodsFlammable] [bit] NULL,
[EscortRequired] [bit] NULL,
[CarrierIDNum] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
