CREATE TABLE [dbo].[ARTIKUJCMF]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[KOD] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMKLA] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMKLB] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMKLC] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMKLD] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMKLE] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMKLF] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMKLG] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMKLH] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMKLI] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMKLJ] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMKLK] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMKLL] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMKLM] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMKLN] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMKLO] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMKLP] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMKLQ] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMKLR] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMKLS] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMKLT] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMPL1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMPL2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMBL] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AKTIV] [bit] NULL,
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAG] [bit] NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL
) ON [PRIMARY]
GO
