CREATE TABLE [dbo].[VIZITORE]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[KMAG] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[KUSER] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATEDOK] [datetime] NOT NULL CONSTRAINT [DF_VIZITORE_DATEDOK] DEFAULT (getdate()),
[VIZITORE] [int] NOT NULL CONSTRAINT [DF_VIZITORE_VIZITORE] DEFAULT ((0)),
[EXPORT] [bit] NOT NULL CONSTRAINT [DF_VIZITORE_EXPORT] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VIZITORE] ADD CONSTRAINT [PK_VIZITORE] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
