CREATE TABLE [dbo].[OferteBak]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[KOD] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PERSHKRIM] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STARTDATE] [datetime] NOT NULL,
[ENDDATE] [datetime] NOT NULL,
[AKTIV] [bit] NOT NULL,
[MEORAR] [bit] NOT NULL,
[KMAG] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KKLI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VLFIX] [bit] NOT NULL,
[PERHERSHEM] [bit] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OferteBak] ADD CONSTRAINT [PK__OferteBa__2E8B20C727960053] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
