CREATE TABLE [dbo].[OferteSchd]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[NRD] [int] NOT NULL,
[ORANGA] [datetime] NOT NULL,
[ORADERI] [datetime] NOT NULL,
[DITA] [int] NOT NULL,
[DITAPERSHKRIM] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OferteSchd] ADD CONSTRAINT [PK__OferteSc__2E8B20C72A726CFE] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
