CREATE TABLE [dbo].[BANKASCR]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[NRD] [int] NULL,
[KODAF] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOD] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIPREF] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATEDOKREF] [datetime] NULL,
[NRDOKREF] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOMENT] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LLOGARI] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LLOGARIPK] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DB] [float] NULL,
[KR] [float] NULL,
[DBKRMV] [float] NULL,
[KMON] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KURS1] [float] NULL,
[KURS2] [float] NULL,
[TREGDK] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RRAB] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIPKLL] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRDITAR] [int] NULL,
[TAG] [bit] NULL,
[OPERLLOJ] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPERNR] [int] NULL,
[OPERDT] [datetime] NULL,
[OPERAPL] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPERORD] [int] NULL,
[OPERNRFAT] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL,
[FADESTIN] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAART] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IMPORTKODAF] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODAGJ] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATROW] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORDERSCR] [int] NULL,
[TAGRND] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODDETAJ] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [{518F6408-3160-435B-81BC-8C521351D215}] ON [dbo].[BANKASCR] ([NRD]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [@NRD_BANKASCR] ON [dbo].[BANKASCR] ([NRD], [RRAB] DESC, [NRRENDOR]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BANKASCR] WITH NOCHECK ADD CONSTRAINT [FK_BANKASCR_BANKA] FOREIGN KEY ([NRD]) REFERENCES [dbo].[BANKA] ([NRRENDOR]) ON DELETE CASCADE ON UPDATE CASCADE
GO
