CREATE TABLE [dbo].[OFERTEMARKETINGBOUNDLE]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[NRD] [int] NOT NULL,
[KOD] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISHTE] [float] NULL,
[BEHET] [float] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OFERTEMARKETINGBOUNDLE] ADD CONSTRAINT [PK_OFERTEMARKETINGBOUNDLE] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
