CREATE TABLE [dbo].[LOGARKA]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[TCRCODE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIPI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VLERA] [float] NULL,
[ERROR] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ERRORTEXT] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[XML] [xml] NULL,
[ERRORMESSAGE] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATEDOK] [datetime] NULL,
[BUSINESSUNIT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARKE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KASE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KMON] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QELLIMI] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATECREATE] [datetime] NULL CONSTRAINT [DF_LOGARKA_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_LOGARKA_DATEEDIT] DEFAULT (getdate()),
[TAGNR] [int] NULL,
[TROW] [bit] NULL,
[FISKALIZUAR] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOGARKA] ADD CONSTRAINT [PK_LOGARKA] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
