CREATE TABLE [dbo].[FAHFC]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[KOD] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADRESA1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADRESA2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADRESA3] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NIPT] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RRETHI] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TELEFON1] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TELEFON2] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIFIKIM1] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIFIKIM2] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OBJEKT] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRUP] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KATEGORI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VENDNDODHJE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RAJON] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAX] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATECREATE] [datetime] NULL CONSTRAINT [DF_FAHFC_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_FAHFC_DATEEDIT] DEFAULT (getdate()),
[NOTACTIV] [bit] NULL,
[ACTIV] [bit] NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_FAHFC_KOD] ON [dbo].[FAHFC] ([KOD]) ON [PRIMARY]
GO
