CREATE TABLE [dbo].[ARTIKUJ]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[KOD] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF2] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF3] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF4] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF5] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLASIF6] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOSTMES] [float] NULL,
[KOSTPLAN] [float] NULL,
[NJESI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MINI] [float] NULL,
[MAKS] [float] NULL,
[NEGST] [bit] NULL,
[POZIC] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIP] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NJESB] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOEFB] [float] NULL,
[CMB] [float] NULL,
[NJESSH] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOEFSH] [float] NULL,
[CMSH] [float] NULL,
[CMSH1] [float] NULL,
[CMSH2] [float] NULL,
[CMSH3] [float] NULL,
[CMSH4] [float] NULL,
[CMSH5] [float] NULL,
[CMSH6] [float] NULL,
[CMSH7] [float] NULL,
[CMSH8] [float] NULL,
[CMSH9] [float] NULL,
[DSCNTKLA] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLB] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLC] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLF] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLG] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TATIM] [bit] NULL,
[PESHA] [float] NULL,
[KONV1] [float] NULL,
[KONV2] [float] NULL,
[KONVNJESI] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BC] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODORG] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOEFICPERB] [float] NULL,
[AUTOSHKLPFJ] [bit] NULL,
[AUTOSHKLPFDBR] [bit] NULL,
[RIMBURSIM] [bit] NULL,
[NOTACTIV] [bit] NULL,
[KODLM] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEP] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LIST] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORG] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAG] [bit] NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL,
[VLTAX] [float] NULL,
[KOEFICENT] [float] NULL CONSTRAINT [DF_ARTIKUJ_KOEFICENT] DEFAULT ((0)),
[APLKMS] [bit] NULL,
[GARANCI] [int] NULL,
[KODTVSH] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLH] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMSHLIMITBLC] [bit] NULL,
[APLPESHE] [bit] NULL,
[ISAMB] [bit] NULL,
[CMBLLIMIT] [bit] NULL,
[CMSHLIMIT] [bit] NULL,
[CMSHPLM1] [float] NULL,
[FURNKOD] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMSHPLM2] [float] NULL,
[PESHANET] [float] NULL,
[PERQKMS] [float] NULL,
[CMSH10] [float] NULL,
[CMSH11] [float] NULL,
[CMSH12] [float] NULL,
[CMSH13] [float] NULL,
[CMSH14] [float] NULL,
[CMSH15] [float] NULL,
[CMSH16] [float] NULL,
[CMSH17] [float] NULL,
[CMSH18] [float] NULL,
[CMSH19] [float] NULL,
[PERSHKRIMSH] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLJ] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLK] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLL] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLN] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLO] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLP] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLQ] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLR] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLS] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSCNTKLT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PESHABRT] [float] NULL,
[PESHORETREG] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VOLUM] [float] NULL,
[KONVKOLITR] [float] NULL,
[PERSHKRIMF] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOEFICBONUS] [float] NULL,
[DOGANEKOD] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FURNARTKOD] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FURNARTPERSHKRIM] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAGARANCI] [float] NULL,
[CMSHMIN] [float] NULL,
[CMSHMAX] [float] NULL,
[CMBLMIN] [float] NULL,
[CMBLMAX] [float] NULL,
[CMBLLIMITBLC] [bit] NULL,
[NRSERIAL] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AMBAUTFJ] [bit] NULL,
[UPDATELASTBL] [bit] NULL,
[DATELASTBL] [datetime] NULL,
[CMRIMBURSIM] [float] NULL,
[STATUSSPEC] [bit] NULL,
[SHENIM1] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHENIM2] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOEFICENTAGJ] [float] NULL,
[KATEGORI] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[APLKATEGORIAGJ] [bit] NULL,
[APLKATEGORIKL] [bit] NULL,
[APLSKADENCE] [bit] NULL,
[APLNRSERIAL] [bit] NULL,
[APLLOCATIONRAFT] [bit] NULL,
[ITEMGJATESI] [float] NULL,
[ITEMGJERESI] [float] NULL,
[ITEMLARTESI] [float] NULL,
[MAXSASILEVRIM] [float] NULL,
[NOTACTIVSH] [bit] NULL,
[NOTACTIVBL] [bit] NULL,
[KODNEW] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODOLD] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATECREATE] [datetime] NULL CONSTRAINT [DF_ART_DATECREATE] DEFAULT (getdate()),
[DATEEDIT] [datetime] NULL CONSTRAINT [DF_ART_DATEEDIT] DEFAULT (getdate()),
[FISKAL] [bit] NULL,
[APLARTIKUJPALM] [bit] NULL,
[CMRIMBURSIMPJESE] [float] NULL,
[DENSITET] [float] NULL,
[CMRIMBURSIMPLOTE] [float] NULL,
[PRODUCTMANAGER] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AMBDETKLIENT] [bit] NULL,
[DateModCmb] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [@KOD_ART] ON [dbo].[ARTIKUJ] ([KOD]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [@NRRENDOR_ART] ON [dbo].[ARTIKUJ] ([NRRENDOR]) ON [PRIMARY]
GO
