CREATE TABLE [dbo].[KONTRATA]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[NRDOK] [int] NULL,
[REFERENCE] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODFKL] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTFILLIM] [datetime] NULL,
[DTFUND] [datetime] NULL,
[DTFATURE] [datetime] NULL,
[PERIUDHA] [int] NULL,
[KMON] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KURS1] [float] NULL CONSTRAINT [DF_KONTRATA_KURS1_1] DEFAULT ((1)),
[KURS2] [float] NULL CONSTRAINT [DF_KONTRATA_KURS2_1] DEFAULT ((1)),
[NOTACTIV] [bit] NULL CONSTRAINT [DF_KONTRATA_NOTACTIV] DEFAULT ((0)),
[TROW] [bit] NULL CONSTRAINT [DF_KONTRATA_TROW] DEFAULT ((0)),
[TAGNR] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[KONTRATA] ADD CONSTRAINT [PK__KONTRATA__2E8B20C7577A1D9F] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [NRDOK] ON [dbo].[KONTRATA] ([NRDOK]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PKNRRENDOR] ON [dbo].[KONTRATA] ([NRRENDOR]) ON [PRIMARY]
GO
