CREATE TABLE [dbo].[OFERTEMARKETING]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[KOD] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DNGA] [datetime] NULL,
[DDERI] [datetime] NULL,
[VLNGA] [float] NULL,
[VLDERI] [float] NULL,
[PERKLILOYAL] [bit] NOT NULL CONSTRAINT [DF_OFERTEMARKETING_PERKLILOYAL] DEFAULT ((0)),
[KLILOYNGA] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KLILOYDERI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VLFIX] [bit] NOT NULL CONSTRAINT [DF_OFERTEMARKETING_VLFIX] DEFAULT ((0)),
[VLERZBR] [float] NULL,
[KUPONIRRADHES] [bit] NOT NULL CONSTRAINT [DF_OFERTEMARKETING_KUPONAKTUAL] DEFAULT ((0)),
[VLEFSHMERIA] [int] NOT NULL CONSTRAINT [DF_OFERTEMARKETING_VLEFSHMERIA] DEFAULT ((0)),
[MAGAZINAT] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shorte] [bit] NOT NULL CONSTRAINT [DF__OFERTEMAR__short__03A9ACE5] DEFAULT ((0)),
[allartc] [bit] NOT NULL CONSTRAINT [DF__OFERTEMAR__allar__049DD11E] DEFAULT ((0)),
[SORARIT] [bit] NOT NULL CONSTRAINT [DF__OFERTEMAR__SORAR__26A76B7B] DEFAULT ((0)),
[ONGA] [int] NOT NULL CONSTRAINT [DF__OFERTEMARK__ONGA__2A77FC5F] DEFAULT ((0)),
[ODERI] [int] NOT NULL CONSTRAINT [DF__OFERTEMAR__ODERI__2C6044D1] DEFAULT ((0)),
[NRFITUES] [int] NOT NULL CONSTRAINT [DF__OFERTEMAR__NRFIT__288FB3ED] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OFERTEMARKETING] ADD CONSTRAINT [PK_OFERTEMARKETING] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
