CREATE TABLE [dbo].[IVAERRORS]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[TYPE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOD] [int] NULL,
[PERSHKRIM] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IVAERRORS] ADD CONSTRAINT [PK_IVAERRORS] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
