CREATE TABLE [dbo].[IMPORTFILTER]
(
[NRRENDOR] [int] NOT NULL,
[NRD] [int] NOT NULL,
[LABEL] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INPUTTYPE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEFAULTVALUE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OPERATION] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATASETQUERY] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INPUTNAME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRUP] [int] NULL,
[ORDER] [int] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IMPORTFILTER] ADD CONSTRAINT [PK__IMPORTFI__3214EC272F6C2C45] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
