CREATE TABLE [dbo].[AQSCR]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[NRD] [int] NULL,
[KOD] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODAF] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KARTLLG] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRRENDKLLG] [int] NULL,
[PERSHKRIM] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NJESI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SASI] [float] NULL,
[CMIMM] [float] NULL,
[VLERAM] [float] NULL,
[KMON] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VLERAFT] [float] NULL,
[CMIMBS] [float] NULL,
[VLERABS] [decimal] (18, 2) NULL,
[KOEFSHB] [float] NULL,
[NJESINV] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIPKLL] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BC] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOMENT] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATEOPER] [datetime] NULL,
[CMIMOR] [float] NULL,
[VLERAOR] [float] NULL,
[TROW] [bit] NULL,
[TAGNR] [int] NULL,
[KODOPER] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NORMEAM] [float] NULL,
[VLERASH] [float] NULL,
[CMIMSH] [float] NULL,
[VLERAAM] [float] NULL,
[KURS1] [float] NULL,
[KURS2] [float] NULL,
[KODFKL] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIMFKL] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIMPRONESI] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NRSERIAL] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KODPRONESI] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATROW] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORDERSCR] [int] NULL,
[VLERAFAT] [float] NULL,
[VLERAFATMV] [float] NULL,
[VLERAEXTMV] [float] NULL,
[KODLOCATION] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIMLOCATION] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AMVLEREMBET] [bit] NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [AQSCRNRD] ON [dbo].[AQSCR] ([NRD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AQSCR] ADD CONSTRAINT [AQSCRNRRENDOR] UNIQUE NONCLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AQSCR] WITH NOCHECK ADD CONSTRAINT [FK_AQSCR_AQ] FOREIGN KEY ([NRD]) REFERENCES [dbo].[AQ] ([NRRENDOR]) ON DELETE CASCADE ON UPDATE CASCADE
GO
