CREATE TABLE [dbo].[SPECIALE]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[KOD] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AKTIV] [bit] NOT NULL CONSTRAINT [DF_SPECIALE_AKTIV] DEFAULT ((1))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SPECIALE] ADD CONSTRAINT [PK_SPECIALE] PRIMARY KEY CLUSTERED  ([NRRENDOR]) ON [PRIMARY]
GO
