CREATE TABLE [dbo].[PROCESE]
(
[NRRENDOR] [int] NOT NULL IDENTITY(1, 1),
[KOD] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSHKRIM] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VISIBLE] [bit] NOT NULL CONSTRAINT [DF__PROCESE__VISIBLE__7A6C23E6] DEFAULT ((1))
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
