CREATE TABLE [RS].[Cells]
(
[ID] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[RowID] [int] NULL,
[ColID] [int] NULL,
[Llogs] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsValue] [bit] NULL,
[Value] [float] NULL
) ON [PRIMARY]
GO
ALTER TABLE [RS].[Cells] ADD CONSTRAINT [PK_RS_RowColLlg] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [RS].[Cells] ADD CONSTRAINT [FK_RS_RowColLlg_RS_RapColumns] FOREIGN KEY ([ColID]) REFERENCES [RS].[Columns] ([ID])
GO
ALTER TABLE [RS].[Cells] ADD CONSTRAINT [FK_RS_RowColLlg_RS_RapRows] FOREIGN KEY ([RowID]) REFERENCES [RS].[Rows] ([ID]) ON DELETE CASCADE
GO
