CREATE TABLE [RS].[Columns]
(
[ID] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[RapID] [int] NULL,
[Pershkrim] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ColIndex] [int] NULL,
[IsTotal] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [RS].[Columns] ADD CONSTRAINT [PK__Columns__3214EC270AE185B0] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [RS].[Columns] ADD CONSTRAINT [FK_RS_RowColumns_RS_RAP] FOREIGN KEY ([RapID]) REFERENCES [RS].[Rap] ([ID]) ON DELETE CASCADE
GO
