CREATE TABLE [RS].[TotRows]
(
[RowID] [int] NOT NULL,
[TotRowID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [RS].[TotRows] ADD CONSTRAINT [FK_RS_TotRows_RS_RapRows] FOREIGN KEY ([RowID]) REFERENCES [RS].[Rows] ([ID]) ON DELETE CASCADE
GO
ALTER TABLE [RS].[TotRows] ADD CONSTRAINT [FK_RS_TotRows_RS_RapRows1] FOREIGN KEY ([TotRowID]) REFERENCES [RS].[Rows] ([ID])
GO
